/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockListBox.h"

typedef struct _CMOCK_LbCreate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  LISTBOX* ReturnVal;
  WORD Expected_ID;
  SHORT Expected_left;
  SHORT Expected_top;
  SHORT Expected_right;
  SHORT Expected_bottom;
  WORD Expected_state;
  XCHAR* Expected_pText;
  GOL_SCHEME* Expected_pScheme;

} CMOCK_LbCreate_CALL_INSTANCE;

typedef struct _CMOCK_LbAddItem_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  LISTITEM* ReturnVal;
  LISTBOX* Expected_pLb;
  LISTITEM* Expected_pPrevItem;
  XCHAR* Expected_pText;
  void* Expected_pBitmap;
  WORD Expected_status;
  WORD Expected_data;

} CMOCK_LbAddItem_CALL_INSTANCE;

typedef struct _CMOCK_LbDelItem_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  LISTBOX* Expected_pLb;
  LISTITEM* Expected_pItem;

} CMOCK_LbDelItem_CALL_INSTANCE;

typedef struct _CMOCK_LbDelItemsList_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  LISTBOX* Expected_pLb;

} CMOCK_LbDelItemsList_CALL_INSTANCE;

typedef struct _CMOCK_LbGetSel_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  LISTITEM* ReturnVal;
  LISTBOX* Expected_pLb;
  LISTITEM* Expected_pFromItem;

} CMOCK_LbGetSel_CALL_INSTANCE;

typedef struct _CMOCK_LbChangeSel_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  LISTBOX* Expected_pLb;
  LISTITEM* Expected_pItem;

} CMOCK_LbChangeSel_CALL_INSTANCE;

typedef struct _CMOCK_LbSetFocusedItem_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  LISTBOX* Expected_pLb;
  SHORT Expected_index;

} CMOCK_LbSetFocusedItem_CALL_INSTANCE;

typedef struct _CMOCK_LbGetFocusedItem_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  SHORT ReturnVal;
  LISTBOX* Expected_pLb;

} CMOCK_LbGetFocusedItem_CALL_INSTANCE;

typedef struct _CMOCK_LbTranslateMsg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD ReturnVal;
  LISTBOX* Expected_pLb;
  GOL_MSG* Expected_pMsg;

} CMOCK_LbTranslateMsg_CALL_INSTANCE;

typedef struct _CMOCK_LbMsgDefault_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD Expected_translatedMsg;
  LISTBOX* Expected_pLb;
  GOL_MSG* Expected_pMsg;

} CMOCK_LbMsgDefault_CALL_INSTANCE;

typedef struct _CMOCK_LbDraw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD ReturnVal;
  LISTBOX* Expected_pLb;

} CMOCK_LbDraw_CALL_INSTANCE;

static struct MockListBoxInstance
{
  CMOCK_MEM_INDEX_TYPE LbCreate_CallInstance;
  CMOCK_MEM_INDEX_TYPE LbAddItem_CallInstance;
  CMOCK_MEM_INDEX_TYPE LbDelItem_CallInstance;
  CMOCK_MEM_INDEX_TYPE LbDelItemsList_CallInstance;
  CMOCK_MEM_INDEX_TYPE LbGetSel_CallInstance;
  CMOCK_MEM_INDEX_TYPE LbChangeSel_CallInstance;
  CMOCK_MEM_INDEX_TYPE LbSetFocusedItem_CallInstance;
  CMOCK_MEM_INDEX_TYPE LbGetFocusedItem_CallInstance;
  CMOCK_MEM_INDEX_TYPE LbTranslateMsg_CallInstance;
  CMOCK_MEM_INDEX_TYPE LbMsgDefault_CallInstance;
  CMOCK_MEM_INDEX_TYPE LbDraw_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockListBox_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LbCreate_CallInstance, cmock_line, "Function 'LbCreate' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LbAddItem_CallInstance, cmock_line, "Function 'LbAddItem' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LbDelItem_CallInstance, cmock_line, "Function 'LbDelItem' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LbDelItemsList_CallInstance, cmock_line, "Function 'LbDelItemsList' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LbGetSel_CallInstance, cmock_line, "Function 'LbGetSel' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LbChangeSel_CallInstance, cmock_line, "Function 'LbChangeSel' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LbSetFocusedItem_CallInstance, cmock_line, "Function 'LbSetFocusedItem' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LbGetFocusedItem_CallInstance, cmock_line, "Function 'LbGetFocusedItem' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LbTranslateMsg_CallInstance, cmock_line, "Function 'LbTranslateMsg' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LbMsgDefault_CallInstance, cmock_line, "Function 'LbMsgDefault' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LbDraw_CallInstance, cmock_line, "Function 'LbDraw' called less times than expected.");
}

void MockListBox_Init(void)
{
  MockListBox_Destroy();
}

void MockListBox_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

LISTBOX* LbCreate(WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, XCHAR* pText, GOL_SCHEME* pScheme)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_LbCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LbCreate_CallInstance);
  Mock.LbCreate_CallInstance = CMock_Guts_MemNext(Mock.LbCreate_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'LbCreate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ID), (void*)(&ID), sizeof(WORD), cmock_line, "Function 'LbCreate' called with unexpected value for argument 'ID'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_left), (void*)(&left), sizeof(SHORT), cmock_line, "Function 'LbCreate' called with unexpected value for argument 'left'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_top), (void*)(&top), sizeof(SHORT), cmock_line, "Function 'LbCreate' called with unexpected value for argument 'top'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_right), (void*)(&right), sizeof(SHORT), cmock_line, "Function 'LbCreate' called with unexpected value for argument 'right'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bottom), (void*)(&bottom), sizeof(SHORT), cmock_line, "Function 'LbCreate' called with unexpected value for argument 'bottom'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(WORD), cmock_line, "Function 'LbCreate' called with unexpected value for argument 'state'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pText), (void*)(pText), sizeof(XCHAR), cmock_line, "Function 'LbCreate' called with unexpected value for argument 'pText'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pScheme), (void*)(pScheme), sizeof(GOL_SCHEME), cmock_line, "Function 'LbCreate' called with unexpected value for argument 'pScheme'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_LbCreate(CMOCK_LbCreate_CALL_INSTANCE* cmock_call_instance, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, XCHAR* pText, GOL_SCHEME* pScheme)
{
  memcpy(&cmock_call_instance->Expected_ID, &ID, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_left, &left, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_top, &top, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_right, &right, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_bottom, &bottom, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(WORD));
  cmock_call_instance->Expected_pText = pText;
  cmock_call_instance->Expected_pScheme = pScheme;
}

void LbCreate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, XCHAR* pText, GOL_SCHEME* pScheme, LISTBOX* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LbCreate_CALL_INSTANCE));
  CMOCK_LbCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.LbCreate_CallInstance = CMock_Guts_MemChain(Mock.LbCreate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_LbCreate(cmock_call_instance, ID, left, top, right, bottom, state, pText, pScheme);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

LISTITEM* LbAddItem(LISTBOX* pLb, LISTITEM* pPrevItem, XCHAR* pText, void* pBitmap, WORD status, WORD data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_LbAddItem_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbAddItem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LbAddItem_CallInstance);
  Mock.LbAddItem_CallInstance = CMock_Guts_MemNext(Mock.LbAddItem_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'LbAddItem' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pLb), (void*)(pLb), sizeof(LISTBOX), cmock_line, "Function 'LbAddItem' called with unexpected value for argument 'pLb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pPrevItem), (void*)(pPrevItem), sizeof(LISTITEM), cmock_line, "Function 'LbAddItem' called with unexpected value for argument 'pPrevItem'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pText), (void*)(pText), sizeof(XCHAR), cmock_line, "Function 'LbAddItem' called with unexpected value for argument 'pText'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_pBitmap, pBitmap, cmock_line, "Function 'LbAddItem' called with unexpected value for argument 'pBitmap'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_status), (void*)(&status), sizeof(WORD), cmock_line, "Function 'LbAddItem' called with unexpected value for argument 'status'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_data), (void*)(&data), sizeof(WORD), cmock_line, "Function 'LbAddItem' called with unexpected value for argument 'data'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_LbAddItem(CMOCK_LbAddItem_CALL_INSTANCE* cmock_call_instance, LISTBOX* pLb, LISTITEM* pPrevItem, XCHAR* pText, void* pBitmap, WORD status, WORD data)
{
  cmock_call_instance->Expected_pLb = pLb;
  cmock_call_instance->Expected_pPrevItem = pPrevItem;
  cmock_call_instance->Expected_pText = pText;
  cmock_call_instance->Expected_pBitmap = pBitmap;
  memcpy(&cmock_call_instance->Expected_status, &status, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_data, &data, sizeof(WORD));
}

void LbAddItem_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, LISTBOX* pLb, LISTITEM* pPrevItem, XCHAR* pText, void* pBitmap, WORD status, WORD data, LISTITEM* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LbAddItem_CALL_INSTANCE));
  CMOCK_LbAddItem_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbAddItem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.LbAddItem_CallInstance = CMock_Guts_MemChain(Mock.LbAddItem_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_LbAddItem(cmock_call_instance, pLb, pPrevItem, pText, pBitmap, status, data);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void LbDelItem(LISTBOX* pLb, LISTITEM* pItem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_LbDelItem_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbDelItem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LbDelItem_CallInstance);
  Mock.LbDelItem_CallInstance = CMock_Guts_MemNext(Mock.LbDelItem_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'LbDelItem' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pLb), (void*)(pLb), sizeof(LISTBOX), cmock_line, "Function 'LbDelItem' called with unexpected value for argument 'pLb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pItem), (void*)(pItem), sizeof(LISTITEM), cmock_line, "Function 'LbDelItem' called with unexpected value for argument 'pItem'.");
  }
}

void CMockExpectParameters_LbDelItem(CMOCK_LbDelItem_CALL_INSTANCE* cmock_call_instance, LISTBOX* pLb, LISTITEM* pItem)
{
  cmock_call_instance->Expected_pLb = pLb;
  cmock_call_instance->Expected_pItem = pItem;
}

void LbDelItem_CMockExpect(UNITY_LINE_TYPE cmock_line, LISTBOX* pLb, LISTITEM* pItem)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LbDelItem_CALL_INSTANCE));
  CMOCK_LbDelItem_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbDelItem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.LbDelItem_CallInstance = CMock_Guts_MemChain(Mock.LbDelItem_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_LbDelItem(cmock_call_instance, pLb, pItem);
}

void LbDelItemsList(LISTBOX* pLb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_LbDelItemsList_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbDelItemsList_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LbDelItemsList_CallInstance);
  Mock.LbDelItemsList_CallInstance = CMock_Guts_MemNext(Mock.LbDelItemsList_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'LbDelItemsList' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pLb), (void*)(pLb), sizeof(LISTBOX), cmock_line, "Function 'LbDelItemsList' called with unexpected value for argument 'pLb'.");
  }
}

void CMockExpectParameters_LbDelItemsList(CMOCK_LbDelItemsList_CALL_INSTANCE* cmock_call_instance, LISTBOX* pLb)
{
  cmock_call_instance->Expected_pLb = pLb;
}

void LbDelItemsList_CMockExpect(UNITY_LINE_TYPE cmock_line, LISTBOX* pLb)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LbDelItemsList_CALL_INSTANCE));
  CMOCK_LbDelItemsList_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbDelItemsList_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.LbDelItemsList_CallInstance = CMock_Guts_MemChain(Mock.LbDelItemsList_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_LbDelItemsList(cmock_call_instance, pLb);
}

LISTITEM* LbGetSel(LISTBOX* pLb, LISTITEM* pFromItem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_LbGetSel_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbGetSel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LbGetSel_CallInstance);
  Mock.LbGetSel_CallInstance = CMock_Guts_MemNext(Mock.LbGetSel_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'LbGetSel' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pLb), (void*)(pLb), sizeof(LISTBOX), cmock_line, "Function 'LbGetSel' called with unexpected value for argument 'pLb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pFromItem), (void*)(pFromItem), sizeof(LISTITEM), cmock_line, "Function 'LbGetSel' called with unexpected value for argument 'pFromItem'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_LbGetSel(CMOCK_LbGetSel_CALL_INSTANCE* cmock_call_instance, LISTBOX* pLb, LISTITEM* pFromItem)
{
  cmock_call_instance->Expected_pLb = pLb;
  cmock_call_instance->Expected_pFromItem = pFromItem;
}

void LbGetSel_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, LISTBOX* pLb, LISTITEM* pFromItem, LISTITEM* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LbGetSel_CALL_INSTANCE));
  CMOCK_LbGetSel_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbGetSel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.LbGetSel_CallInstance = CMock_Guts_MemChain(Mock.LbGetSel_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_LbGetSel(cmock_call_instance, pLb, pFromItem);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void LbChangeSel(LISTBOX* pLb, LISTITEM* pItem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_LbChangeSel_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbChangeSel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LbChangeSel_CallInstance);
  Mock.LbChangeSel_CallInstance = CMock_Guts_MemNext(Mock.LbChangeSel_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'LbChangeSel' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pLb), (void*)(pLb), sizeof(LISTBOX), cmock_line, "Function 'LbChangeSel' called with unexpected value for argument 'pLb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pItem), (void*)(pItem), sizeof(LISTITEM), cmock_line, "Function 'LbChangeSel' called with unexpected value for argument 'pItem'.");
  }
}

void CMockExpectParameters_LbChangeSel(CMOCK_LbChangeSel_CALL_INSTANCE* cmock_call_instance, LISTBOX* pLb, LISTITEM* pItem)
{
  cmock_call_instance->Expected_pLb = pLb;
  cmock_call_instance->Expected_pItem = pItem;
}

void LbChangeSel_CMockExpect(UNITY_LINE_TYPE cmock_line, LISTBOX* pLb, LISTITEM* pItem)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LbChangeSel_CALL_INSTANCE));
  CMOCK_LbChangeSel_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbChangeSel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.LbChangeSel_CallInstance = CMock_Guts_MemChain(Mock.LbChangeSel_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_LbChangeSel(cmock_call_instance, pLb, pItem);
}

void LbSetFocusedItem(LISTBOX* pLb, SHORT index)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_LbSetFocusedItem_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbSetFocusedItem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LbSetFocusedItem_CallInstance);
  Mock.LbSetFocusedItem_CallInstance = CMock_Guts_MemNext(Mock.LbSetFocusedItem_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'LbSetFocusedItem' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pLb), (void*)(pLb), sizeof(LISTBOX), cmock_line, "Function 'LbSetFocusedItem' called with unexpected value for argument 'pLb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_index), (void*)(&index), sizeof(SHORT), cmock_line, "Function 'LbSetFocusedItem' called with unexpected value for argument 'index'.");
  }
}

void CMockExpectParameters_LbSetFocusedItem(CMOCK_LbSetFocusedItem_CALL_INSTANCE* cmock_call_instance, LISTBOX* pLb, SHORT index)
{
  cmock_call_instance->Expected_pLb = pLb;
  memcpy(&cmock_call_instance->Expected_index, &index, sizeof(SHORT));
}

void LbSetFocusedItem_CMockExpect(UNITY_LINE_TYPE cmock_line, LISTBOX* pLb, SHORT index)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LbSetFocusedItem_CALL_INSTANCE));
  CMOCK_LbSetFocusedItem_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbSetFocusedItem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.LbSetFocusedItem_CallInstance = CMock_Guts_MemChain(Mock.LbSetFocusedItem_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_LbSetFocusedItem(cmock_call_instance, pLb, index);
}

SHORT LbGetFocusedItem(LISTBOX* pLb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_LbGetFocusedItem_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbGetFocusedItem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LbGetFocusedItem_CallInstance);
  Mock.LbGetFocusedItem_CallInstance = CMock_Guts_MemNext(Mock.LbGetFocusedItem_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'LbGetFocusedItem' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pLb), (void*)(pLb), sizeof(LISTBOX), cmock_line, "Function 'LbGetFocusedItem' called with unexpected value for argument 'pLb'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_LbGetFocusedItem(CMOCK_LbGetFocusedItem_CALL_INSTANCE* cmock_call_instance, LISTBOX* pLb)
{
  cmock_call_instance->Expected_pLb = pLb;
}

void LbGetFocusedItem_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, LISTBOX* pLb, SHORT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LbGetFocusedItem_CALL_INSTANCE));
  CMOCK_LbGetFocusedItem_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbGetFocusedItem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.LbGetFocusedItem_CallInstance = CMock_Guts_MemChain(Mock.LbGetFocusedItem_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_LbGetFocusedItem(cmock_call_instance, pLb);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(SHORT));
}

WORD LbTranslateMsg(LISTBOX* pLb, GOL_MSG* pMsg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_LbTranslateMsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbTranslateMsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LbTranslateMsg_CallInstance);
  Mock.LbTranslateMsg_CallInstance = CMock_Guts_MemNext(Mock.LbTranslateMsg_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'LbTranslateMsg' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pLb), (void*)(pLb), sizeof(LISTBOX), cmock_line, "Function 'LbTranslateMsg' called with unexpected value for argument 'pLb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMsg), (void*)(pMsg), sizeof(GOL_MSG), cmock_line, "Function 'LbTranslateMsg' called with unexpected value for argument 'pMsg'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_LbTranslateMsg(CMOCK_LbTranslateMsg_CALL_INSTANCE* cmock_call_instance, LISTBOX* pLb, GOL_MSG* pMsg)
{
  cmock_call_instance->Expected_pLb = pLb;
  cmock_call_instance->Expected_pMsg = pMsg;
}

void LbTranslateMsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, LISTBOX* pLb, GOL_MSG* pMsg, WORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LbTranslateMsg_CALL_INSTANCE));
  CMOCK_LbTranslateMsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbTranslateMsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.LbTranslateMsg_CallInstance = CMock_Guts_MemChain(Mock.LbTranslateMsg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_LbTranslateMsg(cmock_call_instance, pLb, pMsg);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(WORD));
}

void LbMsgDefault(WORD translatedMsg, LISTBOX* pLb, GOL_MSG* pMsg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_LbMsgDefault_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbMsgDefault_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LbMsgDefault_CallInstance);
  Mock.LbMsgDefault_CallInstance = CMock_Guts_MemNext(Mock.LbMsgDefault_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'LbMsgDefault' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_translatedMsg), (void*)(&translatedMsg), sizeof(WORD), cmock_line, "Function 'LbMsgDefault' called with unexpected value for argument 'translatedMsg'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pLb), (void*)(pLb), sizeof(LISTBOX), cmock_line, "Function 'LbMsgDefault' called with unexpected value for argument 'pLb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMsg), (void*)(pMsg), sizeof(GOL_MSG), cmock_line, "Function 'LbMsgDefault' called with unexpected value for argument 'pMsg'.");
  }
}

void CMockExpectParameters_LbMsgDefault(CMOCK_LbMsgDefault_CALL_INSTANCE* cmock_call_instance, WORD translatedMsg, LISTBOX* pLb, GOL_MSG* pMsg)
{
  memcpy(&cmock_call_instance->Expected_translatedMsg, &translatedMsg, sizeof(WORD));
  cmock_call_instance->Expected_pLb = pLb;
  cmock_call_instance->Expected_pMsg = pMsg;
}

void LbMsgDefault_CMockExpect(UNITY_LINE_TYPE cmock_line, WORD translatedMsg, LISTBOX* pLb, GOL_MSG* pMsg)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LbMsgDefault_CALL_INSTANCE));
  CMOCK_LbMsgDefault_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbMsgDefault_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.LbMsgDefault_CallInstance = CMock_Guts_MemChain(Mock.LbMsgDefault_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_LbMsgDefault(cmock_call_instance, translatedMsg, pLb, pMsg);
}

WORD LbDraw(LISTBOX* pLb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_LbDraw_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbDraw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LbDraw_CallInstance);
  Mock.LbDraw_CallInstance = CMock_Guts_MemNext(Mock.LbDraw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'LbDraw' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pLb), (void*)(pLb), sizeof(LISTBOX), cmock_line, "Function 'LbDraw' called with unexpected value for argument 'pLb'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_LbDraw(CMOCK_LbDraw_CALL_INSTANCE* cmock_call_instance, LISTBOX* pLb)
{
  cmock_call_instance->Expected_pLb = pLb;
}

void LbDraw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, LISTBOX* pLb, WORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LbDraw_CALL_INSTANCE));
  CMOCK_LbDraw_CALL_INSTANCE* cmock_call_instance = (CMOCK_LbDraw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.LbDraw_CallInstance = CMock_Guts_MemChain(Mock.LbDraw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_LbDraw(cmock_call_instance, pLb);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(WORD));
}

