/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKUART2_H
#define _MOCKUART2_H

#include "uart2.h"

void Mockuart2_Init(void);
void Mockuart2_Destroy(void);
void Mockuart2_Verify(void);




#define UART2GetBaudError_ExpectAndReturn(cmock_retval) UART2GetBaudError_CMockExpectAndReturn(__LINE__, cmock_retval)
void UART2GetBaudError_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char cmock_to_return);
#define UART2GetChar_ExpectAndReturn(cmock_retval) UART2GetChar_CMockExpectAndReturn(__LINE__, cmock_retval)
void UART2GetChar_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char cmock_to_return);
#define UART2PutChar_Expect(ch) UART2PutChar_CMockExpect(__LINE__, ch)
void UART2PutChar_CMockExpect(UNITY_LINE_TYPE cmock_line, char ch);
#define UART2Init_Expect() UART2Init_CMockExpect(__LINE__)
void UART2Init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define UART2IsPressed_ExpectAndReturn(cmock_retval) UART2IsPressed_CMockExpectAndReturn(__LINE__, cmock_retval)
void UART2IsPressed_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char cmock_to_return);
#define UART2PrintString_Expect(str) UART2PrintString_CMockExpect(__LINE__, str)
void UART2PrintString_CMockExpect(UNITY_LINE_TYPE cmock_line, char* str);
#define UART2PutDec_Expect(dec) UART2PutDec_CMockExpect(__LINE__, dec)
void UART2PutDec_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char dec);
#define UART2PutHex_Expect(toPrint) UART2PutHex_CMockExpect(__LINE__, toPrint)
void UART2PutHex_CMockExpect(UNITY_LINE_TYPE cmock_line, int toPrint);
#define UART2PutHexWord_Expect(toPrint) UART2PutHexWord_CMockExpect(__LINE__, toPrint)
void UART2PutHexWord_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned int toPrint);
#define UART2PutHexDWord_Expect(toPrint) UART2PutHexDWord_CMockExpect(__LINE__, toPrint)
void UART2PutHexDWord_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned long int toPrint);
#define UART2Char2Hex_ExpectAndReturn(ch, cmock_retval) UART2Char2Hex_CMockExpectAndReturn(__LINE__, ch, cmock_retval)
void UART2Char2Hex_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char ch, char cmock_to_return);
#define UART2Hex2Char_ExpectAndReturn(hex, cmock_retval) UART2Hex2Char_CMockExpectAndReturn(__LINE__, hex, cmock_retval)
void UART2Hex2Char_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char hex, char cmock_to_return);
#define UART2ClrError_Expect() UART2ClrError_CMockExpect(__LINE__)
void UART2ClrError_CMockExpect(UNITY_LINE_TYPE cmock_line);

#endif
