/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockRunningAverage.h"

typedef struct _CMOCK_newDefaultRunningAverage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RunningAverage* ReturnVal;

} CMOCK_newDefaultRunningAverage_CALL_INSTANCE;

typedef struct _CMOCK_newRunningAverage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RunningAverage* ReturnVal;
  float Expected_initialAverage;
  int Expected_sampleRate;
  int Expected_minTime;
  int Expected_maxTime;
  int Expected_minTimeThreshold;

} CMOCK_newRunningAverage_CALL_INSTANCE;

typedef struct _CMOCK_initDefaultRunningAverage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RunningAverage* Expected_ra;

} CMOCK_initDefaultRunningAverage_CALL_INSTANCE;

typedef struct _CMOCK_initRunningAverage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RunningAverage* Expected_ra;
  float Expected_initialAverage;
  int Expected_sampleRate;
  int Expected_minTime;
  int Expected_maxTime;
  int Expected_minTimeThreshold;

} CMOCK_initRunningAverage_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageGetNewSample_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  RunningAverage* Expected_ra;

} CMOCK_runningAverageGetNewSample_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageSetNewSample_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RunningAverage* Expected_ra;
  int Expected_sample;

} CMOCK_runningAverageSetNewSample_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageGetAverage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  float ReturnVal;
  RunningAverage* Expected_ra;

} CMOCK_runningAverageGetAverage_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageCalcNewSampleWeight_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  RunningAverage* Expected_ra;

} CMOCK_runningAverageCalcNewSampleWeight_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageSetSampleRate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RunningAverage* Expected_ra;
  int Expected_rate;

} CMOCK_runningAverageSetSampleRate_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageSetMaxTime_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RunningAverage* Expected_ra;
  int Expected_max;

} CMOCK_runningAverageSetMaxTime_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageSetMinTime_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RunningAverage* Expected_ra;
  int Expected_min;

} CMOCK_runningAverageSetMinTime_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageGetMaxTimeThreshold_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  RunningAverage* Expected_ra;

} CMOCK_runningAverageGetMaxTimeThreshold_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageSetMaxTimeThreshold_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RunningAverage* Expected_ra;
  int Expected_background;

} CMOCK_runningAverageSetMaxTimeThreshold_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageGetMinTimeThreshold_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  RunningAverage* Expected_ra;

} CMOCK_runningAverageGetMinTimeThreshold_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageSetMinTimeThreshold_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RunningAverage* Expected_ra;
  int Expected_max;

} CMOCK_runningAverageSetMinTimeThreshold_CALL_INSTANCE;

typedef struct _CMOCK_runningAverageCalcNumSpeeds_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  RunningAverage* Expected_ra;

} CMOCK_runningAverageCalcNumSpeeds_CALL_INSTANCE;

static struct MockRunningAverageInstance
{
  CMOCK_MEM_INDEX_TYPE newDefaultRunningAverage_CallInstance;
  CMOCK_MEM_INDEX_TYPE newRunningAverage_CallInstance;
  CMOCK_MEM_INDEX_TYPE initDefaultRunningAverage_CallInstance;
  CMOCK_MEM_INDEX_TYPE initRunningAverage_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageGetNewSample_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageSetNewSample_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageGetAverage_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageCalcNewSampleWeight_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageSetSampleRate_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageSetMaxTime_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageSetMinTime_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageGetMaxTimeThreshold_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageSetMaxTimeThreshold_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageGetMinTimeThreshold_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageSetMinTimeThreshold_CallInstance;
  CMOCK_MEM_INDEX_TYPE runningAverageCalcNumSpeeds_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockRunningAverage_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.newDefaultRunningAverage_CallInstance, cmock_line, "Function 'newDefaultRunningAverage' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.newRunningAverage_CallInstance, cmock_line, "Function 'newRunningAverage' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.initDefaultRunningAverage_CallInstance, cmock_line, "Function 'initDefaultRunningAverage' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.initRunningAverage_CallInstance, cmock_line, "Function 'initRunningAverage' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageGetNewSample_CallInstance, cmock_line, "Function 'runningAverageGetNewSample' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageSetNewSample_CallInstance, cmock_line, "Function 'runningAverageSetNewSample' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageGetAverage_CallInstance, cmock_line, "Function 'runningAverageGetAverage' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageCalcNewSampleWeight_CallInstance, cmock_line, "Function 'runningAverageCalcNewSampleWeight' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageSetSampleRate_CallInstance, cmock_line, "Function 'runningAverageSetSampleRate' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageSetMaxTime_CallInstance, cmock_line, "Function 'runningAverageSetMaxTime' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageSetMinTime_CallInstance, cmock_line, "Function 'runningAverageSetMinTime' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageGetMaxTimeThreshold_CallInstance, cmock_line, "Function 'runningAverageGetMaxTimeThreshold' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageSetMaxTimeThreshold_CallInstance, cmock_line, "Function 'runningAverageSetMaxTimeThreshold' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageGetMinTimeThreshold_CallInstance, cmock_line, "Function 'runningAverageGetMinTimeThreshold' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageSetMinTimeThreshold_CallInstance, cmock_line, "Function 'runningAverageSetMinTimeThreshold' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.runningAverageCalcNumSpeeds_CallInstance, cmock_line, "Function 'runningAverageCalcNumSpeeds' called less times than expected.");
}

void MockRunningAverage_Init(void)
{
  MockRunningAverage_Destroy();
}

void MockRunningAverage_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

RunningAverage* newDefaultRunningAverage(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_newDefaultRunningAverage_CALL_INSTANCE* cmock_call_instance = (CMOCK_newDefaultRunningAverage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.newDefaultRunningAverage_CallInstance);
  Mock.newDefaultRunningAverage_CallInstance = CMock_Guts_MemNext(Mock.newDefaultRunningAverage_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'newDefaultRunningAverage' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void newDefaultRunningAverage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RunningAverage* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_newDefaultRunningAverage_CALL_INSTANCE));
  CMOCK_newDefaultRunningAverage_CALL_INSTANCE* cmock_call_instance = (CMOCK_newDefaultRunningAverage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.newDefaultRunningAverage_CallInstance = CMock_Guts_MemChain(Mock.newDefaultRunningAverage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

RunningAverage* newRunningAverage(float initialAverage, int sampleRate, int minTime, int maxTime, int minTimeThreshold)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_newRunningAverage_CALL_INSTANCE* cmock_call_instance = (CMOCK_newRunningAverage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.newRunningAverage_CallInstance);
  Mock.newRunningAverage_CallInstance = CMock_Guts_MemNext(Mock.newRunningAverage_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'newRunningAverage' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_FLOAT(cmock_call_instance->Expected_initialAverage, initialAverage, cmock_line, "Function 'newRunningAverage' called with unexpected value for argument 'initialAverage'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_sampleRate, sampleRate, cmock_line, "Function 'newRunningAverage' called with unexpected value for argument 'sampleRate'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_minTime, minTime, cmock_line, "Function 'newRunningAverage' called with unexpected value for argument 'minTime'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_maxTime, maxTime, cmock_line, "Function 'newRunningAverage' called with unexpected value for argument 'maxTime'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_minTimeThreshold, minTimeThreshold, cmock_line, "Function 'newRunningAverage' called with unexpected value for argument 'minTimeThreshold'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_newRunningAverage(CMOCK_newRunningAverage_CALL_INSTANCE* cmock_call_instance, float initialAverage, int sampleRate, int minTime, int maxTime, int minTimeThreshold)
{
  cmock_call_instance->Expected_initialAverage = initialAverage;
  cmock_call_instance->Expected_sampleRate = sampleRate;
  cmock_call_instance->Expected_minTime = minTime;
  cmock_call_instance->Expected_maxTime = maxTime;
  cmock_call_instance->Expected_minTimeThreshold = minTimeThreshold;
}

void newRunningAverage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, float initialAverage, int sampleRate, int minTime, int maxTime, int minTimeThreshold, RunningAverage* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_newRunningAverage_CALL_INSTANCE));
  CMOCK_newRunningAverage_CALL_INSTANCE* cmock_call_instance = (CMOCK_newRunningAverage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.newRunningAverage_CallInstance = CMock_Guts_MemChain(Mock.newRunningAverage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_newRunningAverage(cmock_call_instance, initialAverage, sampleRate, minTime, maxTime, minTimeThreshold);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void initDefaultRunningAverage(RunningAverage* ra)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_initDefaultRunningAverage_CALL_INSTANCE* cmock_call_instance = (CMOCK_initDefaultRunningAverage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.initDefaultRunningAverage_CallInstance);
  Mock.initDefaultRunningAverage_CallInstance = CMock_Guts_MemNext(Mock.initDefaultRunningAverage_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'initDefaultRunningAverage' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'initDefaultRunningAverage' called with unexpected value for argument 'ra'.");
  }
}

void CMockExpectParameters_initDefaultRunningAverage(CMOCK_initDefaultRunningAverage_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra)
{
  cmock_call_instance->Expected_ra = ra;
}

void initDefaultRunningAverage_CMockExpect(UNITY_LINE_TYPE cmock_line, RunningAverage* ra)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_initDefaultRunningAverage_CALL_INSTANCE));
  CMOCK_initDefaultRunningAverage_CALL_INSTANCE* cmock_call_instance = (CMOCK_initDefaultRunningAverage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.initDefaultRunningAverage_CallInstance = CMock_Guts_MemChain(Mock.initDefaultRunningAverage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_initDefaultRunningAverage(cmock_call_instance, ra);
}

void initRunningAverage(RunningAverage* ra, float initialAverage, int sampleRate, int minTime, int maxTime, int minTimeThreshold)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_initRunningAverage_CALL_INSTANCE* cmock_call_instance = (CMOCK_initRunningAverage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.initRunningAverage_CallInstance);
  Mock.initRunningAverage_CallInstance = CMock_Guts_MemNext(Mock.initRunningAverage_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'initRunningAverage' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'initRunningAverage' called with unexpected value for argument 'ra'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_FLOAT(cmock_call_instance->Expected_initialAverage, initialAverage, cmock_line, "Function 'initRunningAverage' called with unexpected value for argument 'initialAverage'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_sampleRate, sampleRate, cmock_line, "Function 'initRunningAverage' called with unexpected value for argument 'sampleRate'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_minTime, minTime, cmock_line, "Function 'initRunningAverage' called with unexpected value for argument 'minTime'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_maxTime, maxTime, cmock_line, "Function 'initRunningAverage' called with unexpected value for argument 'maxTime'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_minTimeThreshold, minTimeThreshold, cmock_line, "Function 'initRunningAverage' called with unexpected value for argument 'minTimeThreshold'.");
  }
}

void CMockExpectParameters_initRunningAverage(CMOCK_initRunningAverage_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra, float initialAverage, int sampleRate, int minTime, int maxTime, int minTimeThreshold)
{
  cmock_call_instance->Expected_ra = ra;
  cmock_call_instance->Expected_initialAverage = initialAverage;
  cmock_call_instance->Expected_sampleRate = sampleRate;
  cmock_call_instance->Expected_minTime = minTime;
  cmock_call_instance->Expected_maxTime = maxTime;
  cmock_call_instance->Expected_minTimeThreshold = minTimeThreshold;
}

void initRunningAverage_CMockExpect(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, float initialAverage, int sampleRate, int minTime, int maxTime, int minTimeThreshold)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_initRunningAverage_CALL_INSTANCE));
  CMOCK_initRunningAverage_CALL_INSTANCE* cmock_call_instance = (CMOCK_initRunningAverage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.initRunningAverage_CallInstance = CMock_Guts_MemChain(Mock.initRunningAverage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_initRunningAverage(cmock_call_instance, ra, initialAverage, sampleRate, minTime, maxTime, minTimeThreshold);
}

int runningAverageGetNewSample(RunningAverage* ra)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageGetNewSample_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageGetNewSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageGetNewSample_CallInstance);
  Mock.runningAverageGetNewSample_CallInstance = CMock_Guts_MemNext(Mock.runningAverageGetNewSample_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageGetNewSample' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageGetNewSample' called with unexpected value for argument 'ra'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_runningAverageGetNewSample(CMOCK_runningAverageGetNewSample_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra)
{
  cmock_call_instance->Expected_ra = ra;
}

void runningAverageGetNewSample_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageGetNewSample_CALL_INSTANCE));
  CMOCK_runningAverageGetNewSample_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageGetNewSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageGetNewSample_CallInstance = CMock_Guts_MemChain(Mock.runningAverageGetNewSample_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageGetNewSample(cmock_call_instance, ra);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void runningAverageSetNewSample(RunningAverage* ra, int sample)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageSetNewSample_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetNewSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageSetNewSample_CallInstance);
  Mock.runningAverageSetNewSample_CallInstance = CMock_Guts_MemNext(Mock.runningAverageSetNewSample_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageSetNewSample' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageSetNewSample' called with unexpected value for argument 'ra'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_sample, sample, cmock_line, "Function 'runningAverageSetNewSample' called with unexpected value for argument 'sample'.");
  }
}

void CMockExpectParameters_runningAverageSetNewSample(CMOCK_runningAverageSetNewSample_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra, int sample)
{
  cmock_call_instance->Expected_ra = ra;
  cmock_call_instance->Expected_sample = sample;
}

void runningAverageSetNewSample_CMockExpect(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, int sample)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageSetNewSample_CALL_INSTANCE));
  CMOCK_runningAverageSetNewSample_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetNewSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageSetNewSample_CallInstance = CMock_Guts_MemChain(Mock.runningAverageSetNewSample_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageSetNewSample(cmock_call_instance, ra, sample);
}

float runningAverageGetAverage(RunningAverage* ra)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageGetAverage_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageGetAverage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageGetAverage_CallInstance);
  Mock.runningAverageGetAverage_CallInstance = CMock_Guts_MemNext(Mock.runningAverageGetAverage_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageGetAverage' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageGetAverage' called with unexpected value for argument 'ra'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_runningAverageGetAverage(CMOCK_runningAverageGetAverage_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra)
{
  cmock_call_instance->Expected_ra = ra;
}

void runningAverageGetAverage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, float cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageGetAverage_CALL_INSTANCE));
  CMOCK_runningAverageGetAverage_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageGetAverage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageGetAverage_CallInstance = CMock_Guts_MemChain(Mock.runningAverageGetAverage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageGetAverage(cmock_call_instance, ra);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int runningAverageCalcNewSampleWeight(RunningAverage* ra)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageCalcNewSampleWeight_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageCalcNewSampleWeight_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageCalcNewSampleWeight_CallInstance);
  Mock.runningAverageCalcNewSampleWeight_CallInstance = CMock_Guts_MemNext(Mock.runningAverageCalcNewSampleWeight_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageCalcNewSampleWeight' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageCalcNewSampleWeight' called with unexpected value for argument 'ra'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_runningAverageCalcNewSampleWeight(CMOCK_runningAverageCalcNewSampleWeight_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra)
{
  cmock_call_instance->Expected_ra = ra;
}

void runningAverageCalcNewSampleWeight_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageCalcNewSampleWeight_CALL_INSTANCE));
  CMOCK_runningAverageCalcNewSampleWeight_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageCalcNewSampleWeight_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageCalcNewSampleWeight_CallInstance = CMock_Guts_MemChain(Mock.runningAverageCalcNewSampleWeight_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageCalcNewSampleWeight(cmock_call_instance, ra);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void runningAverageSetSampleRate(RunningAverage* ra, int rate)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageSetSampleRate_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetSampleRate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageSetSampleRate_CallInstance);
  Mock.runningAverageSetSampleRate_CallInstance = CMock_Guts_MemNext(Mock.runningAverageSetSampleRate_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageSetSampleRate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageSetSampleRate' called with unexpected value for argument 'ra'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_rate, rate, cmock_line, "Function 'runningAverageSetSampleRate' called with unexpected value for argument 'rate'.");
  }
}

void CMockExpectParameters_runningAverageSetSampleRate(CMOCK_runningAverageSetSampleRate_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra, int rate)
{
  cmock_call_instance->Expected_ra = ra;
  cmock_call_instance->Expected_rate = rate;
}

void runningAverageSetSampleRate_CMockExpect(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, int rate)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageSetSampleRate_CALL_INSTANCE));
  CMOCK_runningAverageSetSampleRate_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetSampleRate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageSetSampleRate_CallInstance = CMock_Guts_MemChain(Mock.runningAverageSetSampleRate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageSetSampleRate(cmock_call_instance, ra, rate);
}

void runningAverageSetMaxTime(RunningAverage* ra, int max)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageSetMaxTime_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetMaxTime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageSetMaxTime_CallInstance);
  Mock.runningAverageSetMaxTime_CallInstance = CMock_Guts_MemNext(Mock.runningAverageSetMaxTime_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageSetMaxTime' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageSetMaxTime' called with unexpected value for argument 'ra'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_max, max, cmock_line, "Function 'runningAverageSetMaxTime' called with unexpected value for argument 'max'.");
  }
}

void CMockExpectParameters_runningAverageSetMaxTime(CMOCK_runningAverageSetMaxTime_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra, int max)
{
  cmock_call_instance->Expected_ra = ra;
  cmock_call_instance->Expected_max = max;
}

void runningAverageSetMaxTime_CMockExpect(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, int max)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageSetMaxTime_CALL_INSTANCE));
  CMOCK_runningAverageSetMaxTime_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetMaxTime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageSetMaxTime_CallInstance = CMock_Guts_MemChain(Mock.runningAverageSetMaxTime_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageSetMaxTime(cmock_call_instance, ra, max);
}

void runningAverageSetMinTime(RunningAverage* ra, int min)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageSetMinTime_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetMinTime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageSetMinTime_CallInstance);
  Mock.runningAverageSetMinTime_CallInstance = CMock_Guts_MemNext(Mock.runningAverageSetMinTime_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageSetMinTime' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageSetMinTime' called with unexpected value for argument 'ra'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_min, min, cmock_line, "Function 'runningAverageSetMinTime' called with unexpected value for argument 'min'.");
  }
}

void CMockExpectParameters_runningAverageSetMinTime(CMOCK_runningAverageSetMinTime_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra, int min)
{
  cmock_call_instance->Expected_ra = ra;
  cmock_call_instance->Expected_min = min;
}

void runningAverageSetMinTime_CMockExpect(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, int min)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageSetMinTime_CALL_INSTANCE));
  CMOCK_runningAverageSetMinTime_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetMinTime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageSetMinTime_CallInstance = CMock_Guts_MemChain(Mock.runningAverageSetMinTime_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageSetMinTime(cmock_call_instance, ra, min);
}

int runningAverageGetMaxTimeThreshold(RunningAverage* ra)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageGetMaxTimeThreshold_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageGetMaxTimeThreshold_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageGetMaxTimeThreshold_CallInstance);
  Mock.runningAverageGetMaxTimeThreshold_CallInstance = CMock_Guts_MemNext(Mock.runningAverageGetMaxTimeThreshold_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageGetMaxTimeThreshold' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageGetMaxTimeThreshold' called with unexpected value for argument 'ra'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_runningAverageGetMaxTimeThreshold(CMOCK_runningAverageGetMaxTimeThreshold_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra)
{
  cmock_call_instance->Expected_ra = ra;
}

void runningAverageGetMaxTimeThreshold_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageGetMaxTimeThreshold_CALL_INSTANCE));
  CMOCK_runningAverageGetMaxTimeThreshold_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageGetMaxTimeThreshold_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageGetMaxTimeThreshold_CallInstance = CMock_Guts_MemChain(Mock.runningAverageGetMaxTimeThreshold_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageGetMaxTimeThreshold(cmock_call_instance, ra);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void runningAverageSetMaxTimeThreshold(RunningAverage* ra, int background)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageSetMaxTimeThreshold_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetMaxTimeThreshold_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageSetMaxTimeThreshold_CallInstance);
  Mock.runningAverageSetMaxTimeThreshold_CallInstance = CMock_Guts_MemNext(Mock.runningAverageSetMaxTimeThreshold_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageSetMaxTimeThreshold' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageSetMaxTimeThreshold' called with unexpected value for argument 'ra'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_background, background, cmock_line, "Function 'runningAverageSetMaxTimeThreshold' called with unexpected value for argument 'background'.");
  }
}

void CMockExpectParameters_runningAverageSetMaxTimeThreshold(CMOCK_runningAverageSetMaxTimeThreshold_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra, int background)
{
  cmock_call_instance->Expected_ra = ra;
  cmock_call_instance->Expected_background = background;
}

void runningAverageSetMaxTimeThreshold_CMockExpect(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, int background)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageSetMaxTimeThreshold_CALL_INSTANCE));
  CMOCK_runningAverageSetMaxTimeThreshold_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetMaxTimeThreshold_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageSetMaxTimeThreshold_CallInstance = CMock_Guts_MemChain(Mock.runningAverageSetMaxTimeThreshold_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageSetMaxTimeThreshold(cmock_call_instance, ra, background);
}

int runningAverageGetMinTimeThreshold(RunningAverage* ra)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageGetMinTimeThreshold_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageGetMinTimeThreshold_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageGetMinTimeThreshold_CallInstance);
  Mock.runningAverageGetMinTimeThreshold_CallInstance = CMock_Guts_MemNext(Mock.runningAverageGetMinTimeThreshold_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageGetMinTimeThreshold' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageGetMinTimeThreshold' called with unexpected value for argument 'ra'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_runningAverageGetMinTimeThreshold(CMOCK_runningAverageGetMinTimeThreshold_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra)
{
  cmock_call_instance->Expected_ra = ra;
}

void runningAverageGetMinTimeThreshold_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageGetMinTimeThreshold_CALL_INSTANCE));
  CMOCK_runningAverageGetMinTimeThreshold_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageGetMinTimeThreshold_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageGetMinTimeThreshold_CallInstance = CMock_Guts_MemChain(Mock.runningAverageGetMinTimeThreshold_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageGetMinTimeThreshold(cmock_call_instance, ra);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void runningAverageSetMinTimeThreshold(RunningAverage* ra, int max)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageSetMinTimeThreshold_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetMinTimeThreshold_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageSetMinTimeThreshold_CallInstance);
  Mock.runningAverageSetMinTimeThreshold_CallInstance = CMock_Guts_MemNext(Mock.runningAverageSetMinTimeThreshold_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageSetMinTimeThreshold' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageSetMinTimeThreshold' called with unexpected value for argument 'ra'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_max, max, cmock_line, "Function 'runningAverageSetMinTimeThreshold' called with unexpected value for argument 'max'.");
  }
}

void CMockExpectParameters_runningAverageSetMinTimeThreshold(CMOCK_runningAverageSetMinTimeThreshold_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra, int max)
{
  cmock_call_instance->Expected_ra = ra;
  cmock_call_instance->Expected_max = max;
}

void runningAverageSetMinTimeThreshold_CMockExpect(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, int max)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageSetMinTimeThreshold_CALL_INSTANCE));
  CMOCK_runningAverageSetMinTimeThreshold_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageSetMinTimeThreshold_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageSetMinTimeThreshold_CallInstance = CMock_Guts_MemChain(Mock.runningAverageSetMinTimeThreshold_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageSetMinTimeThreshold(cmock_call_instance, ra, max);
}

int runningAverageCalcNumSpeeds(RunningAverage* ra)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_runningAverageCalcNumSpeeds_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageCalcNumSpeeds_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.runningAverageCalcNumSpeeds_CallInstance);
  Mock.runningAverageCalcNumSpeeds_CallInstance = CMock_Guts_MemNext(Mock.runningAverageCalcNumSpeeds_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'runningAverageCalcNumSpeeds' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ra), (void*)(ra), sizeof(RunningAverage), cmock_line, "Function 'runningAverageCalcNumSpeeds' called with unexpected value for argument 'ra'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_runningAverageCalcNumSpeeds(CMOCK_runningAverageCalcNumSpeeds_CALL_INSTANCE* cmock_call_instance, RunningAverage* ra)
{
  cmock_call_instance->Expected_ra = ra;
}

void runningAverageCalcNumSpeeds_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RunningAverage* ra, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_runningAverageCalcNumSpeeds_CALL_INSTANCE));
  CMOCK_runningAverageCalcNumSpeeds_CALL_INSTANCE* cmock_call_instance = (CMOCK_runningAverageCalcNumSpeeds_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.runningAverageCalcNumSpeeds_CallInstance = CMock_Guts_MemChain(Mock.runningAverageCalcNumSpeeds_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_runningAverageCalcNumSpeeds(cmock_call_instance, ra);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

