/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockImageDecoderConfig.h"

static struct MockImageDecoderConfigInstance
{
  unsigned char placeHolder;
} Mock;

extern jmp_buf AbortFrame;

void MockImageDecoderConfig_Verify(void)
{
}

void MockImageDecoderConfig_Init(void)
{
  MockImageDecoderConfig_Destroy();
}

void MockImageDecoderConfig_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

