/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockElements.h"

typedef struct _CMOCK_Clear_Header_Window_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_Clear_Header_Window_CALL_INSTANCE;

typedef struct _CMOCK_Clear_Divider_Window_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_Clear_Divider_Window_CALL_INSTANCE;

typedef struct _CMOCK_New_Divider_Window_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_New_Divider_Window_CALL_INSTANCE;

typedef struct _CMOCK_Update_Divider_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  UINT8 Expected_update_type;

} CMOCK_Update_Divider_CALL_INSTANCE;

typedef struct _CMOCK_Clear_Element_Window_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_Clear_Element_Window_CALL_INSTANCE;

typedef struct _CMOCK_New_Element_Window_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_New_Element_Window_CALL_INSTANCE;

typedef struct _CMOCK_Update_Element_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  UINT8 Expected_update_type;

} CMOCK_Update_Element_CALL_INSTANCE;

typedef struct _CMOCK_Create_New_Arc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_Create_New_Arc_CALL_INSTANCE;

typedef struct _CMOCK_Draw_Arc_Tick_Marks_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char Expected_cmock_arg1;

} CMOCK_Draw_Arc_Tick_Marks_CALL_INSTANCE;

typedef struct _CMOCK_Setup_Arc_Units_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_Setup_Arc_Units_CALL_INSTANCE;

typedef struct _CMOCK_Draw_Arc_Units_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  UINT8 Expected_update_type;

} CMOCK_Draw_Arc_Units_CALL_INSTANCE;

typedef struct _CMOCK_Update_Arc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned short int ReturnVal;

} CMOCK_Update_Arc_CALL_INSTANCE;

typedef struct _CMOCK_Update_Range_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_Update_Range_CALL_INSTANCE;

typedef struct _CMOCK_GetRateResult_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  float ReturnVal;

} CMOCK_GetRateResult_CALL_INSTANCE;

static struct MockElementsInstance
{
  CMOCK_MEM_INDEX_TYPE Clear_Header_Window_CallInstance;
  CMOCK_MEM_INDEX_TYPE Clear_Divider_Window_CallInstance;
  CMOCK_MEM_INDEX_TYPE New_Divider_Window_CallInstance;
  CMOCK_MEM_INDEX_TYPE Update_Divider_CallInstance;
  CMOCK_MEM_INDEX_TYPE Clear_Element_Window_CallInstance;
  CMOCK_MEM_INDEX_TYPE New_Element_Window_CallInstance;
  CMOCK_MEM_INDEX_TYPE Update_Element_CallInstance;
  CMOCK_MEM_INDEX_TYPE Create_New_Arc_CallInstance;
  CMOCK_MEM_INDEX_TYPE Draw_Arc_Tick_Marks_CallInstance;
  CMOCK_MEM_INDEX_TYPE Setup_Arc_Units_CallInstance;
  CMOCK_MEM_INDEX_TYPE Draw_Arc_Units_CallInstance;
  CMOCK_MEM_INDEX_TYPE Update_Arc_CallInstance;
  CMOCK_MEM_INDEX_TYPE Update_Range_CallInstance;
  CMOCK_MEM_INDEX_TYPE GetRateResult_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockElements_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Clear_Header_Window_CallInstance, cmock_line, "Function 'Clear_Header_Window' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Clear_Divider_Window_CallInstance, cmock_line, "Function 'Clear_Divider_Window' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.New_Divider_Window_CallInstance, cmock_line, "Function 'New_Divider_Window' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Update_Divider_CallInstance, cmock_line, "Function 'Update_Divider' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Clear_Element_Window_CallInstance, cmock_line, "Function 'Clear_Element_Window' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.New_Element_Window_CallInstance, cmock_line, "Function 'New_Element_Window' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Update_Element_CallInstance, cmock_line, "Function 'Update_Element' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Create_New_Arc_CallInstance, cmock_line, "Function 'Create_New_Arc' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Draw_Arc_Tick_Marks_CallInstance, cmock_line, "Function 'Draw_Arc_Tick_Marks' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Setup_Arc_Units_CallInstance, cmock_line, "Function 'Setup_Arc_Units' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Draw_Arc_Units_CallInstance, cmock_line, "Function 'Draw_Arc_Units' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Update_Arc_CallInstance, cmock_line, "Function 'Update_Arc' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Update_Range_CallInstance, cmock_line, "Function 'Update_Range' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GetRateResult_CallInstance, cmock_line, "Function 'GetRateResult' called less times than expected.");
}

void MockElements_Init(void)
{
  MockElements_Destroy();
}

void MockElements_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void Clear_Header_Window(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Clear_Header_Window_CALL_INSTANCE* cmock_call_instance = (CMOCK_Clear_Header_Window_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Clear_Header_Window_CallInstance);
  Mock.Clear_Header_Window_CallInstance = CMock_Guts_MemNext(Mock.Clear_Header_Window_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Clear_Header_Window' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void Clear_Header_Window_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Clear_Header_Window_CALL_INSTANCE));
  CMOCK_Clear_Header_Window_CALL_INSTANCE* cmock_call_instance = (CMOCK_Clear_Header_Window_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Clear_Header_Window_CallInstance = CMock_Guts_MemChain(Mock.Clear_Header_Window_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void Clear_Divider_Window(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Clear_Divider_Window_CALL_INSTANCE* cmock_call_instance = (CMOCK_Clear_Divider_Window_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Clear_Divider_Window_CallInstance);
  Mock.Clear_Divider_Window_CallInstance = CMock_Guts_MemNext(Mock.Clear_Divider_Window_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Clear_Divider_Window' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void Clear_Divider_Window_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Clear_Divider_Window_CALL_INSTANCE));
  CMOCK_Clear_Divider_Window_CALL_INSTANCE* cmock_call_instance = (CMOCK_Clear_Divider_Window_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Clear_Divider_Window_CallInstance = CMock_Guts_MemChain(Mock.Clear_Divider_Window_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void New_Divider_Window(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_New_Divider_Window_CALL_INSTANCE* cmock_call_instance = (CMOCK_New_Divider_Window_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.New_Divider_Window_CallInstance);
  Mock.New_Divider_Window_CallInstance = CMock_Guts_MemNext(Mock.New_Divider_Window_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'New_Divider_Window' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void New_Divider_Window_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_New_Divider_Window_CALL_INSTANCE));
  CMOCK_New_Divider_Window_CALL_INSTANCE* cmock_call_instance = (CMOCK_New_Divider_Window_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.New_Divider_Window_CallInstance = CMock_Guts_MemChain(Mock.New_Divider_Window_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void Update_Divider(UINT8 update_type)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Update_Divider_CALL_INSTANCE* cmock_call_instance = (CMOCK_Update_Divider_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Update_Divider_CallInstance);
  Mock.Update_Divider_CallInstance = CMock_Guts_MemNext(Mock.Update_Divider_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Update_Divider' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_update_type, update_type, cmock_line, "Function 'Update_Divider' called with unexpected value for argument 'update_type'.");
  }
}

void CMockExpectParameters_Update_Divider(CMOCK_Update_Divider_CALL_INSTANCE* cmock_call_instance, UINT8 update_type)
{
  cmock_call_instance->Expected_update_type = update_type;
}

void Update_Divider_CMockExpect(UNITY_LINE_TYPE cmock_line, UINT8 update_type)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Update_Divider_CALL_INSTANCE));
  CMOCK_Update_Divider_CALL_INSTANCE* cmock_call_instance = (CMOCK_Update_Divider_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Update_Divider_CallInstance = CMock_Guts_MemChain(Mock.Update_Divider_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Update_Divider(cmock_call_instance, update_type);
}

void Clear_Element_Window(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Clear_Element_Window_CALL_INSTANCE* cmock_call_instance = (CMOCK_Clear_Element_Window_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Clear_Element_Window_CallInstance);
  Mock.Clear_Element_Window_CallInstance = CMock_Guts_MemNext(Mock.Clear_Element_Window_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Clear_Element_Window' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void Clear_Element_Window_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Clear_Element_Window_CALL_INSTANCE));
  CMOCK_Clear_Element_Window_CALL_INSTANCE* cmock_call_instance = (CMOCK_Clear_Element_Window_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Clear_Element_Window_CallInstance = CMock_Guts_MemChain(Mock.Clear_Element_Window_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void New_Element_Window(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_New_Element_Window_CALL_INSTANCE* cmock_call_instance = (CMOCK_New_Element_Window_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.New_Element_Window_CallInstance);
  Mock.New_Element_Window_CallInstance = CMock_Guts_MemNext(Mock.New_Element_Window_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'New_Element_Window' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void New_Element_Window_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_New_Element_Window_CALL_INSTANCE));
  CMOCK_New_Element_Window_CALL_INSTANCE* cmock_call_instance = (CMOCK_New_Element_Window_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.New_Element_Window_CallInstance = CMock_Guts_MemChain(Mock.New_Element_Window_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void Update_Element(UINT8 update_type)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Update_Element_CALL_INSTANCE* cmock_call_instance = (CMOCK_Update_Element_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Update_Element_CallInstance);
  Mock.Update_Element_CallInstance = CMock_Guts_MemNext(Mock.Update_Element_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Update_Element' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_update_type, update_type, cmock_line, "Function 'Update_Element' called with unexpected value for argument 'update_type'.");
  }
}

void CMockExpectParameters_Update_Element(CMOCK_Update_Element_CALL_INSTANCE* cmock_call_instance, UINT8 update_type)
{
  cmock_call_instance->Expected_update_type = update_type;
}

void Update_Element_CMockExpect(UNITY_LINE_TYPE cmock_line, UINT8 update_type)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Update_Element_CALL_INSTANCE));
  CMOCK_Update_Element_CALL_INSTANCE* cmock_call_instance = (CMOCK_Update_Element_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Update_Element_CallInstance = CMock_Guts_MemChain(Mock.Update_Element_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Update_Element(cmock_call_instance, update_type);
}

void Create_New_Arc(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Create_New_Arc_CALL_INSTANCE* cmock_call_instance = (CMOCK_Create_New_Arc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Create_New_Arc_CallInstance);
  Mock.Create_New_Arc_CallInstance = CMock_Guts_MemNext(Mock.Create_New_Arc_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Create_New_Arc' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void Create_New_Arc_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Create_New_Arc_CALL_INSTANCE));
  CMOCK_Create_New_Arc_CALL_INSTANCE* cmock_call_instance = (CMOCK_Create_New_Arc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Create_New_Arc_CallInstance = CMock_Guts_MemChain(Mock.Create_New_Arc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void Draw_Arc_Tick_Marks(unsigned char cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Draw_Arc_Tick_Marks_CALL_INSTANCE* cmock_call_instance = (CMOCK_Draw_Arc_Tick_Marks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Draw_Arc_Tick_Marks_CallInstance);
  Mock.Draw_Arc_Tick_Marks_CallInstance = CMock_Guts_MemNext(Mock.Draw_Arc_Tick_Marks_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Draw_Arc_Tick_Marks' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'Draw_Arc_Tick_Marks' called with unexpected value for argument 'cmock_arg1'.");
  }
}

void CMockExpectParameters_Draw_Arc_Tick_Marks(CMOCK_Draw_Arc_Tick_Marks_CALL_INSTANCE* cmock_call_instance, unsigned char cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void Draw_Arc_Tick_Marks_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Draw_Arc_Tick_Marks_CALL_INSTANCE));
  CMOCK_Draw_Arc_Tick_Marks_CALL_INSTANCE* cmock_call_instance = (CMOCK_Draw_Arc_Tick_Marks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Draw_Arc_Tick_Marks_CallInstance = CMock_Guts_MemChain(Mock.Draw_Arc_Tick_Marks_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Draw_Arc_Tick_Marks(cmock_call_instance, cmock_arg1);
}

void Setup_Arc_Units(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Setup_Arc_Units_CALL_INSTANCE* cmock_call_instance = (CMOCK_Setup_Arc_Units_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Setup_Arc_Units_CallInstance);
  Mock.Setup_Arc_Units_CallInstance = CMock_Guts_MemNext(Mock.Setup_Arc_Units_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Setup_Arc_Units' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void Setup_Arc_Units_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Setup_Arc_Units_CALL_INSTANCE));
  CMOCK_Setup_Arc_Units_CALL_INSTANCE* cmock_call_instance = (CMOCK_Setup_Arc_Units_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Setup_Arc_Units_CallInstance = CMock_Guts_MemChain(Mock.Setup_Arc_Units_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void Draw_Arc_Units(UINT8 update_type)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Draw_Arc_Units_CALL_INSTANCE* cmock_call_instance = (CMOCK_Draw_Arc_Units_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Draw_Arc_Units_CallInstance);
  Mock.Draw_Arc_Units_CallInstance = CMock_Guts_MemNext(Mock.Draw_Arc_Units_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Draw_Arc_Units' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_update_type, update_type, cmock_line, "Function 'Draw_Arc_Units' called with unexpected value for argument 'update_type'.");
  }
}

void CMockExpectParameters_Draw_Arc_Units(CMOCK_Draw_Arc_Units_CALL_INSTANCE* cmock_call_instance, UINT8 update_type)
{
  cmock_call_instance->Expected_update_type = update_type;
}

void Draw_Arc_Units_CMockExpect(UNITY_LINE_TYPE cmock_line, UINT8 update_type)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Draw_Arc_Units_CALL_INSTANCE));
  CMOCK_Draw_Arc_Units_CALL_INSTANCE* cmock_call_instance = (CMOCK_Draw_Arc_Units_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Draw_Arc_Units_CallInstance = CMock_Guts_MemChain(Mock.Draw_Arc_Units_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Draw_Arc_Units(cmock_call_instance, update_type);
}

unsigned short int Update_Arc(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Update_Arc_CALL_INSTANCE* cmock_call_instance = (CMOCK_Update_Arc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Update_Arc_CallInstance);
  Mock.Update_Arc_CallInstance = CMock_Guts_MemNext(Mock.Update_Arc_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Update_Arc' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void Update_Arc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned short int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Update_Arc_CALL_INSTANCE));
  CMOCK_Update_Arc_CALL_INSTANCE* cmock_call_instance = (CMOCK_Update_Arc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Update_Arc_CallInstance = CMock_Guts_MemChain(Mock.Update_Arc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(unsigned short int));
}

void Update_Range(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Update_Range_CALL_INSTANCE* cmock_call_instance = (CMOCK_Update_Range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Update_Range_CallInstance);
  Mock.Update_Range_CallInstance = CMock_Guts_MemNext(Mock.Update_Range_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Update_Range' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void Update_Range_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Update_Range_CALL_INSTANCE));
  CMOCK_Update_Range_CALL_INSTANCE* cmock_call_instance = (CMOCK_Update_Range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Update_Range_CallInstance = CMock_Guts_MemChain(Mock.Update_Range_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

float GetRateResult(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GetRateResult_CALL_INSTANCE* cmock_call_instance = (CMOCK_GetRateResult_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GetRateResult_CallInstance);
  Mock.GetRateResult_CallInstance = CMock_Guts_MemNext(Mock.GetRateResult_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GetRateResult' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void GetRateResult_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GetRateResult_CALL_INSTANCE));
  CMOCK_GetRateResult_CALL_INSTANCE* cmock_call_instance = (CMOCK_GetRateResult_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GetRateResult_CallInstance = CMock_Guts_MemChain(Mock.GetRateResult_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

