/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKWINDOW_H
#define _MOCKWINDOW_H

#include "Window.h"

void MockWindow_Init(void);
void MockWindow_Destroy(void);
void MockWindow_Verify(void);




#define WndCreate_ExpectAndReturn(ID, left, top, right, bottom, state, pBitmap, pText, pScheme, cmock_retval) WndCreate_CMockExpectAndReturn(__LINE__, ID, left, top, right, bottom, state, pBitmap, pText, pScheme, cmock_retval)
void WndCreate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, void* pBitmap, XCHAR* pText, GOL_SCHEME* pScheme, WINDOW* cmock_to_return);
#define WndSetText_Expect(pW, pText) WndSetText_CMockExpect(__LINE__, pW, pText)
void WndSetText_CMockExpect(UNITY_LINE_TYPE cmock_line, WINDOW* pW, XCHAR* pText);
#define WndTranslateMsg_ExpectAndReturn(pW, pMsg, cmock_retval) WndTranslateMsg_CMockExpectAndReturn(__LINE__, pW, pMsg, cmock_retval)
void WndTranslateMsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WINDOW* pW, GOL_MSG* pMsg, WORD cmock_to_return);
#define WndDraw_ExpectAndReturn(pW, cmock_retval) WndDraw_CMockExpectAndReturn(__LINE__, pW, cmock_retval)
void WndDraw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WINDOW* pW, WORD cmock_to_return);

#endif
