/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockstruct_queue.h"

static struct Mockstruct_queueInstance
{
  unsigned char placeHolder;
} Mock;

extern jmp_buf AbortFrame;

void Mockstruct_queue_Verify(void)
{
}

void Mockstruct_queue_Init(void)
{
  Mockstruct_queue_Destroy();
}

void Mockstruct_queue_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

