/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKKEYBOARD_MENU_H
#define _MOCKKEYBOARD_MENU_H

#include "Keyboard_Menu.h"

void MockKeyboard_Menu_Init(void);
void MockKeyboard_Menu_Destroy(void);
void MockKeyboard_Menu_Verify(void);




#define CreateMenu_Expect() CreateMenu_CMockExpect(__LINE__)
void CreateMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateMainMenu_Expect() CreateMainMenu_CMockExpect(__LINE__)
void CreateMainMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreatePasswordEntryMenu_Expect() CreatePasswordEntryMenu_CMockExpect(__LINE__)
void CreatePasswordEntryMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateSettingsMenu_Expect() CreateSettingsMenu_CMockExpect(__LINE__)
void CreateSettingsMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateProductMenu_Expect() CreateProductMenu_CMockExpect(__LINE__)
void CreateProductMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateLanguageMenu_Expect() CreateLanguageMenu_CMockExpect(__LINE__)
void CreateLanguageMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateCalendarMenu_Expect() CreateCalendarMenu_CMockExpect(__LINE__)
void CreateCalendarMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateClockMenu_Expect() CreateClockMenu_CMockExpect(__LINE__)
void CreateClockMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreatePasswordMenu_Expect() CreatePasswordMenu_CMockExpect(__LINE__)
void CreatePasswordMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreatePasswordResponseMenu_Expect() CreatePasswordResponseMenu_CMockExpect(__LINE__)
void CreatePasswordResponseMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateSystemMenu_Expect() CreateSystemMenu_CMockExpect(__LINE__)
void CreateSystemMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateFeaturesMenu_Expect() CreateFeaturesMenu_CMockExpect(__LINE__)
void CreateFeaturesMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateSourceCheckMenu_Expect() CreateSourceCheckMenu_CMockExpect(__LINE__)
void CreateSourceCheckMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateBackgroundCheckMenu_Expect() CreateBackgroundCheckMenu_CMockExpect(__LINE__)
void CreateBackgroundCheckMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateIntegrateMenu_Expect() CreateIntegrateMenu_CMockExpect(__LINE__)
void CreateIntegrateMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateIntegrateReportMenu_Expect() CreateIntegrateReportMenu_CMockExpect(__LINE__)
void CreateIntegrateReportMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateIntegrateValueMenu_Expect() CreateIntegrateValueMenu_CMockExpect(__LINE__)
void CreateIntegrateValueMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateDataLoggingMenu_Expect() CreateDataLoggingMenu_CMockExpect(__LINE__)
void CreateDataLoggingMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateDataLoggingReportMenu_Expect() CreateDataLoggingReportMenu_CMockExpect(__LINE__)
void CreateDataLoggingReportMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateDataLoggingReportSystemMenu_Expect() CreateDataLoggingReportSystemMenu_CMockExpect(__LINE__)
void CreateDataLoggingReportSystemMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateDataLoggingReportInstrumentMenu_Expect() CreateDataLoggingReportInstrumentMenu_CMockExpect(__LINE__)
void CreateDataLoggingReportInstrumentMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateDataLoggingReportReadingsMenu_Expect() CreateDataLoggingReportReadingsMenu_CMockExpect(__LINE__)
void CreateDataLoggingReportReadingsMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateControlsMenu_Expect() CreateControlsMenu_CMockExpect(__LINE__)
void CreateControlsMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateBacklightMenu_Expect() CreateBacklightMenu_CMockExpect(__LINE__)
void CreateBacklightMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateAutoBacklightMenu_Expect() CreateAutoBacklightMenu_CMockExpect(__LINE__)
void CreateAutoBacklightMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateAudioMenu_Expect() CreateAudioMenu_CMockExpect(__LINE__)
void CreateAudioMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateGPSMenu_Expect() CreateGPSMenu_CMockExpect(__LINE__)
void CreateGPSMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateBluetoothMenu_Expect() CreateBluetoothMenu_CMockExpect(__LINE__)
void CreateBluetoothMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateDetectorMenu_Expect() CreateDetectorMenu_CMockExpect(__LINE__)
void CreateDetectorMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateDetectorSetupMenu_Expect() CreateDetectorSetupMenu_CMockExpect(__LINE__)
void CreateDetectorSetupMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateDisplayMenu_Expect(calling_menu) CreateDisplayMenu_CMockExpect(__LINE__, calling_menu)
void CreateDisplayMenu_CMockExpect(UNITY_LINE_TYPE cmock_line, SHORT calling_menu);
#define CreateDisplaySetupMenu_Expect() CreateDisplaySetupMenu_CMockExpect(__LINE__)
void CreateDisplaySetupMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateViewMenu_Expect() CreateViewMenu_CMockExpect(__LINE__)
void CreateViewMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateViewAppearanceMenu_Expect() CreateViewAppearanceMenu_CMockExpect(__LINE__)
void CreateViewAppearanceMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateViewFunctionsMenu_Expect() CreateViewFunctionsMenu_CMockExpect(__LINE__)
void CreateViewFunctionsMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateViewFunctionMenu_Expect() CreateViewFunctionMenu_CMockExpect(__LINE__)
void CreateViewFunctionMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateViewAlertsMenu_Expect() CreateViewAlertsMenu_CMockExpect(__LINE__)
void CreateViewAlertsMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateViewAlertsReadingMenu_Expect() CreateViewAlertsReadingMenu_CMockExpect(__LINE__)
void CreateViewAlertsReadingMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateViewAlarmsMenu_Expect() CreateViewAlarmsMenu_CMockExpect(__LINE__)
void CreateViewAlarmsMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateViewAlarmsReadingMenu_Expect() CreateViewAlarmsReadingMenu_CMockExpect(__LINE__)
void CreateViewAlarmsReadingMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateAlertsAlarmsMenu_Expect() CreateAlertsAlarmsMenu_CMockExpect(__LINE__)
void CreateAlertsAlarmsMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateAlertsMenu_Expect() CreateAlertsMenu_CMockExpect(__LINE__)
void CreateAlertsMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateAlarmsMenu_Expect() CreateAlarmsMenu_CMockExpect(__LINE__)
void CreateAlarmsMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateFunctionsMenu_Expect() CreateFunctionsMenu_CMockExpect(__LINE__)
void CreateFunctionsMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateBlankMenu_Expect() CreateBlankMenu_CMockExpect(__LINE__)
void CreateBlankMenu_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define FormatString_Expect(generic_string, message, message_length) FormatString_CMockExpect(__LINE__, generic_string, message, message_length)
void FormatString_CMockExpect(UNITY_LINE_TYPE cmock_line, char* generic_string, char* message, UINT8 message_length);
#define FormatLine_Expect(current_line, generic_string, sub_menu, line_item, line_item_type) FormatLine_CMockExpect(__LINE__, current_line, generic_string, sub_menu, line_item, line_item_type)
void FormatLine_CMockExpect(UNITY_LINE_TYPE cmock_line, UINT8 current_line, char* generic_string, UINT8 sub_menu, void* line_item, UINT8 line_item_type);
#define CreateLine_Expect() CreateLine_CMockExpect(__LINE__)
void CreateLine_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateEditLine_Expect() CreateEditLine_CMockExpect(__LINE__)
void CreateEditLine_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateEditStringLine_Expect() CreateEditStringLine_CMockExpect(__LINE__)
void CreateEditStringLine_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define ChangeMenuLine_Expect() ChangeMenuLine_CMockExpect(__LINE__)
void ChangeMenuLine_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define ChangeEditLine_Expect() ChangeEditLine_CMockExpect(__LINE__)
void ChangeEditLine_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define ChangeEditStringLine_Expect() ChangeEditStringLine_CMockExpect(__LINE__)
void ChangeEditStringLine_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CreateMonthList_Expect(generic_value, generic_string) CreateMonthList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateMonthList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateShortMonthList_Expect(generic_value, generic_string) CreateShortMonthList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateShortMonthList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateLanguageList_Expect(generic_value, generic_string) CreateLanguageList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateLanguageList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreatePowerUpModeList_Expect(generic_value, generic_string) CreatePowerUpModeList_CMockExpect(__LINE__, generic_value, generic_string)
void CreatePowerUpModeList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateDetectorPowerUpModeList_Expect(generic_value, generic_string) CreateDetectorPowerUpModeList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateDetectorPowerUpModeList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateOperatingModeList_Expect(generic_value, generic_string) CreateOperatingModeList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateOperatingModeList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateAudioOperatingModeList_Expect(generic_value, generic_string) CreateAudioOperatingModeList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateAudioOperatingModeList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateColorList_Expect(generic_value, generic_string) CreateColorList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateColorList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateCurrentViewList_Expect(generic_value, generic_string) CreateCurrentViewList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateCurrentViewList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateMultiplierList_Expect(generic_value, generic_string) CreateMultiplierList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateMultiplierList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateUnitsList_Expect(generic_value, generic_string) CreateUnitsList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateUnitsList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateModelList_Expect(generic_value, generic_string) CreateModelList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateModelList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateViewFunctionList_Expect(generic_value, generic_string) CreateViewFunctionList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateViewFunctionList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateDetectorList_Expect(generic_value, generic_string) CreateDetectorList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateDetectorList_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned short generic_value, char* generic_string);
#define CreateInstrumentFunctionsList_Expect(generic_value, generic_string) CreateInstrumentFunctionsList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateInstrumentFunctionsList_CMockExpect(UNITY_LINE_TYPE cmock_line, UINT8 generic_value, char* generic_string);
#define CreatePercentageList_Expect(generic_value, generic_string) CreatePercentageList_CMockExpect(__LINE__, generic_value, generic_string)
void CreatePercentageList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateCurrentDetectorList_Expect(generic_value, generic_string) CreateCurrentDetectorList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateCurrentDetectorList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);
#define CreateRangeList_Expect(generic_value, generic_string) CreateRangeList_CMockExpect(__LINE__, generic_value, generic_string)
void CreateRangeList_CMockExpect(UNITY_LINE_TYPE cmock_line, char generic_value, char* generic_string);

#endif
