/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockusb_host.h"

typedef struct _CMOCK_USB_HOST_APP_EVENT_HANDLER_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_address;
  USB_EVENT Expected_event;
  void* Expected_data;
  DWORD Expected_size;

} CMOCK_USB_HOST_APP_EVENT_HANDLER_CALL_INSTANCE;

typedef struct _CMOCK_USBHostClearEndpointErrors_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE Expected_endpoint;

} CMOCK_USBHostClearEndpointErrors_CALL_INSTANCE;

typedef struct _CMOCK_USBHostDeviceSpecificClientDriver_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_deviceAddress;

} CMOCK_USBHostDeviceSpecificClientDriver_CALL_INSTANCE;

typedef struct _CMOCK_USBHostDeviceStatus_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;

} CMOCK_USBHostDeviceStatus_CALL_INSTANCE;

typedef struct _CMOCK_USBHostInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  unsigned long Expected_flags;

} CMOCK_USBHostInit_CALL_INSTANCE;

typedef struct _CMOCK_USBHostIsochronousBuffersCreate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  ISOCHRONOUS_DATA* Expected_isocData;
  BYTE Expected_numberOfBuffers;
  WORD Expected_bufferSize;

} CMOCK_USBHostIsochronousBuffersCreate_CALL_INSTANCE;

typedef struct _CMOCK_USBHostIsochronousBuffersDestroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ISOCHRONOUS_DATA* Expected_isocData;
  BYTE Expected_numberOfBuffers;

} CMOCK_USBHostIsochronousBuffersDestroy_CALL_INSTANCE;

typedef struct _CMOCK_USBHostIsochronousBuffersReset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ISOCHRONOUS_DATA* Expected_isocData;
  BYTE Expected_numberOfBuffers;

} CMOCK_USBHostIsochronousBuffersReset_CALL_INSTANCE;

typedef struct _CMOCK_USBHostIssueDeviceRequest_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE Expected_bmRequestType;
  BYTE Expected_bRequest;
  WORD Expected_wValue;
  WORD Expected_wIndex;
  WORD Expected_wLength;
  BYTE* Expected_data;
  BYTE Expected_dataDirection;
  BYTE Expected_clientDriverID;

} CMOCK_USBHostIssueDeviceRequest_CALL_INSTANCE;

typedef struct _CMOCK_USBHostRead_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE Expected_endpoint;
  BYTE* Expected_data;
  DWORD Expected_size;

} CMOCK_USBHostRead_CALL_INSTANCE;

typedef struct _CMOCK_USBHostResetDevice_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;

} CMOCK_USBHostResetDevice_CALL_INSTANCE;

typedef struct _CMOCK_USBHostResumeDevice_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;

} CMOCK_USBHostResumeDevice_CALL_INSTANCE;

typedef struct _CMOCK_USBHostSetDeviceConfiguration_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE Expected_configuration;

} CMOCK_USBHostSetDeviceConfiguration_CALL_INSTANCE;

typedef struct _CMOCK_USBHostSetNAKTimeout_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE Expected_endpoint;
  WORD Expected_flags;
  WORD Expected_timeoutCount;

} CMOCK_USBHostSetNAKTimeout_CALL_INSTANCE;

typedef struct _CMOCK_USBHostShutdown_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USBHostShutdown_CALL_INSTANCE;

typedef struct _CMOCK_USBHostSuspendDevice_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;

} CMOCK_USBHostSuspendDevice_CALL_INSTANCE;

typedef struct _CMOCK_USBHostTasks_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USBHostTasks_CALL_INSTANCE;

typedef struct _CMOCK_USBHostTerminateTransfer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE Expected_deviceAddress;
  BYTE Expected_endpoint;

} CMOCK_USBHostTerminateTransfer_CALL_INSTANCE;

typedef struct _CMOCK_USBHostTransferIsComplete_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE Expected_endpoint;
  BYTE* Expected_errorCode;
  DWORD* Expected_byteCount;

} CMOCK_USBHostTransferIsComplete_CALL_INSTANCE;

typedef struct _CMOCK_USBHostVbusEvent_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  USB_EVENT Expected_vbusEvent;
  BYTE Expected_hubAddress;
  BYTE Expected_portNumber;

} CMOCK_USBHostVbusEvent_CALL_INSTANCE;

typedef struct _CMOCK_USBHostWrite_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE Expected_endpoint;
  BYTE* Expected_data;
  DWORD Expected_size;

} CMOCK_USBHostWrite_CALL_INSTANCE;

static struct Mockusb_hostInstance
{
  CMOCK_MEM_INDEX_TYPE USB_HOST_APP_EVENT_HANDLER_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostClearEndpointErrors_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostDeviceSpecificClientDriver_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostDeviceStatus_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostIsochronousBuffersCreate_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostIsochronousBuffersDestroy_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostIsochronousBuffersReset_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostIssueDeviceRequest_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostRead_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostResetDevice_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostResumeDevice_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostSetDeviceConfiguration_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostSetNAKTimeout_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostShutdown_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostSuspendDevice_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostTasks_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostTerminateTransfer_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostTransferIsComplete_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostVbusEvent_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostWrite_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockusb_host_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USB_HOST_APP_EVENT_HANDLER_CallInstance, cmock_line, "Function 'USB_HOST_APP_EVENT_HANDLER' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostClearEndpointErrors_CallInstance, cmock_line, "Function 'USBHostClearEndpointErrors' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostDeviceSpecificClientDriver_CallInstance, cmock_line, "Function 'USBHostDeviceSpecificClientDriver' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostDeviceStatus_CallInstance, cmock_line, "Function 'USBHostDeviceStatus' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostInit_CallInstance, cmock_line, "Function 'USBHostInit' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostIsochronousBuffersCreate_CallInstance, cmock_line, "Function 'USBHostIsochronousBuffersCreate' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostIsochronousBuffersDestroy_CallInstance, cmock_line, "Function 'USBHostIsochronousBuffersDestroy' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostIsochronousBuffersReset_CallInstance, cmock_line, "Function 'USBHostIsochronousBuffersReset' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostIssueDeviceRequest_CallInstance, cmock_line, "Function 'USBHostIssueDeviceRequest' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostRead_CallInstance, cmock_line, "Function 'USBHostRead' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostResetDevice_CallInstance, cmock_line, "Function 'USBHostResetDevice' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostResumeDevice_CallInstance, cmock_line, "Function 'USBHostResumeDevice' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostSetDeviceConfiguration_CallInstance, cmock_line, "Function 'USBHostSetDeviceConfiguration' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostSetNAKTimeout_CallInstance, cmock_line, "Function 'USBHostSetNAKTimeout' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostShutdown_CallInstance, cmock_line, "Function 'USBHostShutdown' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostSuspendDevice_CallInstance, cmock_line, "Function 'USBHostSuspendDevice' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostTasks_CallInstance, cmock_line, "Function 'USBHostTasks' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostTerminateTransfer_CallInstance, cmock_line, "Function 'USBHostTerminateTransfer' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostTransferIsComplete_CallInstance, cmock_line, "Function 'USBHostTransferIsComplete' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostVbusEvent_CallInstance, cmock_line, "Function 'USBHostVbusEvent' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostWrite_CallInstance, cmock_line, "Function 'USBHostWrite' called less times than expected.");
}

void Mockusb_host_Init(void)
{
  Mockusb_host_Destroy();
}

void Mockusb_host_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

BOOL USB_HOST_APP_EVENT_HANDLER(BYTE address, USB_EVENT event, void* data, DWORD size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USB_HOST_APP_EVENT_HANDLER_CALL_INSTANCE* cmock_call_instance = (CMOCK_USB_HOST_APP_EVENT_HANDLER_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USB_HOST_APP_EVENT_HANDLER_CallInstance);
  Mock.USB_HOST_APP_EVENT_HANDLER_CallInstance = CMock_Guts_MemNext(Mock.USB_HOST_APP_EVENT_HANDLER_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USB_HOST_APP_EVENT_HANDLER' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_address), (void*)(&address), sizeof(BYTE), cmock_line, "Function 'USB_HOST_APP_EVENT_HANDLER' called with unexpected value for argument 'address'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_event), (void*)(&event), sizeof(USB_EVENT), cmock_line, "Function 'USB_HOST_APP_EVENT_HANDLER' called with unexpected value for argument 'event'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_data, data, cmock_line, "Function 'USB_HOST_APP_EVENT_HANDLER' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(DWORD), cmock_line, "Function 'USB_HOST_APP_EVENT_HANDLER' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USB_HOST_APP_EVENT_HANDLER(CMOCK_USB_HOST_APP_EVENT_HANDLER_CALL_INSTANCE* cmock_call_instance, BYTE address, USB_EVENT event, void* data, DWORD size)
{
  memcpy(&cmock_call_instance->Expected_address, &address, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_event, &event, sizeof(USB_EVENT));
  cmock_call_instance->Expected_data = data;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(DWORD));
}

void USB_HOST_APP_EVENT_HANDLER_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE address, USB_EVENT event, void* data, DWORD size, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USB_HOST_APP_EVENT_HANDLER_CALL_INSTANCE));
  CMOCK_USB_HOST_APP_EVENT_HANDLER_CALL_INSTANCE* cmock_call_instance = (CMOCK_USB_HOST_APP_EVENT_HANDLER_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USB_HOST_APP_EVENT_HANDLER_CallInstance = CMock_Guts_MemChain(Mock.USB_HOST_APP_EVENT_HANDLER_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USB_HOST_APP_EVENT_HANDLER(cmock_call_instance, address, event, data, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BYTE USBHostClearEndpointErrors(BYTE deviceAddress, BYTE endpoint)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostClearEndpointErrors_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostClearEndpointErrors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostClearEndpointErrors_CallInstance);
  Mock.USBHostClearEndpointErrors_CallInstance = CMock_Guts_MemNext(Mock.USBHostClearEndpointErrors_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostClearEndpointErrors' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostClearEndpointErrors' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_endpoint), (void*)(&endpoint), sizeof(BYTE), cmock_line, "Function 'USBHostClearEndpointErrors' called with unexpected value for argument 'endpoint'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostClearEndpointErrors(CMOCK_USBHostClearEndpointErrors_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE endpoint)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_endpoint, &endpoint, sizeof(BYTE));
}

void USBHostClearEndpointErrors_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE endpoint, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostClearEndpointErrors_CALL_INSTANCE));
  CMOCK_USBHostClearEndpointErrors_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostClearEndpointErrors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostClearEndpointErrors_CallInstance = CMock_Guts_MemChain(Mock.USBHostClearEndpointErrors_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostClearEndpointErrors(cmock_call_instance, deviceAddress, endpoint);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BOOL USBHostDeviceSpecificClientDriver(BYTE deviceAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostDeviceSpecificClientDriver_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostDeviceSpecificClientDriver_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostDeviceSpecificClientDriver_CallInstance);
  Mock.USBHostDeviceSpecificClientDriver_CallInstance = CMock_Guts_MemNext(Mock.USBHostDeviceSpecificClientDriver_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostDeviceSpecificClientDriver' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostDeviceSpecificClientDriver' called with unexpected value for argument 'deviceAddress'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostDeviceSpecificClientDriver(CMOCK_USBHostDeviceSpecificClientDriver_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
}

void USBHostDeviceSpecificClientDriver_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostDeviceSpecificClientDriver_CALL_INSTANCE));
  CMOCK_USBHostDeviceSpecificClientDriver_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostDeviceSpecificClientDriver_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostDeviceSpecificClientDriver_CallInstance = CMock_Guts_MemChain(Mock.USBHostDeviceSpecificClientDriver_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostDeviceSpecificClientDriver(cmock_call_instance, deviceAddress);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BYTE USBHostDeviceStatus(BYTE deviceAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostDeviceStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostDeviceStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostDeviceStatus_CallInstance);
  Mock.USBHostDeviceStatus_CallInstance = CMock_Guts_MemNext(Mock.USBHostDeviceStatus_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostDeviceStatus' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostDeviceStatus' called with unexpected value for argument 'deviceAddress'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostDeviceStatus(CMOCK_USBHostDeviceStatus_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
}

void USBHostDeviceStatus_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostDeviceStatus_CALL_INSTANCE));
  CMOCK_USBHostDeviceStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostDeviceStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostDeviceStatus_CallInstance = CMock_Guts_MemChain(Mock.USBHostDeviceStatus_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostDeviceStatus(cmock_call_instance, deviceAddress);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BOOL USBHostInit(unsigned long flags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostInit_CallInstance);
  Mock.USBHostInit_CallInstance = CMock_Guts_MemNext(Mock.USBHostInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostInit' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_flags, flags, cmock_line, "Function 'USBHostInit' called with unexpected value for argument 'flags'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostInit(CMOCK_USBHostInit_CALL_INSTANCE* cmock_call_instance, unsigned long flags)
{
  cmock_call_instance->Expected_flags = flags;
}

void USBHostInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned long flags, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostInit_CALL_INSTANCE));
  CMOCK_USBHostInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostInit_CallInstance = CMock_Guts_MemChain(Mock.USBHostInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostInit(cmock_call_instance, flags);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BOOL USBHostIsochronousBuffersCreate(ISOCHRONOUS_DATA* isocData, BYTE numberOfBuffers, WORD bufferSize)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostIsochronousBuffersCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostIsochronousBuffersCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostIsochronousBuffersCreate_CallInstance);
  Mock.USBHostIsochronousBuffersCreate_CallInstance = CMock_Guts_MemNext(Mock.USBHostIsochronousBuffersCreate_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostIsochronousBuffersCreate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_isocData), (void*)(isocData), sizeof(ISOCHRONOUS_DATA), cmock_line, "Function 'USBHostIsochronousBuffersCreate' called with unexpected value for argument 'isocData'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_numberOfBuffers), (void*)(&numberOfBuffers), sizeof(BYTE), cmock_line, "Function 'USBHostIsochronousBuffersCreate' called with unexpected value for argument 'numberOfBuffers'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bufferSize), (void*)(&bufferSize), sizeof(WORD), cmock_line, "Function 'USBHostIsochronousBuffersCreate' called with unexpected value for argument 'bufferSize'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostIsochronousBuffersCreate(CMOCK_USBHostIsochronousBuffersCreate_CALL_INSTANCE* cmock_call_instance, ISOCHRONOUS_DATA* isocData, BYTE numberOfBuffers, WORD bufferSize)
{
  cmock_call_instance->Expected_isocData = isocData;
  memcpy(&cmock_call_instance->Expected_numberOfBuffers, &numberOfBuffers, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_bufferSize, &bufferSize, sizeof(WORD));
}

void USBHostIsochronousBuffersCreate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ISOCHRONOUS_DATA* isocData, BYTE numberOfBuffers, WORD bufferSize, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostIsochronousBuffersCreate_CALL_INSTANCE));
  CMOCK_USBHostIsochronousBuffersCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostIsochronousBuffersCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostIsochronousBuffersCreate_CallInstance = CMock_Guts_MemChain(Mock.USBHostIsochronousBuffersCreate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostIsochronousBuffersCreate(cmock_call_instance, isocData, numberOfBuffers, bufferSize);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void USBHostIsochronousBuffersDestroy(ISOCHRONOUS_DATA* isocData, BYTE numberOfBuffers)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostIsochronousBuffersDestroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostIsochronousBuffersDestroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostIsochronousBuffersDestroy_CallInstance);
  Mock.USBHostIsochronousBuffersDestroy_CallInstance = CMock_Guts_MemNext(Mock.USBHostIsochronousBuffersDestroy_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostIsochronousBuffersDestroy' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_isocData), (void*)(isocData), sizeof(ISOCHRONOUS_DATA), cmock_line, "Function 'USBHostIsochronousBuffersDestroy' called with unexpected value for argument 'isocData'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_numberOfBuffers), (void*)(&numberOfBuffers), sizeof(BYTE), cmock_line, "Function 'USBHostIsochronousBuffersDestroy' called with unexpected value for argument 'numberOfBuffers'.");
  }
}

void CMockExpectParameters_USBHostIsochronousBuffersDestroy(CMOCK_USBHostIsochronousBuffersDestroy_CALL_INSTANCE* cmock_call_instance, ISOCHRONOUS_DATA* isocData, BYTE numberOfBuffers)
{
  cmock_call_instance->Expected_isocData = isocData;
  memcpy(&cmock_call_instance->Expected_numberOfBuffers, &numberOfBuffers, sizeof(BYTE));
}

void USBHostIsochronousBuffersDestroy_CMockExpect(UNITY_LINE_TYPE cmock_line, ISOCHRONOUS_DATA* isocData, BYTE numberOfBuffers)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostIsochronousBuffersDestroy_CALL_INSTANCE));
  CMOCK_USBHostIsochronousBuffersDestroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostIsochronousBuffersDestroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostIsochronousBuffersDestroy_CallInstance = CMock_Guts_MemChain(Mock.USBHostIsochronousBuffersDestroy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostIsochronousBuffersDestroy(cmock_call_instance, isocData, numberOfBuffers);
}

void USBHostIsochronousBuffersReset(ISOCHRONOUS_DATA* isocData, BYTE numberOfBuffers)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostIsochronousBuffersReset_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostIsochronousBuffersReset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostIsochronousBuffersReset_CallInstance);
  Mock.USBHostIsochronousBuffersReset_CallInstance = CMock_Guts_MemNext(Mock.USBHostIsochronousBuffersReset_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostIsochronousBuffersReset' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_isocData), (void*)(isocData), sizeof(ISOCHRONOUS_DATA), cmock_line, "Function 'USBHostIsochronousBuffersReset' called with unexpected value for argument 'isocData'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_numberOfBuffers), (void*)(&numberOfBuffers), sizeof(BYTE), cmock_line, "Function 'USBHostIsochronousBuffersReset' called with unexpected value for argument 'numberOfBuffers'.");
  }
}

void CMockExpectParameters_USBHostIsochronousBuffersReset(CMOCK_USBHostIsochronousBuffersReset_CALL_INSTANCE* cmock_call_instance, ISOCHRONOUS_DATA* isocData, BYTE numberOfBuffers)
{
  cmock_call_instance->Expected_isocData = isocData;
  memcpy(&cmock_call_instance->Expected_numberOfBuffers, &numberOfBuffers, sizeof(BYTE));
}

void USBHostIsochronousBuffersReset_CMockExpect(UNITY_LINE_TYPE cmock_line, ISOCHRONOUS_DATA* isocData, BYTE numberOfBuffers)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostIsochronousBuffersReset_CALL_INSTANCE));
  CMOCK_USBHostIsochronousBuffersReset_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostIsochronousBuffersReset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostIsochronousBuffersReset_CallInstance = CMock_Guts_MemChain(Mock.USBHostIsochronousBuffersReset_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostIsochronousBuffersReset(cmock_call_instance, isocData, numberOfBuffers);
}

BYTE USBHostIssueDeviceRequest(BYTE deviceAddress, BYTE bmRequestType, BYTE bRequest, WORD wValue, WORD wIndex, WORD wLength, BYTE* data, BYTE dataDirection, BYTE clientDriverID)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostIssueDeviceRequest_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostIssueDeviceRequest_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostIssueDeviceRequest_CallInstance);
  Mock.USBHostIssueDeviceRequest_CallInstance = CMock_Guts_MemNext(Mock.USBHostIssueDeviceRequest_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostIssueDeviceRequest' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostIssueDeviceRequest' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bmRequestType), (void*)(&bmRequestType), sizeof(BYTE), cmock_line, "Function 'USBHostIssueDeviceRequest' called with unexpected value for argument 'bmRequestType'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bRequest), (void*)(&bRequest), sizeof(BYTE), cmock_line, "Function 'USBHostIssueDeviceRequest' called with unexpected value for argument 'bRequest'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_wValue), (void*)(&wValue), sizeof(WORD), cmock_line, "Function 'USBHostIssueDeviceRequest' called with unexpected value for argument 'wValue'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_wIndex), (void*)(&wIndex), sizeof(WORD), cmock_line, "Function 'USBHostIssueDeviceRequest' called with unexpected value for argument 'wIndex'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_wLength), (void*)(&wLength), sizeof(WORD), cmock_line, "Function 'USBHostIssueDeviceRequest' called with unexpected value for argument 'wLength'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(BYTE), cmock_line, "Function 'USBHostIssueDeviceRequest' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dataDirection), (void*)(&dataDirection), sizeof(BYTE), cmock_line, "Function 'USBHostIssueDeviceRequest' called with unexpected value for argument 'dataDirection'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_clientDriverID), (void*)(&clientDriverID), sizeof(BYTE), cmock_line, "Function 'USBHostIssueDeviceRequest' called with unexpected value for argument 'clientDriverID'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostIssueDeviceRequest(CMOCK_USBHostIssueDeviceRequest_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE bmRequestType, BYTE bRequest, WORD wValue, WORD wIndex, WORD wLength, BYTE* data, BYTE dataDirection, BYTE clientDriverID)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_bmRequestType, &bmRequestType, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_bRequest, &bRequest, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_wValue, &wValue, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_wIndex, &wIndex, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_wLength, &wLength, sizeof(WORD));
  cmock_call_instance->Expected_data = data;
  memcpy(&cmock_call_instance->Expected_dataDirection, &dataDirection, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_clientDriverID, &clientDriverID, sizeof(BYTE));
}

void USBHostIssueDeviceRequest_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE bmRequestType, BYTE bRequest, WORD wValue, WORD wIndex, WORD wLength, BYTE* data, BYTE dataDirection, BYTE clientDriverID, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostIssueDeviceRequest_CALL_INSTANCE));
  CMOCK_USBHostIssueDeviceRequest_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostIssueDeviceRequest_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostIssueDeviceRequest_CallInstance = CMock_Guts_MemChain(Mock.USBHostIssueDeviceRequest_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostIssueDeviceRequest(cmock_call_instance, deviceAddress, bmRequestType, bRequest, wValue, wIndex, wLength, data, dataDirection, clientDriverID);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BYTE USBHostRead(BYTE deviceAddress, BYTE endpoint, BYTE* data, DWORD size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostRead_CallInstance);
  Mock.USBHostRead_CallInstance = CMock_Guts_MemNext(Mock.USBHostRead_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostRead' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostRead' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_endpoint), (void*)(&endpoint), sizeof(BYTE), cmock_line, "Function 'USBHostRead' called with unexpected value for argument 'endpoint'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(BYTE), cmock_line, "Function 'USBHostRead' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(DWORD), cmock_line, "Function 'USBHostRead' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostRead(CMOCK_USBHostRead_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE endpoint, BYTE* data, DWORD size)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_endpoint, &endpoint, sizeof(BYTE));
  cmock_call_instance->Expected_data = data;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(DWORD));
}

void USBHostRead_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE endpoint, BYTE* data, DWORD size, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostRead_CALL_INSTANCE));
  CMOCK_USBHostRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostRead_CallInstance = CMock_Guts_MemChain(Mock.USBHostRead_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostRead(cmock_call_instance, deviceAddress, endpoint, data, size);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BYTE USBHostResetDevice(BYTE deviceAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostResetDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostResetDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostResetDevice_CallInstance);
  Mock.USBHostResetDevice_CallInstance = CMock_Guts_MemNext(Mock.USBHostResetDevice_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostResetDevice' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostResetDevice' called with unexpected value for argument 'deviceAddress'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostResetDevice(CMOCK_USBHostResetDevice_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
}

void USBHostResetDevice_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostResetDevice_CALL_INSTANCE));
  CMOCK_USBHostResetDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostResetDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostResetDevice_CallInstance = CMock_Guts_MemChain(Mock.USBHostResetDevice_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostResetDevice(cmock_call_instance, deviceAddress);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BYTE USBHostResumeDevice(BYTE deviceAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostResumeDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostResumeDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostResumeDevice_CallInstance);
  Mock.USBHostResumeDevice_CallInstance = CMock_Guts_MemNext(Mock.USBHostResumeDevice_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostResumeDevice' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostResumeDevice' called with unexpected value for argument 'deviceAddress'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostResumeDevice(CMOCK_USBHostResumeDevice_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
}

void USBHostResumeDevice_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostResumeDevice_CALL_INSTANCE));
  CMOCK_USBHostResumeDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostResumeDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostResumeDevice_CallInstance = CMock_Guts_MemChain(Mock.USBHostResumeDevice_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostResumeDevice(cmock_call_instance, deviceAddress);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BYTE USBHostSetDeviceConfiguration(BYTE deviceAddress, BYTE configuration)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostSetDeviceConfiguration_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostSetDeviceConfiguration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostSetDeviceConfiguration_CallInstance);
  Mock.USBHostSetDeviceConfiguration_CallInstance = CMock_Guts_MemNext(Mock.USBHostSetDeviceConfiguration_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostSetDeviceConfiguration' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostSetDeviceConfiguration' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_configuration), (void*)(&configuration), sizeof(BYTE), cmock_line, "Function 'USBHostSetDeviceConfiguration' called with unexpected value for argument 'configuration'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostSetDeviceConfiguration(CMOCK_USBHostSetDeviceConfiguration_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE configuration)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_configuration, &configuration, sizeof(BYTE));
}

void USBHostSetDeviceConfiguration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE configuration, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostSetDeviceConfiguration_CALL_INSTANCE));
  CMOCK_USBHostSetDeviceConfiguration_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostSetDeviceConfiguration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostSetDeviceConfiguration_CallInstance = CMock_Guts_MemChain(Mock.USBHostSetDeviceConfiguration_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostSetDeviceConfiguration(cmock_call_instance, deviceAddress, configuration);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BYTE USBHostSetNAKTimeout(BYTE deviceAddress, BYTE endpoint, WORD flags, WORD timeoutCount)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostSetNAKTimeout_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostSetNAKTimeout_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostSetNAKTimeout_CallInstance);
  Mock.USBHostSetNAKTimeout_CallInstance = CMock_Guts_MemNext(Mock.USBHostSetNAKTimeout_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostSetNAKTimeout' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostSetNAKTimeout' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_endpoint), (void*)(&endpoint), sizeof(BYTE), cmock_line, "Function 'USBHostSetNAKTimeout' called with unexpected value for argument 'endpoint'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_flags), (void*)(&flags), sizeof(WORD), cmock_line, "Function 'USBHostSetNAKTimeout' called with unexpected value for argument 'flags'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_timeoutCount), (void*)(&timeoutCount), sizeof(WORD), cmock_line, "Function 'USBHostSetNAKTimeout' called with unexpected value for argument 'timeoutCount'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostSetNAKTimeout(CMOCK_USBHostSetNAKTimeout_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE endpoint, WORD flags, WORD timeoutCount)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_endpoint, &endpoint, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_flags, &flags, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_timeoutCount, &timeoutCount, sizeof(WORD));
}

void USBHostSetNAKTimeout_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE endpoint, WORD flags, WORD timeoutCount, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostSetNAKTimeout_CALL_INSTANCE));
  CMOCK_USBHostSetNAKTimeout_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostSetNAKTimeout_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostSetNAKTimeout_CallInstance = CMock_Guts_MemChain(Mock.USBHostSetNAKTimeout_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostSetNAKTimeout(cmock_call_instance, deviceAddress, endpoint, flags, timeoutCount);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

void USBHostShutdown(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostShutdown_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostShutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostShutdown_CallInstance);
  Mock.USBHostShutdown_CallInstance = CMock_Guts_MemNext(Mock.USBHostShutdown_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostShutdown' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void USBHostShutdown_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostShutdown_CALL_INSTANCE));
  CMOCK_USBHostShutdown_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostShutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostShutdown_CallInstance = CMock_Guts_MemChain(Mock.USBHostShutdown_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

BYTE USBHostSuspendDevice(BYTE deviceAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostSuspendDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostSuspendDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostSuspendDevice_CallInstance);
  Mock.USBHostSuspendDevice_CallInstance = CMock_Guts_MemNext(Mock.USBHostSuspendDevice_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostSuspendDevice' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostSuspendDevice' called with unexpected value for argument 'deviceAddress'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostSuspendDevice(CMOCK_USBHostSuspendDevice_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
}

void USBHostSuspendDevice_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostSuspendDevice_CALL_INSTANCE));
  CMOCK_USBHostSuspendDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostSuspendDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostSuspendDevice_CallInstance = CMock_Guts_MemChain(Mock.USBHostSuspendDevice_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostSuspendDevice(cmock_call_instance, deviceAddress);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

void USBHostTasks(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostTasks_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostTasks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostTasks_CallInstance);
  Mock.USBHostTasks_CallInstance = CMock_Guts_MemNext(Mock.USBHostTasks_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostTasks' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void USBHostTasks_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostTasks_CALL_INSTANCE));
  CMOCK_USBHostTasks_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostTasks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostTasks_CallInstance = CMock_Guts_MemChain(Mock.USBHostTasks_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void USBHostTerminateTransfer(BYTE deviceAddress, BYTE endpoint)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostTerminateTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostTerminateTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostTerminateTransfer_CallInstance);
  Mock.USBHostTerminateTransfer_CallInstance = CMock_Guts_MemNext(Mock.USBHostTerminateTransfer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostTerminateTransfer' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostTerminateTransfer' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_endpoint), (void*)(&endpoint), sizeof(BYTE), cmock_line, "Function 'USBHostTerminateTransfer' called with unexpected value for argument 'endpoint'.");
  }
}

void CMockExpectParameters_USBHostTerminateTransfer(CMOCK_USBHostTerminateTransfer_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE endpoint)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_endpoint, &endpoint, sizeof(BYTE));
}

void USBHostTerminateTransfer_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE endpoint)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostTerminateTransfer_CALL_INSTANCE));
  CMOCK_USBHostTerminateTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostTerminateTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostTerminateTransfer_CallInstance = CMock_Guts_MemChain(Mock.USBHostTerminateTransfer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostTerminateTransfer(cmock_call_instance, deviceAddress, endpoint);
}

BOOL USBHostTransferIsComplete(BYTE deviceAddress, BYTE endpoint, BYTE* errorCode, DWORD* byteCount)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostTransferIsComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostTransferIsComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostTransferIsComplete_CallInstance);
  Mock.USBHostTransferIsComplete_CallInstance = CMock_Guts_MemNext(Mock.USBHostTransferIsComplete_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostTransferIsComplete' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostTransferIsComplete' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_endpoint), (void*)(&endpoint), sizeof(BYTE), cmock_line, "Function 'USBHostTransferIsComplete' called with unexpected value for argument 'endpoint'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_errorCode), (void*)(errorCode), sizeof(BYTE), cmock_line, "Function 'USBHostTransferIsComplete' called with unexpected value for argument 'errorCode'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_byteCount), (void*)(byteCount), sizeof(DWORD), cmock_line, "Function 'USBHostTransferIsComplete' called with unexpected value for argument 'byteCount'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostTransferIsComplete(CMOCK_USBHostTransferIsComplete_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE endpoint, BYTE* errorCode, DWORD* byteCount)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_endpoint, &endpoint, sizeof(BYTE));
  cmock_call_instance->Expected_errorCode = errorCode;
  cmock_call_instance->Expected_byteCount = byteCount;
}

void USBHostTransferIsComplete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE endpoint, BYTE* errorCode, DWORD* byteCount, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostTransferIsComplete_CALL_INSTANCE));
  CMOCK_USBHostTransferIsComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostTransferIsComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostTransferIsComplete_CallInstance = CMock_Guts_MemChain(Mock.USBHostTransferIsComplete_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostTransferIsComplete(cmock_call_instance, deviceAddress, endpoint, errorCode, byteCount);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BYTE USBHostVbusEvent(USB_EVENT vbusEvent, BYTE hubAddress, BYTE portNumber)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostVbusEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostVbusEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostVbusEvent_CallInstance);
  Mock.USBHostVbusEvent_CallInstance = CMock_Guts_MemNext(Mock.USBHostVbusEvent_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostVbusEvent' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_vbusEvent), (void*)(&vbusEvent), sizeof(USB_EVENT), cmock_line, "Function 'USBHostVbusEvent' called with unexpected value for argument 'vbusEvent'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_hubAddress), (void*)(&hubAddress), sizeof(BYTE), cmock_line, "Function 'USBHostVbusEvent' called with unexpected value for argument 'hubAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_portNumber), (void*)(&portNumber), sizeof(BYTE), cmock_line, "Function 'USBHostVbusEvent' called with unexpected value for argument 'portNumber'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostVbusEvent(CMOCK_USBHostVbusEvent_CALL_INSTANCE* cmock_call_instance, USB_EVENT vbusEvent, BYTE hubAddress, BYTE portNumber)
{
  memcpy(&cmock_call_instance->Expected_vbusEvent, &vbusEvent, sizeof(USB_EVENT));
  memcpy(&cmock_call_instance->Expected_hubAddress, &hubAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_portNumber, &portNumber, sizeof(BYTE));
}

void USBHostVbusEvent_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, USB_EVENT vbusEvent, BYTE hubAddress, BYTE portNumber, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostVbusEvent_CALL_INSTANCE));
  CMOCK_USBHostVbusEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostVbusEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostVbusEvent_CallInstance = CMock_Guts_MemChain(Mock.USBHostVbusEvent_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostVbusEvent(cmock_call_instance, vbusEvent, hubAddress, portNumber);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BYTE USBHostWrite(BYTE deviceAddress, BYTE endpoint, BYTE* data, DWORD size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostWrite_CallInstance);
  Mock.USBHostWrite_CallInstance = CMock_Guts_MemNext(Mock.USBHostWrite_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostWrite' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostWrite' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_endpoint), (void*)(&endpoint), sizeof(BYTE), cmock_line, "Function 'USBHostWrite' called with unexpected value for argument 'endpoint'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(BYTE), cmock_line, "Function 'USBHostWrite' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(DWORD), cmock_line, "Function 'USBHostWrite' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostWrite(CMOCK_USBHostWrite_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE endpoint, BYTE* data, DWORD size)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_endpoint, &endpoint, sizeof(BYTE));
  cmock_call_instance->Expected_data = data;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(DWORD));
}

void USBHostWrite_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE endpoint, BYTE* data, DWORD size, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostWrite_CALL_INSTANCE));
  CMOCK_USBHostWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostWrite_CallInstance = CMock_Guts_MemChain(Mock.USBHostWrite_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostWrite(cmock_call_instance, deviceAddress, endpoint, data, size);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

