/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockGrid.h"

typedef struct _CMOCK_GridClearCellState_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GRID* Expected_pGrid;
  SHORT Expected_column;
  SHORT Expected_row;
  WORD Expected_state;

} CMOCK_GridClearCellState_CALL_INSTANCE;

typedef struct _CMOCK_GridCreate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GRID* ReturnVal;
  WORD Expected_ID;
  SHORT Expected_left;
  SHORT Expected_top;
  SHORT Expected_right;
  SHORT Expected_bottom;
  WORD Expected_state;
  SHORT Expected_numColumns;
  SHORT Expected_numRows;
  SHORT Expected_cellWidth;
  SHORT Expected_cellHeight;
  GOL_SCHEME* Expected_pScheme;

} CMOCK_GridCreate_CALL_INSTANCE;

typedef struct _CMOCK_GridDraw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD ReturnVal;
  GRID* Expected_pGrid;

} CMOCK_GridDraw_CALL_INSTANCE;

typedef struct _CMOCK_GridFreeItems_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GRID* Expected_pGrid;

} CMOCK_GridFreeItems_CALL_INSTANCE;

typedef struct _CMOCK_GridGetCell_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* ReturnVal;
  GRID* Expected_pGrid;
  SHORT Expected_column;
  SHORT Expected_row;
  WORD* Expected_cellType;

} CMOCK_GridGetCell_CALL_INSTANCE;

typedef struct _CMOCK_GridMsgDefault_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD Expected_translatedMsg;
  GRID* Expected_pGrid;
  GOL_MSG* Expected_pMsg;

} CMOCK_GridMsgDefault_CALL_INSTANCE;

typedef struct _CMOCK_GridSetCell_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD ReturnVal;
  GRID* Expected_pGrid;
  SHORT Expected_column;
  SHORT Expected_row;
  WORD Expected_state;
  void* Expected_data;

} CMOCK_GridSetCell_CALL_INSTANCE;

typedef struct _CMOCK_GridSetCellState_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GRID* Expected_pGrid;
  SHORT Expected_column;
  SHORT Expected_row;
  WORD Expected_state;

} CMOCK_GridSetCellState_CALL_INSTANCE;

typedef struct _CMOCK_GridSetFocus_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GRID* Expected_pGrid;
  SHORT Expected_column;
  SHORT Expected_row;

} CMOCK_GridSetFocus_CALL_INSTANCE;

typedef struct _CMOCK_GridTranslateMsg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD ReturnVal;
  GRID* Expected_pCb;
  GOL_MSG* Expected_pMsg;

} CMOCK_GridTranslateMsg_CALL_INSTANCE;

static struct MockGridInstance
{
  CMOCK_MEM_INDEX_TYPE GridClearCellState_CallInstance;
  CMOCK_MEM_INDEX_TYPE GridCreate_CallInstance;
  CMOCK_MEM_INDEX_TYPE GridDraw_CallInstance;
  CMOCK_MEM_INDEX_TYPE GridFreeItems_CallInstance;
  CMOCK_MEM_INDEX_TYPE GridGetCell_CallInstance;
  CMOCK_MEM_INDEX_TYPE GridMsgDefault_CallInstance;
  CMOCK_MEM_INDEX_TYPE GridSetCell_CallInstance;
  CMOCK_MEM_INDEX_TYPE GridSetCellState_CallInstance;
  CMOCK_MEM_INDEX_TYPE GridSetFocus_CallInstance;
  CMOCK_MEM_INDEX_TYPE GridTranslateMsg_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockGrid_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GridClearCellState_CallInstance, cmock_line, "Function 'GridClearCellState' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GridCreate_CallInstance, cmock_line, "Function 'GridCreate' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GridDraw_CallInstance, cmock_line, "Function 'GridDraw' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GridFreeItems_CallInstance, cmock_line, "Function 'GridFreeItems' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GridGetCell_CallInstance, cmock_line, "Function 'GridGetCell' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GridMsgDefault_CallInstance, cmock_line, "Function 'GridMsgDefault' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GridSetCell_CallInstance, cmock_line, "Function 'GridSetCell' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GridSetCellState_CallInstance, cmock_line, "Function 'GridSetCellState' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GridSetFocus_CallInstance, cmock_line, "Function 'GridSetFocus' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GridTranslateMsg_CallInstance, cmock_line, "Function 'GridTranslateMsg' called less times than expected.");
}

void MockGrid_Init(void)
{
  MockGrid_Destroy();
}

void MockGrid_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void GridClearCellState(GRID* pGrid, SHORT column, SHORT row, WORD state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GridClearCellState_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridClearCellState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GridClearCellState_CallInstance);
  Mock.GridClearCellState_CallInstance = CMock_Guts_MemNext(Mock.GridClearCellState_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GridClearCellState' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGrid), (void*)(pGrid), sizeof(GRID), cmock_line, "Function 'GridClearCellState' called with unexpected value for argument 'pGrid'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_column), (void*)(&column), sizeof(SHORT), cmock_line, "Function 'GridClearCellState' called with unexpected value for argument 'column'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_row), (void*)(&row), sizeof(SHORT), cmock_line, "Function 'GridClearCellState' called with unexpected value for argument 'row'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(WORD), cmock_line, "Function 'GridClearCellState' called with unexpected value for argument 'state'.");
  }
}

void CMockExpectParameters_GridClearCellState(CMOCK_GridClearCellState_CALL_INSTANCE* cmock_call_instance, GRID* pGrid, SHORT column, SHORT row, WORD state)
{
  cmock_call_instance->Expected_pGrid = pGrid;
  memcpy(&cmock_call_instance->Expected_column, &column, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_row, &row, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(WORD));
}

void GridClearCellState_CMockExpect(UNITY_LINE_TYPE cmock_line, GRID* pGrid, SHORT column, SHORT row, WORD state)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GridClearCellState_CALL_INSTANCE));
  CMOCK_GridClearCellState_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridClearCellState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GridClearCellState_CallInstance = CMock_Guts_MemChain(Mock.GridClearCellState_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GridClearCellState(cmock_call_instance, pGrid, column, row, state);
}

GRID* GridCreate(WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, SHORT numColumns, SHORT numRows, SHORT cellWidth, SHORT cellHeight, GOL_SCHEME* pScheme)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GridCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GridCreate_CallInstance);
  Mock.GridCreate_CallInstance = CMock_Guts_MemNext(Mock.GridCreate_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GridCreate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ID), (void*)(&ID), sizeof(WORD), cmock_line, "Function 'GridCreate' called with unexpected value for argument 'ID'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_left), (void*)(&left), sizeof(SHORT), cmock_line, "Function 'GridCreate' called with unexpected value for argument 'left'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_top), (void*)(&top), sizeof(SHORT), cmock_line, "Function 'GridCreate' called with unexpected value for argument 'top'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_right), (void*)(&right), sizeof(SHORT), cmock_line, "Function 'GridCreate' called with unexpected value for argument 'right'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bottom), (void*)(&bottom), sizeof(SHORT), cmock_line, "Function 'GridCreate' called with unexpected value for argument 'bottom'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(WORD), cmock_line, "Function 'GridCreate' called with unexpected value for argument 'state'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_numColumns), (void*)(&numColumns), sizeof(SHORT), cmock_line, "Function 'GridCreate' called with unexpected value for argument 'numColumns'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_numRows), (void*)(&numRows), sizeof(SHORT), cmock_line, "Function 'GridCreate' called with unexpected value for argument 'numRows'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cellWidth), (void*)(&cellWidth), sizeof(SHORT), cmock_line, "Function 'GridCreate' called with unexpected value for argument 'cellWidth'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cellHeight), (void*)(&cellHeight), sizeof(SHORT), cmock_line, "Function 'GridCreate' called with unexpected value for argument 'cellHeight'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pScheme), (void*)(pScheme), sizeof(GOL_SCHEME), cmock_line, "Function 'GridCreate' called with unexpected value for argument 'pScheme'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_GridCreate(CMOCK_GridCreate_CALL_INSTANCE* cmock_call_instance, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, SHORT numColumns, SHORT numRows, SHORT cellWidth, SHORT cellHeight, GOL_SCHEME* pScheme)
{
  memcpy(&cmock_call_instance->Expected_ID, &ID, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_left, &left, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_top, &top, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_right, &right, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_bottom, &bottom, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_numColumns, &numColumns, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_numRows, &numRows, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_cellWidth, &cellWidth, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_cellHeight, &cellHeight, sizeof(SHORT));
  cmock_call_instance->Expected_pScheme = pScheme;
}

void GridCreate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, SHORT numColumns, SHORT numRows, SHORT cellWidth, SHORT cellHeight, GOL_SCHEME* pScheme, GRID* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GridCreate_CALL_INSTANCE));
  CMOCK_GridCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GridCreate_CallInstance = CMock_Guts_MemChain(Mock.GridCreate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GridCreate(cmock_call_instance, ID, left, top, right, bottom, state, numColumns, numRows, cellWidth, cellHeight, pScheme);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

WORD GridDraw(GRID* pGrid)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GridDraw_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridDraw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GridDraw_CallInstance);
  Mock.GridDraw_CallInstance = CMock_Guts_MemNext(Mock.GridDraw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GridDraw' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGrid), (void*)(pGrid), sizeof(GRID), cmock_line, "Function 'GridDraw' called with unexpected value for argument 'pGrid'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_GridDraw(CMOCK_GridDraw_CALL_INSTANCE* cmock_call_instance, GRID* pGrid)
{
  cmock_call_instance->Expected_pGrid = pGrid;
}

void GridDraw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GRID* pGrid, WORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GridDraw_CALL_INSTANCE));
  CMOCK_GridDraw_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridDraw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GridDraw_CallInstance = CMock_Guts_MemChain(Mock.GridDraw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GridDraw(cmock_call_instance, pGrid);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(WORD));
}

void GridFreeItems(GRID* pGrid)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GridFreeItems_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridFreeItems_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GridFreeItems_CallInstance);
  Mock.GridFreeItems_CallInstance = CMock_Guts_MemNext(Mock.GridFreeItems_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GridFreeItems' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGrid), (void*)(pGrid), sizeof(GRID), cmock_line, "Function 'GridFreeItems' called with unexpected value for argument 'pGrid'.");
  }
}

void CMockExpectParameters_GridFreeItems(CMOCK_GridFreeItems_CALL_INSTANCE* cmock_call_instance, GRID* pGrid)
{
  cmock_call_instance->Expected_pGrid = pGrid;
}

void GridFreeItems_CMockExpect(UNITY_LINE_TYPE cmock_line, GRID* pGrid)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GridFreeItems_CALL_INSTANCE));
  CMOCK_GridFreeItems_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridFreeItems_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GridFreeItems_CallInstance = CMock_Guts_MemChain(Mock.GridFreeItems_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GridFreeItems(cmock_call_instance, pGrid);
}

void* GridGetCell(GRID* pGrid, SHORT column, SHORT row, WORD* cellType)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GridGetCell_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridGetCell_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GridGetCell_CallInstance);
  Mock.GridGetCell_CallInstance = CMock_Guts_MemNext(Mock.GridGetCell_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GridGetCell' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGrid), (void*)(pGrid), sizeof(GRID), cmock_line, "Function 'GridGetCell' called with unexpected value for argument 'pGrid'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_column), (void*)(&column), sizeof(SHORT), cmock_line, "Function 'GridGetCell' called with unexpected value for argument 'column'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_row), (void*)(&row), sizeof(SHORT), cmock_line, "Function 'GridGetCell' called with unexpected value for argument 'row'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cellType), (void*)(cellType), sizeof(WORD), cmock_line, "Function 'GridGetCell' called with unexpected value for argument 'cellType'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_GridGetCell(CMOCK_GridGetCell_CALL_INSTANCE* cmock_call_instance, GRID* pGrid, SHORT column, SHORT row, WORD* cellType)
{
  cmock_call_instance->Expected_pGrid = pGrid;
  memcpy(&cmock_call_instance->Expected_column, &column, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_row, &row, sizeof(SHORT));
  cmock_call_instance->Expected_cellType = cellType;
}

void GridGetCell_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GRID* pGrid, SHORT column, SHORT row, WORD* cellType, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GridGetCell_CALL_INSTANCE));
  CMOCK_GridGetCell_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridGetCell_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GridGetCell_CallInstance = CMock_Guts_MemChain(Mock.GridGetCell_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GridGetCell(cmock_call_instance, pGrid, column, row, cellType);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void GridMsgDefault(WORD translatedMsg, GRID* pGrid, GOL_MSG* pMsg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GridMsgDefault_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridMsgDefault_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GridMsgDefault_CallInstance);
  Mock.GridMsgDefault_CallInstance = CMock_Guts_MemNext(Mock.GridMsgDefault_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GridMsgDefault' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_translatedMsg), (void*)(&translatedMsg), sizeof(WORD), cmock_line, "Function 'GridMsgDefault' called with unexpected value for argument 'translatedMsg'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGrid), (void*)(pGrid), sizeof(GRID), cmock_line, "Function 'GridMsgDefault' called with unexpected value for argument 'pGrid'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMsg), (void*)(pMsg), sizeof(GOL_MSG), cmock_line, "Function 'GridMsgDefault' called with unexpected value for argument 'pMsg'.");
  }
}

void CMockExpectParameters_GridMsgDefault(CMOCK_GridMsgDefault_CALL_INSTANCE* cmock_call_instance, WORD translatedMsg, GRID* pGrid, GOL_MSG* pMsg)
{
  memcpy(&cmock_call_instance->Expected_translatedMsg, &translatedMsg, sizeof(WORD));
  cmock_call_instance->Expected_pGrid = pGrid;
  cmock_call_instance->Expected_pMsg = pMsg;
}

void GridMsgDefault_CMockExpect(UNITY_LINE_TYPE cmock_line, WORD translatedMsg, GRID* pGrid, GOL_MSG* pMsg)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GridMsgDefault_CALL_INSTANCE));
  CMOCK_GridMsgDefault_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridMsgDefault_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GridMsgDefault_CallInstance = CMock_Guts_MemChain(Mock.GridMsgDefault_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GridMsgDefault(cmock_call_instance, translatedMsg, pGrid, pMsg);
}

WORD GridSetCell(GRID* pGrid, SHORT column, SHORT row, WORD state, void* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GridSetCell_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridSetCell_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GridSetCell_CallInstance);
  Mock.GridSetCell_CallInstance = CMock_Guts_MemNext(Mock.GridSetCell_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GridSetCell' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGrid), (void*)(pGrid), sizeof(GRID), cmock_line, "Function 'GridSetCell' called with unexpected value for argument 'pGrid'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_column), (void*)(&column), sizeof(SHORT), cmock_line, "Function 'GridSetCell' called with unexpected value for argument 'column'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_row), (void*)(&row), sizeof(SHORT), cmock_line, "Function 'GridSetCell' called with unexpected value for argument 'row'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(WORD), cmock_line, "Function 'GridSetCell' called with unexpected value for argument 'state'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_data, data, cmock_line, "Function 'GridSetCell' called with unexpected value for argument 'data'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_GridSetCell(CMOCK_GridSetCell_CALL_INSTANCE* cmock_call_instance, GRID* pGrid, SHORT column, SHORT row, WORD state, void* data)
{
  cmock_call_instance->Expected_pGrid = pGrid;
  memcpy(&cmock_call_instance->Expected_column, &column, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_row, &row, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(WORD));
  cmock_call_instance->Expected_data = data;
}

void GridSetCell_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GRID* pGrid, SHORT column, SHORT row, WORD state, void* data, WORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GridSetCell_CALL_INSTANCE));
  CMOCK_GridSetCell_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridSetCell_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GridSetCell_CallInstance = CMock_Guts_MemChain(Mock.GridSetCell_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GridSetCell(cmock_call_instance, pGrid, column, row, state, data);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(WORD));
}

void GridSetCellState(GRID* pGrid, SHORT column, SHORT row, WORD state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GridSetCellState_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridSetCellState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GridSetCellState_CallInstance);
  Mock.GridSetCellState_CallInstance = CMock_Guts_MemNext(Mock.GridSetCellState_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GridSetCellState' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGrid), (void*)(pGrid), sizeof(GRID), cmock_line, "Function 'GridSetCellState' called with unexpected value for argument 'pGrid'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_column), (void*)(&column), sizeof(SHORT), cmock_line, "Function 'GridSetCellState' called with unexpected value for argument 'column'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_row), (void*)(&row), sizeof(SHORT), cmock_line, "Function 'GridSetCellState' called with unexpected value for argument 'row'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(WORD), cmock_line, "Function 'GridSetCellState' called with unexpected value for argument 'state'.");
  }
}

void CMockExpectParameters_GridSetCellState(CMOCK_GridSetCellState_CALL_INSTANCE* cmock_call_instance, GRID* pGrid, SHORT column, SHORT row, WORD state)
{
  cmock_call_instance->Expected_pGrid = pGrid;
  memcpy(&cmock_call_instance->Expected_column, &column, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_row, &row, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(WORD));
}

void GridSetCellState_CMockExpect(UNITY_LINE_TYPE cmock_line, GRID* pGrid, SHORT column, SHORT row, WORD state)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GridSetCellState_CALL_INSTANCE));
  CMOCK_GridSetCellState_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridSetCellState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GridSetCellState_CallInstance = CMock_Guts_MemChain(Mock.GridSetCellState_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GridSetCellState(cmock_call_instance, pGrid, column, row, state);
}

void GridSetFocus(GRID* pGrid, SHORT column, SHORT row)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GridSetFocus_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridSetFocus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GridSetFocus_CallInstance);
  Mock.GridSetFocus_CallInstance = CMock_Guts_MemNext(Mock.GridSetFocus_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GridSetFocus' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGrid), (void*)(pGrid), sizeof(GRID), cmock_line, "Function 'GridSetFocus' called with unexpected value for argument 'pGrid'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_column), (void*)(&column), sizeof(SHORT), cmock_line, "Function 'GridSetFocus' called with unexpected value for argument 'column'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_row), (void*)(&row), sizeof(SHORT), cmock_line, "Function 'GridSetFocus' called with unexpected value for argument 'row'.");
  }
}

void CMockExpectParameters_GridSetFocus(CMOCK_GridSetFocus_CALL_INSTANCE* cmock_call_instance, GRID* pGrid, SHORT column, SHORT row)
{
  cmock_call_instance->Expected_pGrid = pGrid;
  memcpy(&cmock_call_instance->Expected_column, &column, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_row, &row, sizeof(SHORT));
}

void GridSetFocus_CMockExpect(UNITY_LINE_TYPE cmock_line, GRID* pGrid, SHORT column, SHORT row)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GridSetFocus_CALL_INSTANCE));
  CMOCK_GridSetFocus_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridSetFocus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GridSetFocus_CallInstance = CMock_Guts_MemChain(Mock.GridSetFocus_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GridSetFocus(cmock_call_instance, pGrid, column, row);
}

WORD GridTranslateMsg(GRID* pCb, GOL_MSG* pMsg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GridTranslateMsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridTranslateMsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GridTranslateMsg_CallInstance);
  Mock.GridTranslateMsg_CallInstance = CMock_Guts_MemNext(Mock.GridTranslateMsg_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GridTranslateMsg' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pCb), (void*)(pCb), sizeof(GRID), cmock_line, "Function 'GridTranslateMsg' called with unexpected value for argument 'pCb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMsg), (void*)(pMsg), sizeof(GOL_MSG), cmock_line, "Function 'GridTranslateMsg' called with unexpected value for argument 'pMsg'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_GridTranslateMsg(CMOCK_GridTranslateMsg_CALL_INSTANCE* cmock_call_instance, GRID* pCb, GOL_MSG* pMsg)
{
  cmock_call_instance->Expected_pCb = pCb;
  cmock_call_instance->Expected_pMsg = pMsg;
}

void GridTranslateMsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GRID* pCb, GOL_MSG* pMsg, WORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GridTranslateMsg_CALL_INSTANCE));
  CMOCK_GridTranslateMsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_GridTranslateMsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GridTranslateMsg_CallInstance = CMock_Guts_MemChain(Mock.GridTranslateMsg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GridTranslateMsg(cmock_call_instance, pCb, pMsg);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(WORD));
}

