/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockFSconfig.h"

static struct MockFSconfigInstance
{
  unsigned char placeHolder;
} Mock;

extern jmp_buf AbortFrame;

void MockFSconfig_Verify(void)
{
}

void MockFSconfig_Init(void)
{
  MockFSconfig_Destroy();
}

void MockFSconfig_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

