/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKJPEGDECODER_H
#define _MOCKJPEGDECODER_H

#include "JpegDecoder.h"

void MockJpegDecoder_Init(void);
void MockJpegDecoder_Destroy(void);
void MockJpegDecoder_Verify(void);




#define JPEG_bDecode_ExpectAndReturn(pfile, cmock_retval) JPEG_bDecode_CMockExpectAndReturn(__LINE__, pfile, cmock_retval)
void JPEG_bDecode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, IMG_FILE* pfile, BYTE cmock_to_return);

#endif
