/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKGROUPBOX_H
#define _MOCKGROUPBOX_H

#include "GroupBox.h"

void MockGroupBox_Init(void);
void MockGroupBox_Destroy(void);
void MockGroupBox_Verify(void);




#define GbSetText_Expect(pGb, pText) GbSetText_CMockExpect(__LINE__, pGb, pText)
void GbSetText_CMockExpect(UNITY_LINE_TYPE cmock_line, GROUPBOX* pGb, XCHAR* pText);
#define GbTranslateMsg_ExpectAndReturn(pGb, pMsg, cmock_retval) GbTranslateMsg_CMockExpectAndReturn(__LINE__, pGb, pMsg, cmock_retval)
void GbTranslateMsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GROUPBOX* pGb, GOL_MSG* pMsg, WORD cmock_to_return);
#define GbCreate_ExpectAndReturn(ID, left, top, right, bottom, state, pText, pScheme, cmock_retval) GbCreate_CMockExpectAndReturn(__LINE__, ID, left, top, right, bottom, state, pText, pScheme, cmock_retval)
void GbCreate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, XCHAR* pText, GOL_SCHEME* pScheme, GROUPBOX* cmock_to_return);
#define GbDraw_ExpectAndReturn(pGb, cmock_retval) GbDraw_CMockExpectAndReturn(__LINE__, pGb, cmock_retval)
void GbDraw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GROUPBOX* pGb, WORD cmock_to_return);

#endif
