/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockusb_host_msd.h"

typedef struct _CMOCK_USBHostMSDDeviceStatus_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;

} CMOCK_USBHostMSDDeviceStatus_CALL_INSTANCE;

typedef struct _CMOCK_USBHostMSDResetDevice_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;

} CMOCK_USBHostMSDResetDevice_CALL_INSTANCE;

typedef struct _CMOCK_USBHostMSDTasks_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USBHostMSDTasks_CALL_INSTANCE;

typedef struct _CMOCK_USBHostMSDTerminateTransfer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE Expected_deviceAddress;

} CMOCK_USBHostMSDTerminateTransfer_CALL_INSTANCE;

typedef struct _CMOCK_USBHostMSDTransfer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE Expected_deviceLUN;
  BYTE Expected_direction;
  BYTE* Expected_commandBlock;
  BYTE Expected_commandBlockLength;
  BYTE* Expected_data;
  DWORD Expected_dataLength;

} CMOCK_USBHostMSDTransfer_CALL_INSTANCE;

typedef struct _CMOCK_USBHostMSDTransferIsComplete_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE* Expected_errorCode;
  DWORD* Expected_byteCount;

} CMOCK_USBHostMSDTransferIsComplete_CALL_INSTANCE;

typedef struct _CMOCK_USBHostMSDInitialize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_address;
  DWORD Expected_flags;
  BYTE Expected_clientDriverID;

} CMOCK_USBHostMSDInitialize_CALL_INSTANCE;

typedef struct _CMOCK_USBHostMSDEventHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_address;
  USB_EVENT Expected_event;
  void* Expected_data;
  DWORD Expected_size;

} CMOCK_USBHostMSDEventHandler_CALL_INSTANCE;

static struct Mockusb_host_msdInstance
{
  CMOCK_MEM_INDEX_TYPE USBHostMSDDeviceStatus_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostMSDResetDevice_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostMSDTasks_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostMSDTerminateTransfer_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostMSDTransfer_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostMSDTransferIsComplete_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostMSDInitialize_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostMSDEventHandler_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockusb_host_msd_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostMSDDeviceStatus_CallInstance, cmock_line, "Function 'USBHostMSDDeviceStatus' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostMSDResetDevice_CallInstance, cmock_line, "Function 'USBHostMSDResetDevice' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostMSDTasks_CallInstance, cmock_line, "Function 'USBHostMSDTasks' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostMSDTerminateTransfer_CallInstance, cmock_line, "Function 'USBHostMSDTerminateTransfer' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostMSDTransfer_CallInstance, cmock_line, "Function 'USBHostMSDTransfer' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostMSDTransferIsComplete_CallInstance, cmock_line, "Function 'USBHostMSDTransferIsComplete' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostMSDInitialize_CallInstance, cmock_line, "Function 'USBHostMSDInitialize' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostMSDEventHandler_CallInstance, cmock_line, "Function 'USBHostMSDEventHandler' called less times than expected.");
}

void Mockusb_host_msd_Init(void)
{
  Mockusb_host_msd_Destroy();
}

void Mockusb_host_msd_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

BYTE USBHostMSDDeviceStatus(BYTE deviceAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostMSDDeviceStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDDeviceStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostMSDDeviceStatus_CallInstance);
  Mock.USBHostMSDDeviceStatus_CallInstance = CMock_Guts_MemNext(Mock.USBHostMSDDeviceStatus_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostMSDDeviceStatus' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostMSDDeviceStatus' called with unexpected value for argument 'deviceAddress'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostMSDDeviceStatus(CMOCK_USBHostMSDDeviceStatus_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
}

void USBHostMSDDeviceStatus_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostMSDDeviceStatus_CALL_INSTANCE));
  CMOCK_USBHostMSDDeviceStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDDeviceStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostMSDDeviceStatus_CallInstance = CMock_Guts_MemChain(Mock.USBHostMSDDeviceStatus_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostMSDDeviceStatus(cmock_call_instance, deviceAddress);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BYTE USBHostMSDResetDevice(BYTE deviceAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostMSDResetDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDResetDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostMSDResetDevice_CallInstance);
  Mock.USBHostMSDResetDevice_CallInstance = CMock_Guts_MemNext(Mock.USBHostMSDResetDevice_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostMSDResetDevice' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostMSDResetDevice' called with unexpected value for argument 'deviceAddress'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostMSDResetDevice(CMOCK_USBHostMSDResetDevice_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
}

void USBHostMSDResetDevice_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostMSDResetDevice_CALL_INSTANCE));
  CMOCK_USBHostMSDResetDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDResetDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostMSDResetDevice_CallInstance = CMock_Guts_MemChain(Mock.USBHostMSDResetDevice_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostMSDResetDevice(cmock_call_instance, deviceAddress);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

void USBHostMSDTasks(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostMSDTasks_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDTasks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostMSDTasks_CallInstance);
  Mock.USBHostMSDTasks_CallInstance = CMock_Guts_MemNext(Mock.USBHostMSDTasks_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostMSDTasks' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void USBHostMSDTasks_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostMSDTasks_CALL_INSTANCE));
  CMOCK_USBHostMSDTasks_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDTasks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostMSDTasks_CallInstance = CMock_Guts_MemChain(Mock.USBHostMSDTasks_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void USBHostMSDTerminateTransfer(BYTE deviceAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostMSDTerminateTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDTerminateTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostMSDTerminateTransfer_CallInstance);
  Mock.USBHostMSDTerminateTransfer_CallInstance = CMock_Guts_MemNext(Mock.USBHostMSDTerminateTransfer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostMSDTerminateTransfer' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostMSDTerminateTransfer' called with unexpected value for argument 'deviceAddress'.");
  }
}

void CMockExpectParameters_USBHostMSDTerminateTransfer(CMOCK_USBHostMSDTerminateTransfer_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
}

void USBHostMSDTerminateTransfer_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostMSDTerminateTransfer_CALL_INSTANCE));
  CMOCK_USBHostMSDTerminateTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDTerminateTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostMSDTerminateTransfer_CallInstance = CMock_Guts_MemChain(Mock.USBHostMSDTerminateTransfer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostMSDTerminateTransfer(cmock_call_instance, deviceAddress);
}

BYTE USBHostMSDTransfer(BYTE deviceAddress, BYTE deviceLUN, BYTE direction, BYTE* commandBlock, BYTE commandBlockLength, BYTE* data, DWORD dataLength)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostMSDTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostMSDTransfer_CallInstance);
  Mock.USBHostMSDTransfer_CallInstance = CMock_Guts_MemNext(Mock.USBHostMSDTransfer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostMSDTransfer' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostMSDTransfer' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceLUN), (void*)(&deviceLUN), sizeof(BYTE), cmock_line, "Function 'USBHostMSDTransfer' called with unexpected value for argument 'deviceLUN'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_direction), (void*)(&direction), sizeof(BYTE), cmock_line, "Function 'USBHostMSDTransfer' called with unexpected value for argument 'direction'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_commandBlock), (void*)(commandBlock), sizeof(BYTE), cmock_line, "Function 'USBHostMSDTransfer' called with unexpected value for argument 'commandBlock'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_commandBlockLength), (void*)(&commandBlockLength), sizeof(BYTE), cmock_line, "Function 'USBHostMSDTransfer' called with unexpected value for argument 'commandBlockLength'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(BYTE), cmock_line, "Function 'USBHostMSDTransfer' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dataLength), (void*)(&dataLength), sizeof(DWORD), cmock_line, "Function 'USBHostMSDTransfer' called with unexpected value for argument 'dataLength'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostMSDTransfer(CMOCK_USBHostMSDTransfer_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE deviceLUN, BYTE direction, BYTE* commandBlock, BYTE commandBlockLength, BYTE* data, DWORD dataLength)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_deviceLUN, &deviceLUN, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_direction, &direction, sizeof(BYTE));
  cmock_call_instance->Expected_commandBlock = commandBlock;
  memcpy(&cmock_call_instance->Expected_commandBlockLength, &commandBlockLength, sizeof(BYTE));
  cmock_call_instance->Expected_data = data;
  memcpy(&cmock_call_instance->Expected_dataLength, &dataLength, sizeof(DWORD));
}

void USBHostMSDTransfer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE deviceLUN, BYTE direction, BYTE* commandBlock, BYTE commandBlockLength, BYTE* data, DWORD dataLength, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostMSDTransfer_CALL_INSTANCE));
  CMOCK_USBHostMSDTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostMSDTransfer_CallInstance = CMock_Guts_MemChain(Mock.USBHostMSDTransfer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostMSDTransfer(cmock_call_instance, deviceAddress, deviceLUN, direction, commandBlock, commandBlockLength, data, dataLength);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BOOL USBHostMSDTransferIsComplete(BYTE deviceAddress, BYTE* errorCode, DWORD* byteCount)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostMSDTransferIsComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDTransferIsComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostMSDTransferIsComplete_CallInstance);
  Mock.USBHostMSDTransferIsComplete_CallInstance = CMock_Guts_MemNext(Mock.USBHostMSDTransferIsComplete_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostMSDTransferIsComplete' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostMSDTransferIsComplete' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_errorCode), (void*)(errorCode), sizeof(BYTE), cmock_line, "Function 'USBHostMSDTransferIsComplete' called with unexpected value for argument 'errorCode'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_byteCount), (void*)(byteCount), sizeof(DWORD), cmock_line, "Function 'USBHostMSDTransferIsComplete' called with unexpected value for argument 'byteCount'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostMSDTransferIsComplete(CMOCK_USBHostMSDTransferIsComplete_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE* errorCode, DWORD* byteCount)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  cmock_call_instance->Expected_errorCode = errorCode;
  cmock_call_instance->Expected_byteCount = byteCount;
}

void USBHostMSDTransferIsComplete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE* errorCode, DWORD* byteCount, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostMSDTransferIsComplete_CALL_INSTANCE));
  CMOCK_USBHostMSDTransferIsComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDTransferIsComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostMSDTransferIsComplete_CallInstance = CMock_Guts_MemChain(Mock.USBHostMSDTransferIsComplete_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostMSDTransferIsComplete(cmock_call_instance, deviceAddress, errorCode, byteCount);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BOOL USBHostMSDInitialize(BYTE address, DWORD flags, BYTE clientDriverID)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostMSDInitialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDInitialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostMSDInitialize_CallInstance);
  Mock.USBHostMSDInitialize_CallInstance = CMock_Guts_MemNext(Mock.USBHostMSDInitialize_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostMSDInitialize' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_address), (void*)(&address), sizeof(BYTE), cmock_line, "Function 'USBHostMSDInitialize' called with unexpected value for argument 'address'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_flags), (void*)(&flags), sizeof(DWORD), cmock_line, "Function 'USBHostMSDInitialize' called with unexpected value for argument 'flags'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_clientDriverID), (void*)(&clientDriverID), sizeof(BYTE), cmock_line, "Function 'USBHostMSDInitialize' called with unexpected value for argument 'clientDriverID'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostMSDInitialize(CMOCK_USBHostMSDInitialize_CALL_INSTANCE* cmock_call_instance, BYTE address, DWORD flags, BYTE clientDriverID)
{
  memcpy(&cmock_call_instance->Expected_address, &address, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_flags, &flags, sizeof(DWORD));
  memcpy(&cmock_call_instance->Expected_clientDriverID, &clientDriverID, sizeof(BYTE));
}

void USBHostMSDInitialize_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE address, DWORD flags, BYTE clientDriverID, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostMSDInitialize_CALL_INSTANCE));
  CMOCK_USBHostMSDInitialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDInitialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostMSDInitialize_CallInstance = CMock_Guts_MemChain(Mock.USBHostMSDInitialize_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostMSDInitialize(cmock_call_instance, address, flags, clientDriverID);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BOOL USBHostMSDEventHandler(BYTE address, USB_EVENT event, void* data, DWORD size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostMSDEventHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDEventHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostMSDEventHandler_CallInstance);
  Mock.USBHostMSDEventHandler_CallInstance = CMock_Guts_MemNext(Mock.USBHostMSDEventHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostMSDEventHandler' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_address), (void*)(&address), sizeof(BYTE), cmock_line, "Function 'USBHostMSDEventHandler' called with unexpected value for argument 'address'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_event), (void*)(&event), sizeof(USB_EVENT), cmock_line, "Function 'USBHostMSDEventHandler' called with unexpected value for argument 'event'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_data, data, cmock_line, "Function 'USBHostMSDEventHandler' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(DWORD), cmock_line, "Function 'USBHostMSDEventHandler' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostMSDEventHandler(CMOCK_USBHostMSDEventHandler_CALL_INSTANCE* cmock_call_instance, BYTE address, USB_EVENT event, void* data, DWORD size)
{
  memcpy(&cmock_call_instance->Expected_address, &address, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_event, &event, sizeof(USB_EVENT));
  cmock_call_instance->Expected_data = data;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(DWORD));
}

void USBHostMSDEventHandler_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE address, USB_EVENT event, void* data, DWORD size, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostMSDEventHandler_CALL_INSTANCE));
  CMOCK_USBHostMSDEventHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostMSDEventHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostMSDEventHandler_CallInstance = CMock_Guts_MemChain(Mock.USBHostMSDEventHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostMSDEventHandler(cmock_call_instance, address, event, data, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

