/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockUART.h"

static struct MockUARTInstance
{
  unsigned char placeHolder;
} Mock;

extern jmp_buf AbortFrame;

void MockUART_Verify(void)
{
}

void MockUART_Init(void)
{
  MockUART_Destroy();
}

void MockUART_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

