/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSYSTEM_H
#define _MOCKSYSTEM_H

#include "System.h"

void MockSystem_Init(void);
void MockSystem_Destroy(void);
void MockSystem_Verify(void);




#define SystemInit_Expect() SystemInit_CMockExpect(__LINE__)
void SystemInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define TimersInit_Expect() TimersInit_CMockExpect(__LINE__)
void TimersInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define I2CInit_Expect() I2CInit_CMockExpect(__LINE__)
void I2CInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define DisplayInit_Expect() DisplayInit_CMockExpect(__LINE__)
void DisplayInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define MemoryInit_Expect() MemoryInit_CMockExpect(__LINE__)
void MemoryInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define TimerInit_Expect() TimerInit_CMockExpect(__LINE__)
void TimerInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define SchemeInit_Expect() SchemeInit_CMockExpect(__LINE__)
void SchemeInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define VariableInit_Expect() VariableInit_CMockExpect(__LINE__)
void VariableInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define RTCCInit_Expect() RTCCInit_CMockExpect(__LINE__)
void RTCCInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define GetADCValue_ExpectAndReturn(index, cmock_retval) GetADCValue_CMockExpectAndReturn(__LINE__, index, cmock_retval)
void GetADCValue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE index, WORD cmock_to_return);
#define ExternalMemoryCallback_ExpectAndReturn(memory, offset, nCount, buffer, cmock_retval) ExternalMemoryCallback_CMockExpectAndReturn(__LINE__, memory, offset, nCount, buffer, cmock_retval)
void ExternalMemoryCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, EXTDATA* memory, LONG offset, WORD nCount, void* buffer, WORD cmock_to_return);
#define RTCCUpdate_Expect() RTCCUpdate_CMockExpect(__LINE__)
void RTCCUpdate_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define RTCCRead_Expect() RTCCRead_CMockExpect(__LINE__)
void RTCCRead_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define convert_BCD_ExpectAndReturn(binary_byte, cmock_retval) convert_BCD_CMockExpectAndReturn(__LINE__, binary_byte, cmock_retval)
void convert_BCD_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char binary_byte, unsigned char cmock_to_return);
#define unconvert_BCD_ExpectAndReturn(BCD_byte, cmock_retval) unconvert_BCD_CMockExpectAndReturn(__LINE__, BCD_byte, cmock_retval)
void unconvert_BCD_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char BCD_byte, unsigned char cmock_to_return);
#define Check_Audio_Status_Expect() Check_Audio_Status_CMockExpect(__LINE__)
void Check_Audio_Status_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Check_Battery_Expect() Check_Battery_CMockExpect(__LINE__)
void Check_Battery_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Check_High_Voltage_Expect(value) Check_High_Voltage_CMockExpect(__LINE__, value)
void Check_High_Voltage_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE value);
#define Check_Temperature_Expect() Check_Temperature_CMockExpect(__LINE__)
void Check_Temperature_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Check_Pressure_Expect() Check_Pressure_CMockExpect(__LINE__)
void Check_Pressure_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define add_error_message_to_queue_Expect(error) add_error_message_to_queue_CMockExpect(__LINE__, error)
void add_error_message_to_queue_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char error);
#define clear_error_message_off_queue_Expect() clear_error_message_off_queue_CMockExpect(__LINE__)
void clear_error_message_off_queue_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Check_Messages_Expect() Check_Messages_CMockExpect(__LINE__)
void Check_Messages_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Clear_All_Errors_Expect() Clear_All_Errors_CMockExpect(__LINE__)
void Clear_All_Errors_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Display_Error_Message_Expect() Display_Error_Message_CMockExpect(__LINE__)
void Display_Error_Message_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Calculate_Integrate_Value_Expect() Calculate_Integrate_Value_CMockExpect(__LINE__)
void Calculate_Integrate_Value_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Set_Audio_Tone_Expect() Set_Audio_Tone_CMockExpect(__LINE__)
void Set_Audio_Tone_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Set_Audio_Volume_Expect() Set_Audio_Volume_CMockExpect(__LINE__)
void Set_Audio_Volume_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Set_Backlight_Level_Expect(index) Set_Backlight_Level_CMockExpect(__LINE__, index)
void Set_Backlight_Level_CMockExpect(UNITY_LINE_TYPE cmock_line, char index);
#define Create_Measurement_Screen_Expect() Create_Measurement_Screen_CMockExpect(__LINE__)
void Create_Measurement_Screen_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Setup_Colors_Expect() Setup_Colors_CMockExpect(__LINE__)
void Setup_Colors_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define CheckCalibrationDueDate_Expect() CheckCalibrationDueDate_CMockExpect(__LINE__)
void CheckCalibrationDueDate_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define USB_Detect_Device_ExpectAndReturn(cmock_retval) USB_Detect_Device_CMockExpectAndReturn(__LINE__, cmock_retval)
void USB_Detect_Device_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE cmock_to_return);
#define Check_USB_Port_Expect() Check_USB_Port_CMockExpect(__LINE__)
void Check_USB_Port_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Check_FTDI_Adapter_Expect() Check_FTDI_Adapter_CMockExpect(__LINE__)
void Check_FTDI_Adapter_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Check_Thumbdrive_Expect() Check_Thumbdrive_CMockExpect(__LINE__)
void Check_Thumbdrive_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define FTDI_Receive_Expect() FTDI_Receive_CMockExpect(__LINE__)
void FTDI_Receive_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define FTDI_Transmit_Expect() FTDI_Transmit_CMockExpect(__LINE__)
void FTDI_Transmit_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define USBHostFTDI_DetectDevice_ExpectAndReturn(cmock_retval) USBHostFTDI_DetectDevice_CMockExpectAndReturn(__LINE__, cmock_retval)
void USBHostFTDI_DetectDevice_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BOOL cmock_to_return);
#define File_System_Initialize_ExpectAndReturn(cmock_retval) File_System_Initialize_CMockExpectAndReturn(__LINE__, cmock_retval)
void File_System_Initialize_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BOOL cmock_to_return);
#define USB_HID_DataCollectionHandler_ExpectAndReturn(cmock_retval) USB_HID_DataCollectionHandler_CMockExpectAndReturn(__LINE__, cmock_retval)
void USB_HID_DataCollectionHandler_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BOOL cmock_to_return);
#define Replace_Get_With_Set_Expect() Replace_Get_With_Set_CMockExpect(__LINE__)
void Replace_Get_With_Set_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Check_Keyboard_Expect() Check_Keyboard_CMockExpect(__LINE__)
void Check_Keyboard_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define USB_Keyboard_Routine_Expect(data, HIDData, state) USB_Keyboard_Routine_CMockExpect(__LINE__, data, HIDData, state)
void USB_Keyboard_Routine_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE data, BYTE HIDData, BOOL state);
#define USB_Keyboard_ProcessInputReport_Expect() USB_Keyboard_ProcessInputReport_CMockExpect(__LINE__)
void USB_Keyboard_ProcessInputReport_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define USB_Keyboard_PrepareOutputReport_Expect() USB_Keyboard_PrepareOutputReport_CMockExpect(__LINE__)
void USB_Keyboard_PrepareOutputReport_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define USB_Keyboard_ClearDataBuffer_Expect() USB_Keyboard_ClearDataBuffer_CMockExpect(__LINE__)
void USB_Keyboard_ClearDataBuffer_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define USB_Keyboard_CompareKeyPressedPrevBuf_ExpectAndReturn(data, cmock_retval) USB_Keyboard_CompareKeyPressedPrevBuf_CMockExpectAndReturn(__LINE__, data, cmock_retval)
void USB_Keyboard_CompareKeyPressedPrevBuf_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE data, BOOL cmock_to_return);
#define USB_Keyboard_CopyToShadowBuffer_Expect() USB_Keyboard_CopyToShadowBuffer_CMockExpect(__LINE__)
void USB_Keyboard_CopyToShadowBuffer_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define USB_Keyboard_HID2ASCII_ExpectAndReturn(a, cmock_retval) USB_Keyboard_HID2ASCII_CMockExpectAndReturn(__LINE__, a, cmock_retval)
void USB_Keyboard_HID2ASCII_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE a, BYTE cmock_to_return);
#define Configure_Header_Expect(message_buffer) Configure_Header_CMockExpect(__LINE__, message_buffer)
void Configure_Header_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE* message_buffer);
#define Configure_Message_Expect(message_buffer, message_type) Configure_Message_CMockExpect(__LINE__, message_buffer, message_type)
void Configure_Message_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE* message_buffer, BYTE message_type);
#define Configure_Data_Stream_Expect(message_buffer) Configure_Data_Stream_CMockExpect(__LINE__, message_buffer)
void Configure_Data_Stream_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE* message_buffer);
#define Format_Text_String_Expect(generic_string, message, message_length) Format_Text_String_CMockExpect(__LINE__, generic_string, message, message_length)
void Format_Text_String_CMockExpect(UNITY_LINE_TYPE cmock_line, char* generic_string, char* message, UINT8 message_length);
#define Initialize_Reporting_Expect(log_state) Initialize_Reporting_CMockExpect(__LINE__, log_state)
void Initialize_Reporting_CMockExpect(UNITY_LINE_TYPE cmock_line, BOOL log_state);
#define Update_Alerts_Alarms_Expect(detector, view) Update_Alerts_Alarms_CMockExpect(__LINE__, detector, view)
void Update_Alerts_Alarms_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE detector, BYTE view);
#define Calculate_New_Radiation_Alert_Expect(detector, view) Calculate_New_Radiation_Alert_CMockExpect(__LINE__, detector, view)
void Calculate_New_Radiation_Alert_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE detector, BYTE view);
#define Calculate_New_Radiation_Alarm_Expect(detector, view) Calculate_New_Radiation_Alarm_CMockExpect(__LINE__, detector, view)
void Calculate_New_Radiation_Alarm_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE detector, BYTE view);
#define Calculate_New_Integrate_Alert_Expect(detector, view) Calculate_New_Integrate_Alert_CMockExpect(__LINE__, detector, view)
void Calculate_New_Integrate_Alert_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE detector, BYTE view);
#define Calculate_New_Integrate_Alarm_Expect(detector, view) Calculate_New_Integrate_Alarm_CMockExpect(__LINE__, detector, view)
void Calculate_New_Integrate_Alarm_CMockExpect(UNITY_LINE_TYPE cmock_line, BYTE detector, BYTE view);
#define Check_Shutdown_Expect() Check_Shutdown_CMockExpect(__LINE__)
void Check_Shutdown_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Shutdown_Power_Expect() Shutdown_Power_CMockExpect(__LINE__)
void Shutdown_Power_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Software_Reset_Expect() Software_Reset_CMockExpect(__LINE__)
void Software_Reset_CMockExpect(UNITY_LINE_TYPE cmock_line);

#endif
