/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockCompiler.h"

static struct MockCompilerInstance
{
  unsigned char placeHolder;
} Mock;

extern jmp_buf AbortFrame;

void MockCompiler_Verify(void)
{
}

void MockCompiler_Init(void)
{
  MockCompiler_Destroy();
}

void MockCompiler_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

