/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSCANCODES_H
#define _MOCKSCANCODES_H

#include "ScanCodes.h"

void MockScanCodes_Init(void);
void MockScanCodes_Destroy(void);
void MockScanCodes_Verify(void);





#endif
