/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKUSB_HAL_PIC24_H
#define _MOCKUSB_HAL_PIC24_H

#include "usb_hal_pic24.h"

void Mockusb_hal_pic24_Init(void);
void Mockusb_hal_pic24_Destroy(void);
void Mockusb_hal_pic24_Verify(void);





#endif
