/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSTATICTEXT_H
#define _MOCKSTATICTEXT_H

#include "StaticText.h"

void MockStaticText_Init(void);
void MockStaticText_Destroy(void);
void MockStaticText_Verify(void);




#define StSetText_Expect(pSt, pText) StSetText_CMockExpect(__LINE__, pSt, pText)
void StSetText_CMockExpect(UNITY_LINE_TYPE cmock_line, STATICTEXT* pSt, XCHAR* pText);
#define StCreate_ExpectAndReturn(ID, left, top, right, bottom, state, pText, pScheme, cmock_retval) StCreate_CMockExpectAndReturn(__LINE__, ID, left, top, right, bottom, state, pText, pScheme, cmock_retval)
void StCreate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, XCHAR* pText, GOL_SCHEME* pScheme, STATICTEXT* cmock_to_return);
#define StTranslateMsg_ExpectAndReturn(pSt, pMsg, cmock_retval) StTranslateMsg_CMockExpectAndReturn(__LINE__, pSt, pMsg, cmock_retval)
void StTranslateMsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, STATICTEXT* pSt, GOL_MSG* pMsg, WORD cmock_to_return);
#define StDraw_ExpectAndReturn(pSt, cmock_retval) StDraw_CMockExpectAndReturn(__LINE__, pSt, cmock_retval)
void StDraw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, STATICTEXT* pSt, WORD cmock_to_return);

#endif
