/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockMessage_Box.h"

static struct MockMessage_BoxInstance
{
  unsigned char placeHolder;
} Mock;

extern jmp_buf AbortFrame;

void MockMessage_Box_Verify(void)
{
}

void MockMessage_Box_Init(void)
{
  MockMessage_Box_Destroy();
}

void MockMessage_Box_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

