/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockScanCodes.h"

static struct MockScanCodesInstance
{
  unsigned char placeHolder;
} Mock;

extern jmp_buf AbortFrame;

void MockScanCodes_Verify(void)
{
}

void MockScanCodes_Init(void)
{
  MockScanCodes_Destroy();
}

void MockScanCodes_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

