/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKIMAGEDECODERCONFIG_H
#define _MOCKIMAGEDECODERCONFIG_H

#include "ImageDecoderConfig.h"

void MockImageDecoderConfig_Init(void);
void MockImageDecoderConfig_Destroy(void);
void MockImageDecoderConfig_Verify(void);





#endif
