/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKUSB_CH9_H
#define _MOCKUSB_CH9_H

#include "usb_ch9.h"

void Mockusb_ch9_Init(void);
void Mockusb_ch9_Destroy(void);
void Mockusb_ch9_Verify(void);





#endif
