/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockEEPROM.h"

static struct MockEEPROMInstance
{
  unsigned char placeHolder;
} Mock;

extern jmp_buf AbortFrame;

void MockEEPROM_Verify(void)
{
}

void MockEEPROM_Init(void)
{
  MockEEPROM_Destroy();
}

void MockEEPROM_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

