/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockEditBox.h"

typedef struct _CMOCK_EbCreate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  EDITBOX* ReturnVal;
  WORD Expected_ID;
  SHORT Expected_left;
  SHORT Expected_top;
  SHORT Expected_right;
  SHORT Expected_bottom;
  WORD Expected_state;
  XCHAR* Expected_pText;
  WORD Expected_charMax;
  GOL_SCHEME* Expected_pScheme;

} CMOCK_EbCreate_CALL_INSTANCE;

typedef struct _CMOCK_EbSetText_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  EDITBOX* Expected_pEb;
  XCHAR* Expected_pText;

} CMOCK_EbSetText_CALL_INSTANCE;

typedef struct _CMOCK_EbAddChar_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  EDITBOX* Expected_pEb;
  XCHAR Expected_ch;

} CMOCK_EbAddChar_CALL_INSTANCE;

typedef struct _CMOCK_EbDeleteChar_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  EDITBOX* Expected_pEb;

} CMOCK_EbDeleteChar_CALL_INSTANCE;

typedef struct _CMOCK_EbTranslateMsg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD ReturnVal;
  EDITBOX* Expected_pEb;
  GOL_MSG* Expected_pMsg;

} CMOCK_EbTranslateMsg_CALL_INSTANCE;

typedef struct _CMOCK_EbMsgDefault_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD Expected_translatedMsg;
  EDITBOX* Expected_pEb;
  GOL_MSG* Expected_pMsg;

} CMOCK_EbMsgDefault_CALL_INSTANCE;

typedef struct _CMOCK_EbDraw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD ReturnVal;
  EDITBOX* Expected_pEb;

} CMOCK_EbDraw_CALL_INSTANCE;

static struct MockEditBoxInstance
{
  CMOCK_MEM_INDEX_TYPE EbCreate_CallInstance;
  CMOCK_MEM_INDEX_TYPE EbSetText_CallInstance;
  CMOCK_MEM_INDEX_TYPE EbAddChar_CallInstance;
  CMOCK_MEM_INDEX_TYPE EbDeleteChar_CallInstance;
  CMOCK_MEM_INDEX_TYPE EbTranslateMsg_CallInstance;
  CMOCK_MEM_INDEX_TYPE EbMsgDefault_CallInstance;
  CMOCK_MEM_INDEX_TYPE EbDraw_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockEditBox_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.EbCreate_CallInstance, cmock_line, "Function 'EbCreate' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.EbSetText_CallInstance, cmock_line, "Function 'EbSetText' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.EbAddChar_CallInstance, cmock_line, "Function 'EbAddChar' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.EbDeleteChar_CallInstance, cmock_line, "Function 'EbDeleteChar' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.EbTranslateMsg_CallInstance, cmock_line, "Function 'EbTranslateMsg' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.EbMsgDefault_CallInstance, cmock_line, "Function 'EbMsgDefault' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.EbDraw_CallInstance, cmock_line, "Function 'EbDraw' called less times than expected.");
}

void MockEditBox_Init(void)
{
  MockEditBox_Destroy();
}

void MockEditBox_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

EDITBOX* EbCreate(WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, XCHAR* pText, WORD charMax, GOL_SCHEME* pScheme)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_EbCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.EbCreate_CallInstance);
  Mock.EbCreate_CallInstance = CMock_Guts_MemNext(Mock.EbCreate_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'EbCreate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ID), (void*)(&ID), sizeof(WORD), cmock_line, "Function 'EbCreate' called with unexpected value for argument 'ID'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_left), (void*)(&left), sizeof(SHORT), cmock_line, "Function 'EbCreate' called with unexpected value for argument 'left'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_top), (void*)(&top), sizeof(SHORT), cmock_line, "Function 'EbCreate' called with unexpected value for argument 'top'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_right), (void*)(&right), sizeof(SHORT), cmock_line, "Function 'EbCreate' called with unexpected value for argument 'right'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bottom), (void*)(&bottom), sizeof(SHORT), cmock_line, "Function 'EbCreate' called with unexpected value for argument 'bottom'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(WORD), cmock_line, "Function 'EbCreate' called with unexpected value for argument 'state'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pText), (void*)(pText), sizeof(XCHAR), cmock_line, "Function 'EbCreate' called with unexpected value for argument 'pText'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_charMax), (void*)(&charMax), sizeof(WORD), cmock_line, "Function 'EbCreate' called with unexpected value for argument 'charMax'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pScheme), (void*)(pScheme), sizeof(GOL_SCHEME), cmock_line, "Function 'EbCreate' called with unexpected value for argument 'pScheme'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_EbCreate(CMOCK_EbCreate_CALL_INSTANCE* cmock_call_instance, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, XCHAR* pText, WORD charMax, GOL_SCHEME* pScheme)
{
  memcpy(&cmock_call_instance->Expected_ID, &ID, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_left, &left, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_top, &top, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_right, &right, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_bottom, &bottom, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(WORD));
  cmock_call_instance->Expected_pText = pText;
  memcpy(&cmock_call_instance->Expected_charMax, &charMax, sizeof(WORD));
  cmock_call_instance->Expected_pScheme = pScheme;
}

void EbCreate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, XCHAR* pText, WORD charMax, GOL_SCHEME* pScheme, EDITBOX* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_EbCreate_CALL_INSTANCE));
  CMOCK_EbCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.EbCreate_CallInstance = CMock_Guts_MemChain(Mock.EbCreate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_EbCreate(cmock_call_instance, ID, left, top, right, bottom, state, pText, charMax, pScheme);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void EbSetText(EDITBOX* pEb, XCHAR* pText)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_EbSetText_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbSetText_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.EbSetText_CallInstance);
  Mock.EbSetText_CallInstance = CMock_Guts_MemNext(Mock.EbSetText_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'EbSetText' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pEb), (void*)(pEb), sizeof(EDITBOX), cmock_line, "Function 'EbSetText' called with unexpected value for argument 'pEb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pText), (void*)(pText), sizeof(XCHAR), cmock_line, "Function 'EbSetText' called with unexpected value for argument 'pText'.");
  }
}

void CMockExpectParameters_EbSetText(CMOCK_EbSetText_CALL_INSTANCE* cmock_call_instance, EDITBOX* pEb, XCHAR* pText)
{
  cmock_call_instance->Expected_pEb = pEb;
  cmock_call_instance->Expected_pText = pText;
}

void EbSetText_CMockExpect(UNITY_LINE_TYPE cmock_line, EDITBOX* pEb, XCHAR* pText)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_EbSetText_CALL_INSTANCE));
  CMOCK_EbSetText_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbSetText_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.EbSetText_CallInstance = CMock_Guts_MemChain(Mock.EbSetText_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_EbSetText(cmock_call_instance, pEb, pText);
}

void EbAddChar(EDITBOX* pEb, XCHAR ch)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_EbAddChar_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbAddChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.EbAddChar_CallInstance);
  Mock.EbAddChar_CallInstance = CMock_Guts_MemNext(Mock.EbAddChar_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'EbAddChar' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pEb), (void*)(pEb), sizeof(EDITBOX), cmock_line, "Function 'EbAddChar' called with unexpected value for argument 'pEb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ch), (void*)(&ch), sizeof(XCHAR), cmock_line, "Function 'EbAddChar' called with unexpected value for argument 'ch'.");
  }
}

void CMockExpectParameters_EbAddChar(CMOCK_EbAddChar_CALL_INSTANCE* cmock_call_instance, EDITBOX* pEb, XCHAR ch)
{
  cmock_call_instance->Expected_pEb = pEb;
  memcpy(&cmock_call_instance->Expected_ch, &ch, sizeof(XCHAR));
}

void EbAddChar_CMockExpect(UNITY_LINE_TYPE cmock_line, EDITBOX* pEb, XCHAR ch)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_EbAddChar_CALL_INSTANCE));
  CMOCK_EbAddChar_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbAddChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.EbAddChar_CallInstance = CMock_Guts_MemChain(Mock.EbAddChar_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_EbAddChar(cmock_call_instance, pEb, ch);
}

void EbDeleteChar(EDITBOX* pEb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_EbDeleteChar_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbDeleteChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.EbDeleteChar_CallInstance);
  Mock.EbDeleteChar_CallInstance = CMock_Guts_MemNext(Mock.EbDeleteChar_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'EbDeleteChar' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pEb), (void*)(pEb), sizeof(EDITBOX), cmock_line, "Function 'EbDeleteChar' called with unexpected value for argument 'pEb'.");
  }
}

void CMockExpectParameters_EbDeleteChar(CMOCK_EbDeleteChar_CALL_INSTANCE* cmock_call_instance, EDITBOX* pEb)
{
  cmock_call_instance->Expected_pEb = pEb;
}

void EbDeleteChar_CMockExpect(UNITY_LINE_TYPE cmock_line, EDITBOX* pEb)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_EbDeleteChar_CALL_INSTANCE));
  CMOCK_EbDeleteChar_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbDeleteChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.EbDeleteChar_CallInstance = CMock_Guts_MemChain(Mock.EbDeleteChar_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_EbDeleteChar(cmock_call_instance, pEb);
}

WORD EbTranslateMsg(EDITBOX* pEb, GOL_MSG* pMsg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_EbTranslateMsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbTranslateMsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.EbTranslateMsg_CallInstance);
  Mock.EbTranslateMsg_CallInstance = CMock_Guts_MemNext(Mock.EbTranslateMsg_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'EbTranslateMsg' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pEb), (void*)(pEb), sizeof(EDITBOX), cmock_line, "Function 'EbTranslateMsg' called with unexpected value for argument 'pEb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMsg), (void*)(pMsg), sizeof(GOL_MSG), cmock_line, "Function 'EbTranslateMsg' called with unexpected value for argument 'pMsg'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_EbTranslateMsg(CMOCK_EbTranslateMsg_CALL_INSTANCE* cmock_call_instance, EDITBOX* pEb, GOL_MSG* pMsg)
{
  cmock_call_instance->Expected_pEb = pEb;
  cmock_call_instance->Expected_pMsg = pMsg;
}

void EbTranslateMsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, EDITBOX* pEb, GOL_MSG* pMsg, WORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_EbTranslateMsg_CALL_INSTANCE));
  CMOCK_EbTranslateMsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbTranslateMsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.EbTranslateMsg_CallInstance = CMock_Guts_MemChain(Mock.EbTranslateMsg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_EbTranslateMsg(cmock_call_instance, pEb, pMsg);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(WORD));
}

void EbMsgDefault(WORD translatedMsg, EDITBOX* pEb, GOL_MSG* pMsg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_EbMsgDefault_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbMsgDefault_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.EbMsgDefault_CallInstance);
  Mock.EbMsgDefault_CallInstance = CMock_Guts_MemNext(Mock.EbMsgDefault_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'EbMsgDefault' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_translatedMsg), (void*)(&translatedMsg), sizeof(WORD), cmock_line, "Function 'EbMsgDefault' called with unexpected value for argument 'translatedMsg'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pEb), (void*)(pEb), sizeof(EDITBOX), cmock_line, "Function 'EbMsgDefault' called with unexpected value for argument 'pEb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMsg), (void*)(pMsg), sizeof(GOL_MSG), cmock_line, "Function 'EbMsgDefault' called with unexpected value for argument 'pMsg'.");
  }
}

void CMockExpectParameters_EbMsgDefault(CMOCK_EbMsgDefault_CALL_INSTANCE* cmock_call_instance, WORD translatedMsg, EDITBOX* pEb, GOL_MSG* pMsg)
{
  memcpy(&cmock_call_instance->Expected_translatedMsg, &translatedMsg, sizeof(WORD));
  cmock_call_instance->Expected_pEb = pEb;
  cmock_call_instance->Expected_pMsg = pMsg;
}

void EbMsgDefault_CMockExpect(UNITY_LINE_TYPE cmock_line, WORD translatedMsg, EDITBOX* pEb, GOL_MSG* pMsg)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_EbMsgDefault_CALL_INSTANCE));
  CMOCK_EbMsgDefault_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbMsgDefault_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.EbMsgDefault_CallInstance = CMock_Guts_MemChain(Mock.EbMsgDefault_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_EbMsgDefault(cmock_call_instance, translatedMsg, pEb, pMsg);
}

WORD EbDraw(EDITBOX* pEb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_EbDraw_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbDraw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.EbDraw_CallInstance);
  Mock.EbDraw_CallInstance = CMock_Guts_MemNext(Mock.EbDraw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'EbDraw' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pEb), (void*)(pEb), sizeof(EDITBOX), cmock_line, "Function 'EbDraw' called with unexpected value for argument 'pEb'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_EbDraw(CMOCK_EbDraw_CALL_INSTANCE* cmock_call_instance, EDITBOX* pEb)
{
  cmock_call_instance->Expected_pEb = pEb;
}

void EbDraw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, EDITBOX* pEb, WORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_EbDraw_CALL_INSTANCE));
  CMOCK_EbDraw_CALL_INSTANCE* cmock_call_instance = (CMOCK_EbDraw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.EbDraw_CallInstance = CMock_Guts_MemChain(Mock.EbDraw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_EbDraw(cmock_call_instance, pEb);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(WORD));
}

