/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockusb_host_hid.h"

typedef struct _CMOCK_USBHostHIDDeviceDetect_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_deviceAddress;

} CMOCK_USBHostHIDDeviceDetect_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHIDDeviceStatus_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;

} CMOCK_USBHostHIDDeviceStatus_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHIDResetDevice_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;

} CMOCK_USBHostHIDResetDevice_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHIDTasks_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USBHostHIDTasks_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHIDTerminateTransfer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE Expected_direction;
  BYTE Expected_interfaceNum;

} CMOCK_USBHostHIDTerminateTransfer_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHIDTransfer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE Expected_direction;
  BYTE Expected_interfaceNum;
  WORD Expected_reportid;
  WORD Expected_size;
  BYTE* Expected_data;

} CMOCK_USBHostHIDTransfer_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHIDTransferIsComplete_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE* Expected_errorCode;
  BYTE* Expected_byteCount;

} CMOCK_USBHostHIDTransferIsComplete_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHID_ApiFindBit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  WORD Expected_usagePage;
  WORD Expected_usage;
  HIDReportTypeEnum Expected_type;
  BYTE* Expected_Report_ID;
  BYTE* Expected_Report_Length;
  BYTE* Expected_Start_Bit;

} CMOCK_USBHostHID_ApiFindBit_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHID_ApiFindValue_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  WORD Expected_usagePage;
  WORD Expected_usage;
  HIDReportTypeEnum Expected_type;
  BYTE* Expected_Report_ID;
  BYTE* Expected_Report_Length;
  BYTE* Expected_Start_Bit;
  BYTE* Expected_Bit_Length;

} CMOCK_USBHostHID_ApiFindValue_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHID_ApiGetCurrentInterfaceNum_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;

} CMOCK_USBHostHID_ApiGetCurrentInterfaceNum_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHID_ApiImportData_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE* Expected_report;
  WORD Expected_reportLength;
  HID_USER_DATA_SIZE* Expected_buffer;
  HID_DATA_DETAILS* Expected_pDataDetails;

} CMOCK_USBHostHID_ApiImportData_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHIDInitialize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_address;
  DWORD Expected_flags;
  BYTE Expected_clientDriverID;

} CMOCK_USBHostHIDInitialize_CALL_INSTANCE;

typedef struct _CMOCK_USBHostHIDEventHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_address;
  USB_EVENT Expected_event;
  void* Expected_data;
  DWORD Expected_size;

} CMOCK_USBHostHIDEventHandler_CALL_INSTANCE;

static struct Mockusb_host_hidInstance
{
  CMOCK_MEM_INDEX_TYPE USBHostHIDDeviceDetect_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHIDDeviceStatus_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHIDResetDevice_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHIDTasks_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHIDTerminateTransfer_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHIDTransfer_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHIDTransferIsComplete_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHID_ApiFindBit_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHID_ApiFindValue_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHID_ApiGetCurrentInterfaceNum_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHID_ApiImportData_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHIDInitialize_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostHIDEventHandler_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockusb_host_hid_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHIDDeviceDetect_CallInstance, cmock_line, "Function 'USBHostHIDDeviceDetect' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHIDDeviceStatus_CallInstance, cmock_line, "Function 'USBHostHIDDeviceStatus' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHIDResetDevice_CallInstance, cmock_line, "Function 'USBHostHIDResetDevice' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHIDTasks_CallInstance, cmock_line, "Function 'USBHostHIDTasks' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHIDTerminateTransfer_CallInstance, cmock_line, "Function 'USBHostHIDTerminateTransfer' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHIDTransfer_CallInstance, cmock_line, "Function 'USBHostHIDTransfer' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHIDTransferIsComplete_CallInstance, cmock_line, "Function 'USBHostHIDTransferIsComplete' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHID_ApiFindBit_CallInstance, cmock_line, "Function 'USBHostHID_ApiFindBit' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHID_ApiFindValue_CallInstance, cmock_line, "Function 'USBHostHID_ApiFindValue' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHID_ApiGetCurrentInterfaceNum_CallInstance, cmock_line, "Function 'USBHostHID_ApiGetCurrentInterfaceNum' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHID_ApiImportData_CallInstance, cmock_line, "Function 'USBHostHID_ApiImportData' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHIDInitialize_CallInstance, cmock_line, "Function 'USBHostHIDInitialize' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostHIDEventHandler_CallInstance, cmock_line, "Function 'USBHostHIDEventHandler' called less times than expected.");
}

void Mockusb_host_hid_Init(void)
{
  Mockusb_host_hid_Destroy();
}

void Mockusb_host_hid_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

BOOL USBHostHIDDeviceDetect(BYTE deviceAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHIDDeviceDetect_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDDeviceDetect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHIDDeviceDetect_CallInstance);
  Mock.USBHostHIDDeviceDetect_CallInstance = CMock_Guts_MemNext(Mock.USBHostHIDDeviceDetect_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHIDDeviceDetect' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostHIDDeviceDetect' called with unexpected value for argument 'deviceAddress'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostHIDDeviceDetect(CMOCK_USBHostHIDDeviceDetect_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
}

void USBHostHIDDeviceDetect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHIDDeviceDetect_CALL_INSTANCE));
  CMOCK_USBHostHIDDeviceDetect_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDDeviceDetect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHIDDeviceDetect_CallInstance = CMock_Guts_MemChain(Mock.USBHostHIDDeviceDetect_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostHIDDeviceDetect(cmock_call_instance, deviceAddress);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BYTE USBHostHIDDeviceStatus(BYTE deviceAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHIDDeviceStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDDeviceStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHIDDeviceStatus_CallInstance);
  Mock.USBHostHIDDeviceStatus_CallInstance = CMock_Guts_MemNext(Mock.USBHostHIDDeviceStatus_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHIDDeviceStatus' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostHIDDeviceStatus' called with unexpected value for argument 'deviceAddress'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostHIDDeviceStatus(CMOCK_USBHostHIDDeviceStatus_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
}

void USBHostHIDDeviceStatus_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHIDDeviceStatus_CALL_INSTANCE));
  CMOCK_USBHostHIDDeviceStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDDeviceStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHIDDeviceStatus_CallInstance = CMock_Guts_MemChain(Mock.USBHostHIDDeviceStatus_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostHIDDeviceStatus(cmock_call_instance, deviceAddress);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BYTE USBHostHIDResetDevice(BYTE deviceAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHIDResetDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDResetDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHIDResetDevice_CallInstance);
  Mock.USBHostHIDResetDevice_CallInstance = CMock_Guts_MemNext(Mock.USBHostHIDResetDevice_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHIDResetDevice' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostHIDResetDevice' called with unexpected value for argument 'deviceAddress'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostHIDResetDevice(CMOCK_USBHostHIDResetDevice_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
}

void USBHostHIDResetDevice_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHIDResetDevice_CALL_INSTANCE));
  CMOCK_USBHostHIDResetDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDResetDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHIDResetDevice_CallInstance = CMock_Guts_MemChain(Mock.USBHostHIDResetDevice_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostHIDResetDevice(cmock_call_instance, deviceAddress);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

void USBHostHIDTasks(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHIDTasks_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDTasks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHIDTasks_CallInstance);
  Mock.USBHostHIDTasks_CallInstance = CMock_Guts_MemNext(Mock.USBHostHIDTasks_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHIDTasks' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void USBHostHIDTasks_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHIDTasks_CALL_INSTANCE));
  CMOCK_USBHostHIDTasks_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDTasks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHIDTasks_CallInstance = CMock_Guts_MemChain(Mock.USBHostHIDTasks_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

BYTE USBHostHIDTerminateTransfer(BYTE deviceAddress, BYTE direction, BYTE interfaceNum)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHIDTerminateTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDTerminateTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHIDTerminateTransfer_CallInstance);
  Mock.USBHostHIDTerminateTransfer_CallInstance = CMock_Guts_MemNext(Mock.USBHostHIDTerminateTransfer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHIDTerminateTransfer' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostHIDTerminateTransfer' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_direction), (void*)(&direction), sizeof(BYTE), cmock_line, "Function 'USBHostHIDTerminateTransfer' called with unexpected value for argument 'direction'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_interfaceNum), (void*)(&interfaceNum), sizeof(BYTE), cmock_line, "Function 'USBHostHIDTerminateTransfer' called with unexpected value for argument 'interfaceNum'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostHIDTerminateTransfer(CMOCK_USBHostHIDTerminateTransfer_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE direction, BYTE interfaceNum)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_direction, &direction, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_interfaceNum, &interfaceNum, sizeof(BYTE));
}

void USBHostHIDTerminateTransfer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE direction, BYTE interfaceNum, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHIDTerminateTransfer_CALL_INSTANCE));
  CMOCK_USBHostHIDTerminateTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDTerminateTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHIDTerminateTransfer_CallInstance = CMock_Guts_MemChain(Mock.USBHostHIDTerminateTransfer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostHIDTerminateTransfer(cmock_call_instance, deviceAddress, direction, interfaceNum);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BYTE USBHostHIDTransfer(BYTE deviceAddress, BYTE direction, BYTE interfaceNum, WORD reportid, WORD size, BYTE* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHIDTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHIDTransfer_CallInstance);
  Mock.USBHostHIDTransfer_CallInstance = CMock_Guts_MemNext(Mock.USBHostHIDTransfer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHIDTransfer' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostHIDTransfer' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_direction), (void*)(&direction), sizeof(BYTE), cmock_line, "Function 'USBHostHIDTransfer' called with unexpected value for argument 'direction'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_interfaceNum), (void*)(&interfaceNum), sizeof(BYTE), cmock_line, "Function 'USBHostHIDTransfer' called with unexpected value for argument 'interfaceNum'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_reportid), (void*)(&reportid), sizeof(WORD), cmock_line, "Function 'USBHostHIDTransfer' called with unexpected value for argument 'reportid'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(WORD), cmock_line, "Function 'USBHostHIDTransfer' called with unexpected value for argument 'size'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(BYTE), cmock_line, "Function 'USBHostHIDTransfer' called with unexpected value for argument 'data'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostHIDTransfer(CMOCK_USBHostHIDTransfer_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE direction, BYTE interfaceNum, WORD reportid, WORD size, BYTE* data)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_direction, &direction, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_interfaceNum, &interfaceNum, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_reportid, &reportid, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(WORD));
  cmock_call_instance->Expected_data = data;
}

void USBHostHIDTransfer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE direction, BYTE interfaceNum, WORD reportid, WORD size, BYTE* data, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHIDTransfer_CALL_INSTANCE));
  CMOCK_USBHostHIDTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHIDTransfer_CallInstance = CMock_Guts_MemChain(Mock.USBHostHIDTransfer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostHIDTransfer(cmock_call_instance, deviceAddress, direction, interfaceNum, reportid, size, data);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BOOL USBHostHIDTransferIsComplete(BYTE deviceAddress, BYTE* errorCode, BYTE* byteCount)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHIDTransferIsComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDTransferIsComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHIDTransferIsComplete_CallInstance);
  Mock.USBHostHIDTransferIsComplete_CallInstance = CMock_Guts_MemNext(Mock.USBHostHIDTransferIsComplete_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHIDTransferIsComplete' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostHIDTransferIsComplete' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_errorCode), (void*)(errorCode), sizeof(BYTE), cmock_line, "Function 'USBHostHIDTransferIsComplete' called with unexpected value for argument 'errorCode'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_byteCount), (void*)(byteCount), sizeof(BYTE), cmock_line, "Function 'USBHostHIDTransferIsComplete' called with unexpected value for argument 'byteCount'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostHIDTransferIsComplete(CMOCK_USBHostHIDTransferIsComplete_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE* errorCode, BYTE* byteCount)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  cmock_call_instance->Expected_errorCode = errorCode;
  cmock_call_instance->Expected_byteCount = byteCount;
}

void USBHostHIDTransferIsComplete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE* errorCode, BYTE* byteCount, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHIDTransferIsComplete_CALL_INSTANCE));
  CMOCK_USBHostHIDTransferIsComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDTransferIsComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHIDTransferIsComplete_CallInstance = CMock_Guts_MemChain(Mock.USBHostHIDTransferIsComplete_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostHIDTransferIsComplete(cmock_call_instance, deviceAddress, errorCode, byteCount);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BOOL USBHostHID_ApiFindBit(WORD usagePage, WORD usage, HIDReportTypeEnum type, BYTE* Report_ID, BYTE* Report_Length, BYTE* Start_Bit)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHID_ApiFindBit_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHID_ApiFindBit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHID_ApiFindBit_CallInstance);
  Mock.USBHostHID_ApiFindBit_CallInstance = CMock_Guts_MemNext(Mock.USBHostHID_ApiFindBit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHID_ApiFindBit' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_usagePage), (void*)(&usagePage), sizeof(WORD), cmock_line, "Function 'USBHostHID_ApiFindBit' called with unexpected value for argument 'usagePage'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_usage), (void*)(&usage), sizeof(WORD), cmock_line, "Function 'USBHostHID_ApiFindBit' called with unexpected value for argument 'usage'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_type), (void*)(&type), sizeof(HIDReportTypeEnum), cmock_line, "Function 'USBHostHID_ApiFindBit' called with unexpected value for argument 'type'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_Report_ID), (void*)(Report_ID), sizeof(BYTE), cmock_line, "Function 'USBHostHID_ApiFindBit' called with unexpected value for argument 'Report_ID'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_Report_Length), (void*)(Report_Length), sizeof(BYTE), cmock_line, "Function 'USBHostHID_ApiFindBit' called with unexpected value for argument 'Report_Length'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_Start_Bit), (void*)(Start_Bit), sizeof(BYTE), cmock_line, "Function 'USBHostHID_ApiFindBit' called with unexpected value for argument 'Start_Bit'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostHID_ApiFindBit(CMOCK_USBHostHID_ApiFindBit_CALL_INSTANCE* cmock_call_instance, WORD usagePage, WORD usage, HIDReportTypeEnum type, BYTE* Report_ID, BYTE* Report_Length, BYTE* Start_Bit)
{
  memcpy(&cmock_call_instance->Expected_usagePage, &usagePage, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_usage, &usage, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_type, &type, sizeof(HIDReportTypeEnum));
  cmock_call_instance->Expected_Report_ID = Report_ID;
  cmock_call_instance->Expected_Report_Length = Report_Length;
  cmock_call_instance->Expected_Start_Bit = Start_Bit;
}

void USBHostHID_ApiFindBit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD usagePage, WORD usage, HIDReportTypeEnum type, BYTE* Report_ID, BYTE* Report_Length, BYTE* Start_Bit, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHID_ApiFindBit_CALL_INSTANCE));
  CMOCK_USBHostHID_ApiFindBit_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHID_ApiFindBit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHID_ApiFindBit_CallInstance = CMock_Guts_MemChain(Mock.USBHostHID_ApiFindBit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostHID_ApiFindBit(cmock_call_instance, usagePage, usage, type, Report_ID, Report_Length, Start_Bit);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BOOL USBHostHID_ApiFindValue(WORD usagePage, WORD usage, HIDReportTypeEnum type, BYTE* Report_ID, BYTE* Report_Length, BYTE* Start_Bit, BYTE* Bit_Length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHID_ApiFindValue_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHID_ApiFindValue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHID_ApiFindValue_CallInstance);
  Mock.USBHostHID_ApiFindValue_CallInstance = CMock_Guts_MemNext(Mock.USBHostHID_ApiFindValue_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHID_ApiFindValue' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_usagePage), (void*)(&usagePage), sizeof(WORD), cmock_line, "Function 'USBHostHID_ApiFindValue' called with unexpected value for argument 'usagePage'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_usage), (void*)(&usage), sizeof(WORD), cmock_line, "Function 'USBHostHID_ApiFindValue' called with unexpected value for argument 'usage'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_type), (void*)(&type), sizeof(HIDReportTypeEnum), cmock_line, "Function 'USBHostHID_ApiFindValue' called with unexpected value for argument 'type'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_Report_ID), (void*)(Report_ID), sizeof(BYTE), cmock_line, "Function 'USBHostHID_ApiFindValue' called with unexpected value for argument 'Report_ID'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_Report_Length), (void*)(Report_Length), sizeof(BYTE), cmock_line, "Function 'USBHostHID_ApiFindValue' called with unexpected value for argument 'Report_Length'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_Start_Bit), (void*)(Start_Bit), sizeof(BYTE), cmock_line, "Function 'USBHostHID_ApiFindValue' called with unexpected value for argument 'Start_Bit'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_Bit_Length), (void*)(Bit_Length), sizeof(BYTE), cmock_line, "Function 'USBHostHID_ApiFindValue' called with unexpected value for argument 'Bit_Length'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostHID_ApiFindValue(CMOCK_USBHostHID_ApiFindValue_CALL_INSTANCE* cmock_call_instance, WORD usagePage, WORD usage, HIDReportTypeEnum type, BYTE* Report_ID, BYTE* Report_Length, BYTE* Start_Bit, BYTE* Bit_Length)
{
  memcpy(&cmock_call_instance->Expected_usagePage, &usagePage, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_usage, &usage, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_type, &type, sizeof(HIDReportTypeEnum));
  cmock_call_instance->Expected_Report_ID = Report_ID;
  cmock_call_instance->Expected_Report_Length = Report_Length;
  cmock_call_instance->Expected_Start_Bit = Start_Bit;
  cmock_call_instance->Expected_Bit_Length = Bit_Length;
}

void USBHostHID_ApiFindValue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD usagePage, WORD usage, HIDReportTypeEnum type, BYTE* Report_ID, BYTE* Report_Length, BYTE* Start_Bit, BYTE* Bit_Length, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHID_ApiFindValue_CALL_INSTANCE));
  CMOCK_USBHostHID_ApiFindValue_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHID_ApiFindValue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHID_ApiFindValue_CallInstance = CMock_Guts_MemChain(Mock.USBHostHID_ApiFindValue_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostHID_ApiFindValue(cmock_call_instance, usagePage, usage, type, Report_ID, Report_Length, Start_Bit, Bit_Length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BYTE USBHostHID_ApiGetCurrentInterfaceNum(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHID_ApiGetCurrentInterfaceNum_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHID_ApiGetCurrentInterfaceNum_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHID_ApiGetCurrentInterfaceNum_CallInstance);
  Mock.USBHostHID_ApiGetCurrentInterfaceNum_CallInstance = CMock_Guts_MemNext(Mock.USBHostHID_ApiGetCurrentInterfaceNum_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHID_ApiGetCurrentInterfaceNum' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void USBHostHID_ApiGetCurrentInterfaceNum_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHID_ApiGetCurrentInterfaceNum_CALL_INSTANCE));
  CMOCK_USBHostHID_ApiGetCurrentInterfaceNum_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHID_ApiGetCurrentInterfaceNum_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHID_ApiGetCurrentInterfaceNum_CallInstance = CMock_Guts_MemChain(Mock.USBHostHID_ApiGetCurrentInterfaceNum_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BOOL USBHostHID_ApiImportData(BYTE* report, WORD reportLength, HID_USER_DATA_SIZE* buffer, HID_DATA_DETAILS* pDataDetails)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHID_ApiImportData_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHID_ApiImportData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHID_ApiImportData_CallInstance);
  Mock.USBHostHID_ApiImportData_CallInstance = CMock_Guts_MemNext(Mock.USBHostHID_ApiImportData_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHID_ApiImportData' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_report), (void*)(report), sizeof(BYTE), cmock_line, "Function 'USBHostHID_ApiImportData' called with unexpected value for argument 'report'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_reportLength), (void*)(&reportLength), sizeof(WORD), cmock_line, "Function 'USBHostHID_ApiImportData' called with unexpected value for argument 'reportLength'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_buffer), (void*)(buffer), sizeof(HID_USER_DATA_SIZE), cmock_line, "Function 'USBHostHID_ApiImportData' called with unexpected value for argument 'buffer'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pDataDetails), (void*)(pDataDetails), sizeof(HID_DATA_DETAILS), cmock_line, "Function 'USBHostHID_ApiImportData' called with unexpected value for argument 'pDataDetails'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostHID_ApiImportData(CMOCK_USBHostHID_ApiImportData_CALL_INSTANCE* cmock_call_instance, BYTE* report, WORD reportLength, HID_USER_DATA_SIZE* buffer, HID_DATA_DETAILS* pDataDetails)
{
  cmock_call_instance->Expected_report = report;
  memcpy(&cmock_call_instance->Expected_reportLength, &reportLength, sizeof(WORD));
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_pDataDetails = pDataDetails;
}

void USBHostHID_ApiImportData_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE* report, WORD reportLength, HID_USER_DATA_SIZE* buffer, HID_DATA_DETAILS* pDataDetails, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHID_ApiImportData_CALL_INSTANCE));
  CMOCK_USBHostHID_ApiImportData_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHID_ApiImportData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHID_ApiImportData_CallInstance = CMock_Guts_MemChain(Mock.USBHostHID_ApiImportData_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostHID_ApiImportData(cmock_call_instance, report, reportLength, buffer, pDataDetails);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BOOL USBHostHIDInitialize(BYTE address, DWORD flags, BYTE clientDriverID)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHIDInitialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDInitialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHIDInitialize_CallInstance);
  Mock.USBHostHIDInitialize_CallInstance = CMock_Guts_MemNext(Mock.USBHostHIDInitialize_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHIDInitialize' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_address), (void*)(&address), sizeof(BYTE), cmock_line, "Function 'USBHostHIDInitialize' called with unexpected value for argument 'address'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_flags), (void*)(&flags), sizeof(DWORD), cmock_line, "Function 'USBHostHIDInitialize' called with unexpected value for argument 'flags'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_clientDriverID), (void*)(&clientDriverID), sizeof(BYTE), cmock_line, "Function 'USBHostHIDInitialize' called with unexpected value for argument 'clientDriverID'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostHIDInitialize(CMOCK_USBHostHIDInitialize_CALL_INSTANCE* cmock_call_instance, BYTE address, DWORD flags, BYTE clientDriverID)
{
  memcpy(&cmock_call_instance->Expected_address, &address, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_flags, &flags, sizeof(DWORD));
  memcpy(&cmock_call_instance->Expected_clientDriverID, &clientDriverID, sizeof(BYTE));
}

void USBHostHIDInitialize_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE address, DWORD flags, BYTE clientDriverID, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHIDInitialize_CALL_INSTANCE));
  CMOCK_USBHostHIDInitialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDInitialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHIDInitialize_CallInstance = CMock_Guts_MemChain(Mock.USBHostHIDInitialize_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostHIDInitialize(cmock_call_instance, address, flags, clientDriverID);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BOOL USBHostHIDEventHandler(BYTE address, USB_EVENT event, void* data, DWORD size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostHIDEventHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDEventHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostHIDEventHandler_CallInstance);
  Mock.USBHostHIDEventHandler_CallInstance = CMock_Guts_MemNext(Mock.USBHostHIDEventHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostHIDEventHandler' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_address), (void*)(&address), sizeof(BYTE), cmock_line, "Function 'USBHostHIDEventHandler' called with unexpected value for argument 'address'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_event), (void*)(&event), sizeof(USB_EVENT), cmock_line, "Function 'USBHostHIDEventHandler' called with unexpected value for argument 'event'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_data, data, cmock_line, "Function 'USBHostHIDEventHandler' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(DWORD), cmock_line, "Function 'USBHostHIDEventHandler' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostHIDEventHandler(CMOCK_USBHostHIDEventHandler_CALL_INSTANCE* cmock_call_instance, BYTE address, USB_EVENT event, void* data, DWORD size)
{
  memcpy(&cmock_call_instance->Expected_address, &address, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_event, &event, sizeof(USB_EVENT));
  cmock_call_instance->Expected_data = data;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(DWORD));
}

void USBHostHIDEventHandler_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE address, USB_EVENT event, void* data, DWORD size, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostHIDEventHandler_CALL_INSTANCE));
  CMOCK_USBHostHIDEventHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostHIDEventHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostHIDEventHandler_CallInstance = CMock_Guts_MemChain(Mock.USBHostHIDEventHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostHIDEventHandler(cmock_call_instance, address, event, data, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

