/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockWindow.h"

typedef struct _CMOCK_WndCreate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WINDOW* ReturnVal;
  WORD Expected_ID;
  SHORT Expected_left;
  SHORT Expected_top;
  SHORT Expected_right;
  SHORT Expected_bottom;
  WORD Expected_state;
  void* Expected_pBitmap;
  XCHAR* Expected_pText;
  GOL_SCHEME* Expected_pScheme;

} CMOCK_WndCreate_CALL_INSTANCE;

typedef struct _CMOCK_WndSetText_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WINDOW* Expected_pW;
  XCHAR* Expected_pText;

} CMOCK_WndSetText_CALL_INSTANCE;

typedef struct _CMOCK_WndTranslateMsg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD ReturnVal;
  WINDOW* Expected_pW;
  GOL_MSG* Expected_pMsg;

} CMOCK_WndTranslateMsg_CALL_INSTANCE;

typedef struct _CMOCK_WndDraw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD ReturnVal;
  WINDOW* Expected_pW;

} CMOCK_WndDraw_CALL_INSTANCE;

static struct MockWindowInstance
{
  CMOCK_MEM_INDEX_TYPE WndCreate_CallInstance;
  CMOCK_MEM_INDEX_TYPE WndSetText_CallInstance;
  CMOCK_MEM_INDEX_TYPE WndTranslateMsg_CallInstance;
  CMOCK_MEM_INDEX_TYPE WndDraw_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockWindow_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.WndCreate_CallInstance, cmock_line, "Function 'WndCreate' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.WndSetText_CallInstance, cmock_line, "Function 'WndSetText' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.WndTranslateMsg_CallInstance, cmock_line, "Function 'WndTranslateMsg' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.WndDraw_CallInstance, cmock_line, "Function 'WndDraw' called less times than expected.");
}

void MockWindow_Init(void)
{
  MockWindow_Destroy();
}

void MockWindow_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

WINDOW* WndCreate(WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, void* pBitmap, XCHAR* pText, GOL_SCHEME* pScheme)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_WndCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_WndCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.WndCreate_CallInstance);
  Mock.WndCreate_CallInstance = CMock_Guts_MemNext(Mock.WndCreate_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'WndCreate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ID), (void*)(&ID), sizeof(WORD), cmock_line, "Function 'WndCreate' called with unexpected value for argument 'ID'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_left), (void*)(&left), sizeof(SHORT), cmock_line, "Function 'WndCreate' called with unexpected value for argument 'left'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_top), (void*)(&top), sizeof(SHORT), cmock_line, "Function 'WndCreate' called with unexpected value for argument 'top'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_right), (void*)(&right), sizeof(SHORT), cmock_line, "Function 'WndCreate' called with unexpected value for argument 'right'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bottom), (void*)(&bottom), sizeof(SHORT), cmock_line, "Function 'WndCreate' called with unexpected value for argument 'bottom'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(WORD), cmock_line, "Function 'WndCreate' called with unexpected value for argument 'state'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_pBitmap, pBitmap, cmock_line, "Function 'WndCreate' called with unexpected value for argument 'pBitmap'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pText), (void*)(pText), sizeof(XCHAR), cmock_line, "Function 'WndCreate' called with unexpected value for argument 'pText'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pScheme), (void*)(pScheme), sizeof(GOL_SCHEME), cmock_line, "Function 'WndCreate' called with unexpected value for argument 'pScheme'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_WndCreate(CMOCK_WndCreate_CALL_INSTANCE* cmock_call_instance, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, void* pBitmap, XCHAR* pText, GOL_SCHEME* pScheme)
{
  memcpy(&cmock_call_instance->Expected_ID, &ID, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_left, &left, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_top, &top, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_right, &right, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_bottom, &bottom, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(WORD));
  cmock_call_instance->Expected_pBitmap = pBitmap;
  cmock_call_instance->Expected_pText = pText;
  cmock_call_instance->Expected_pScheme = pScheme;
}

void WndCreate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, void* pBitmap, XCHAR* pText, GOL_SCHEME* pScheme, WINDOW* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_WndCreate_CALL_INSTANCE));
  CMOCK_WndCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_WndCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.WndCreate_CallInstance = CMock_Guts_MemChain(Mock.WndCreate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_WndCreate(cmock_call_instance, ID, left, top, right, bottom, state, pBitmap, pText, pScheme);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void WndSetText(WINDOW* pW, XCHAR* pText)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_WndSetText_CALL_INSTANCE* cmock_call_instance = (CMOCK_WndSetText_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.WndSetText_CallInstance);
  Mock.WndSetText_CallInstance = CMock_Guts_MemNext(Mock.WndSetText_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'WndSetText' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pW), (void*)(pW), sizeof(WINDOW), cmock_line, "Function 'WndSetText' called with unexpected value for argument 'pW'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pText), (void*)(pText), sizeof(XCHAR), cmock_line, "Function 'WndSetText' called with unexpected value for argument 'pText'.");
  }
}

void CMockExpectParameters_WndSetText(CMOCK_WndSetText_CALL_INSTANCE* cmock_call_instance, WINDOW* pW, XCHAR* pText)
{
  cmock_call_instance->Expected_pW = pW;
  cmock_call_instance->Expected_pText = pText;
}

void WndSetText_CMockExpect(UNITY_LINE_TYPE cmock_line, WINDOW* pW, XCHAR* pText)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_WndSetText_CALL_INSTANCE));
  CMOCK_WndSetText_CALL_INSTANCE* cmock_call_instance = (CMOCK_WndSetText_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.WndSetText_CallInstance = CMock_Guts_MemChain(Mock.WndSetText_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_WndSetText(cmock_call_instance, pW, pText);
}

WORD WndTranslateMsg(WINDOW* pW, GOL_MSG* pMsg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_WndTranslateMsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_WndTranslateMsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.WndTranslateMsg_CallInstance);
  Mock.WndTranslateMsg_CallInstance = CMock_Guts_MemNext(Mock.WndTranslateMsg_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'WndTranslateMsg' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pW), (void*)(pW), sizeof(WINDOW), cmock_line, "Function 'WndTranslateMsg' called with unexpected value for argument 'pW'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMsg), (void*)(pMsg), sizeof(GOL_MSG), cmock_line, "Function 'WndTranslateMsg' called with unexpected value for argument 'pMsg'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_WndTranslateMsg(CMOCK_WndTranslateMsg_CALL_INSTANCE* cmock_call_instance, WINDOW* pW, GOL_MSG* pMsg)
{
  cmock_call_instance->Expected_pW = pW;
  cmock_call_instance->Expected_pMsg = pMsg;
}

void WndTranslateMsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WINDOW* pW, GOL_MSG* pMsg, WORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_WndTranslateMsg_CALL_INSTANCE));
  CMOCK_WndTranslateMsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_WndTranslateMsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.WndTranslateMsg_CallInstance = CMock_Guts_MemChain(Mock.WndTranslateMsg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_WndTranslateMsg(cmock_call_instance, pW, pMsg);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(WORD));
}

WORD WndDraw(WINDOW* pW)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_WndDraw_CALL_INSTANCE* cmock_call_instance = (CMOCK_WndDraw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.WndDraw_CallInstance);
  Mock.WndDraw_CallInstance = CMock_Guts_MemNext(Mock.WndDraw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'WndDraw' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pW), (void*)(pW), sizeof(WINDOW), cmock_line, "Function 'WndDraw' called with unexpected value for argument 'pW'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_WndDraw(CMOCK_WndDraw_CALL_INSTANCE* cmock_call_instance, WINDOW* pW)
{
  cmock_call_instance->Expected_pW = pW;
}

void WndDraw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WINDOW* pW, WORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_WndDraw_CALL_INSTANCE));
  CMOCK_WndDraw_CALL_INSTANCE* cmock_call_instance = (CMOCK_WndDraw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.WndDraw_CallInstance = CMock_Guts_MemChain(Mock.WndDraw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_WndDraw(cmock_call_instance, pW);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(WORD));
}

