/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSLIDER_H
#define _MOCKSLIDER_H

#include "Slider.h"

void MockSlider_Init(void);
void MockSlider_Destroy(void);
void MockSlider_Verify(void);




#define SldSetRange_Expect(pSld, newRange) SldSetRange_CMockExpect(__LINE__, pSld, newRange)
void SldSetRange_CMockExpect(UNITY_LINE_TYPE cmock_line, SLIDER* pSld, SHORT newRange);
#define SldSetPage_Expect(pSld, newPage) SldSetPage_CMockExpect(__LINE__, pSld, newPage)
void SldSetPage_CMockExpect(UNITY_LINE_TYPE cmock_line, SLIDER* pSld, WORD newPage);
#define SldSetPos_Expect(pSld, newPos) SldSetPos_CMockExpect(__LINE__, pSld, newPos)
void SldSetPos_CMockExpect(UNITY_LINE_TYPE cmock_line, SLIDER* pSld, SHORT newPos);
#define SldCreate_ExpectAndReturn(ID, left, top, right, bottom, state, range, page, pos, pScheme, cmock_retval) SldCreate_CMockExpectAndReturn(__LINE__, ID, left, top, right, bottom, state, range, page, pos, pScheme, cmock_retval)
void SldCreate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, WORD range, WORD page, WORD pos, GOL_SCHEME* pScheme, SLIDER* cmock_to_return);
#define SldMsgDefault_Expect(translatedMsg, pSld, pMsg) SldMsgDefault_CMockExpect(__LINE__, translatedMsg, pSld, pMsg)
void SldMsgDefault_CMockExpect(UNITY_LINE_TYPE cmock_line, WORD translatedMsg, SLIDER* pSld, GOL_MSG* pMsg);
#define SldTranslateMsg_ExpectAndReturn(pSld, pMsg, cmock_retval) SldTranslateMsg_CMockExpectAndReturn(__LINE__, pSld, pMsg, cmock_retval)
void SldTranslateMsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SLIDER* pSld, GOL_MSG* pMsg, WORD cmock_to_return);
#define SldDraw_ExpectAndReturn(pSld, cmock_retval) SldDraw_CMockExpectAndReturn(__LINE__, pSld, cmock_retval)
void SldDraw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SLIDER* pSld, WORD cmock_to_return);

#endif
