/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockGroupBox.h"

typedef struct _CMOCK_GbSetText_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GROUPBOX* Expected_pGb;
  XCHAR* Expected_pText;

} CMOCK_GbSetText_CALL_INSTANCE;

typedef struct _CMOCK_GbTranslateMsg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD ReturnVal;
  GROUPBOX* Expected_pGb;
  GOL_MSG* Expected_pMsg;

} CMOCK_GbTranslateMsg_CALL_INSTANCE;

typedef struct _CMOCK_GbCreate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GROUPBOX* ReturnVal;
  WORD Expected_ID;
  SHORT Expected_left;
  SHORT Expected_top;
  SHORT Expected_right;
  SHORT Expected_bottom;
  WORD Expected_state;
  XCHAR* Expected_pText;
  GOL_SCHEME* Expected_pScheme;

} CMOCK_GbCreate_CALL_INSTANCE;

typedef struct _CMOCK_GbDraw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WORD ReturnVal;
  GROUPBOX* Expected_pGb;

} CMOCK_GbDraw_CALL_INSTANCE;

static struct MockGroupBoxInstance
{
  CMOCK_MEM_INDEX_TYPE GbSetText_CallInstance;
  CMOCK_MEM_INDEX_TYPE GbTranslateMsg_CallInstance;
  CMOCK_MEM_INDEX_TYPE GbCreate_CallInstance;
  CMOCK_MEM_INDEX_TYPE GbDraw_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockGroupBox_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GbSetText_CallInstance, cmock_line, "Function 'GbSetText' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GbTranslateMsg_CallInstance, cmock_line, "Function 'GbTranslateMsg' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GbCreate_CallInstance, cmock_line, "Function 'GbCreate' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.GbDraw_CallInstance, cmock_line, "Function 'GbDraw' called less times than expected.");
}

void MockGroupBox_Init(void)
{
  MockGroupBox_Destroy();
}

void MockGroupBox_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void GbSetText(GROUPBOX* pGb, XCHAR* pText)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GbSetText_CALL_INSTANCE* cmock_call_instance = (CMOCK_GbSetText_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GbSetText_CallInstance);
  Mock.GbSetText_CallInstance = CMock_Guts_MemNext(Mock.GbSetText_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GbSetText' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGb), (void*)(pGb), sizeof(GROUPBOX), cmock_line, "Function 'GbSetText' called with unexpected value for argument 'pGb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pText), (void*)(pText), sizeof(XCHAR), cmock_line, "Function 'GbSetText' called with unexpected value for argument 'pText'.");
  }
}

void CMockExpectParameters_GbSetText(CMOCK_GbSetText_CALL_INSTANCE* cmock_call_instance, GROUPBOX* pGb, XCHAR* pText)
{
  cmock_call_instance->Expected_pGb = pGb;
  cmock_call_instance->Expected_pText = pText;
}

void GbSetText_CMockExpect(UNITY_LINE_TYPE cmock_line, GROUPBOX* pGb, XCHAR* pText)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GbSetText_CALL_INSTANCE));
  CMOCK_GbSetText_CALL_INSTANCE* cmock_call_instance = (CMOCK_GbSetText_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GbSetText_CallInstance = CMock_Guts_MemChain(Mock.GbSetText_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GbSetText(cmock_call_instance, pGb, pText);
}

WORD GbTranslateMsg(GROUPBOX* pGb, GOL_MSG* pMsg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GbTranslateMsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_GbTranslateMsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GbTranslateMsg_CallInstance);
  Mock.GbTranslateMsg_CallInstance = CMock_Guts_MemNext(Mock.GbTranslateMsg_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GbTranslateMsg' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGb), (void*)(pGb), sizeof(GROUPBOX), cmock_line, "Function 'GbTranslateMsg' called with unexpected value for argument 'pGb'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMsg), (void*)(pMsg), sizeof(GOL_MSG), cmock_line, "Function 'GbTranslateMsg' called with unexpected value for argument 'pMsg'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_GbTranslateMsg(CMOCK_GbTranslateMsg_CALL_INSTANCE* cmock_call_instance, GROUPBOX* pGb, GOL_MSG* pMsg)
{
  cmock_call_instance->Expected_pGb = pGb;
  cmock_call_instance->Expected_pMsg = pMsg;
}

void GbTranslateMsg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GROUPBOX* pGb, GOL_MSG* pMsg, WORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GbTranslateMsg_CALL_INSTANCE));
  CMOCK_GbTranslateMsg_CALL_INSTANCE* cmock_call_instance = (CMOCK_GbTranslateMsg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GbTranslateMsg_CallInstance = CMock_Guts_MemChain(Mock.GbTranslateMsg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GbTranslateMsg(cmock_call_instance, pGb, pMsg);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(WORD));
}

GROUPBOX* GbCreate(WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, XCHAR* pText, GOL_SCHEME* pScheme)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GbCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_GbCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GbCreate_CallInstance);
  Mock.GbCreate_CallInstance = CMock_Guts_MemNext(Mock.GbCreate_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GbCreate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ID), (void*)(&ID), sizeof(WORD), cmock_line, "Function 'GbCreate' called with unexpected value for argument 'ID'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_left), (void*)(&left), sizeof(SHORT), cmock_line, "Function 'GbCreate' called with unexpected value for argument 'left'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_top), (void*)(&top), sizeof(SHORT), cmock_line, "Function 'GbCreate' called with unexpected value for argument 'top'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_right), (void*)(&right), sizeof(SHORT), cmock_line, "Function 'GbCreate' called with unexpected value for argument 'right'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bottom), (void*)(&bottom), sizeof(SHORT), cmock_line, "Function 'GbCreate' called with unexpected value for argument 'bottom'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(WORD), cmock_line, "Function 'GbCreate' called with unexpected value for argument 'state'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pText), (void*)(pText), sizeof(XCHAR), cmock_line, "Function 'GbCreate' called with unexpected value for argument 'pText'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pScheme), (void*)(pScheme), sizeof(GOL_SCHEME), cmock_line, "Function 'GbCreate' called with unexpected value for argument 'pScheme'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_GbCreate(CMOCK_GbCreate_CALL_INSTANCE* cmock_call_instance, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, XCHAR* pText, GOL_SCHEME* pScheme)
{
  memcpy(&cmock_call_instance->Expected_ID, &ID, sizeof(WORD));
  memcpy(&cmock_call_instance->Expected_left, &left, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_top, &top, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_right, &right, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_bottom, &bottom, sizeof(SHORT));
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(WORD));
  cmock_call_instance->Expected_pText = pText;
  cmock_call_instance->Expected_pScheme = pScheme;
}

void GbCreate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD ID, SHORT left, SHORT top, SHORT right, SHORT bottom, WORD state, XCHAR* pText, GOL_SCHEME* pScheme, GROUPBOX* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GbCreate_CALL_INSTANCE));
  CMOCK_GbCreate_CALL_INSTANCE* cmock_call_instance = (CMOCK_GbCreate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GbCreate_CallInstance = CMock_Guts_MemChain(Mock.GbCreate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GbCreate(cmock_call_instance, ID, left, top, right, bottom, state, pText, pScheme);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

WORD GbDraw(GROUPBOX* pGb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_GbDraw_CALL_INSTANCE* cmock_call_instance = (CMOCK_GbDraw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.GbDraw_CallInstance);
  Mock.GbDraw_CallInstance = CMock_Guts_MemNext(Mock.GbDraw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'GbDraw' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGb), (void*)(pGb), sizeof(GROUPBOX), cmock_line, "Function 'GbDraw' called with unexpected value for argument 'pGb'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_GbDraw(CMOCK_GbDraw_CALL_INSTANCE* cmock_call_instance, GROUPBOX* pGb)
{
  cmock_call_instance->Expected_pGb = pGb;
}

void GbDraw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GROUPBOX* pGb, WORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_GbDraw_CALL_INSTANCE));
  CMOCK_GbDraw_CALL_INSTANCE* cmock_call_instance = (CMOCK_GbDraw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.GbDraw_CallInstance = CMock_Guts_MemChain(Mock.GbDraw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_GbDraw(cmock_call_instance, pGb);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(WORD));
}

