/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKAUTORATE_H
#define _MOCKAUTORATE_H

#include "autorate.h"

void Mockautorate_Init(void);
void Mockautorate_Destroy(void);
void Mockautorate_Verify(void);




#define newAutoRateAverage_ExpectAndReturn(initialAverage, sampleRate, minTimeThreshold, autoRate, autoRateSetting, fixedRate, cmock_retval) newAutoRateAverage_CMockExpectAndReturn(__LINE__, initialAverage, sampleRate, minTimeThreshold, autoRate, autoRateSetting, fixedRate, cmock_retval)
void newAutoRateAverage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, float initialAverage, int sampleRate, int minTimeThreshold, BOOL autoRate, AutoRateSetting autoRateSetting, int fixedRate, AutoRateAverage* cmock_to_return);
#define newDefaultAutoRateAverage_ExpectAndReturn(cmock_retval) newDefaultAutoRateAverage_CMockExpectAndReturn(__LINE__, cmock_retval)
void newDefaultAutoRateAverage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, AutoRateAverage* cmock_to_return);
#define autoRateGetAverage_ExpectAndReturn(autoRateAverage, cmock_retval) autoRateGetAverage_CMockExpectAndReturn(__LINE__, autoRateAverage, cmock_retval)
void autoRateGetAverage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, AutoRateAverage* autoRateAverage, float cmock_to_return);
#define autoRateGetFastMinTime_ExpectAndReturn(autoRateAverage, cmock_retval) autoRateGetFastMinTime_CMockExpectAndReturn(__LINE__, autoRateAverage, cmock_retval)
void autoRateGetFastMinTime_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, AutoRateAverage* autoRateAverage, int cmock_to_return);
#define autoRateGetFastMaxTime_ExpectAndReturn(autoRateAverage, cmock_retval) autoRateGetFastMaxTime_CMockExpectAndReturn(__LINE__, autoRateAverage, cmock_retval)
void autoRateGetFastMaxTime_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, AutoRateAverage* autoRateAverage, int cmock_to_return);
#define autoRateGetSlowMinTime_ExpectAndReturn(autoRateAverage, cmock_retval) autoRateGetSlowMinTime_CMockExpectAndReturn(__LINE__, autoRateAverage, cmock_retval)
void autoRateGetSlowMinTime_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, AutoRateAverage* autoRateAverage, int cmock_to_return);
#define autoRateGetSlowMaxTime_ExpectAndReturn(autoRateAverage, cmock_retval) autoRateGetSlowMaxTime_CMockExpectAndReturn(__LINE__, autoRateAverage, cmock_retval)
void autoRateGetSlowMaxTime_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, AutoRateAverage* autoRateAverage, int cmock_to_return);
#define autoRateSetFastMinTime_Expect(autoRateAverage, fastMinTime) autoRateSetFastMinTime_CMockExpect(__LINE__, autoRateAverage, fastMinTime)
void autoRateSetFastMinTime_CMockExpect(UNITY_LINE_TYPE cmock_line, AutoRateAverage* autoRateAverage, int fastMinTime);
#define autoRateSetFastMaxTime_Expect(autoRateAverage, fastMaxTime) autoRateSetFastMaxTime_CMockExpect(__LINE__, autoRateAverage, fastMaxTime)
void autoRateSetFastMaxTime_CMockExpect(UNITY_LINE_TYPE cmock_line, AutoRateAverage* autoRateAverage, int fastMaxTime);
#define autoRateSetSlowMinTime_Expect(autoRateAverage, slowMinTime) autoRateSetSlowMinTime_CMockExpect(__LINE__, autoRateAverage, slowMinTime)
void autoRateSetSlowMinTime_CMockExpect(UNITY_LINE_TYPE cmock_line, AutoRateAverage* autoRateAverage, int slowMinTime);
#define autoRateSetSlowMaxTime_Expect(autoRateAverage, slowMaxTime) autoRateSetSlowMaxTime_CMockExpect(__LINE__, autoRateAverage, slowMaxTime)
void autoRateSetSlowMaxTime_CMockExpect(UNITY_LINE_TYPE cmock_line, AutoRateAverage* autoRateAverage, int slowMaxTime);
#define updateAutoRateSettings_Expect(autoRateAverage, autoRate, autoRateSetting, fixedRate) updateAutoRateSettings_CMockExpect(__LINE__, autoRateAverage, autoRate, autoRateSetting, fixedRate)
void updateAutoRateSettings_CMockExpect(UNITY_LINE_TYPE cmock_line, AutoRateAverage* autoRateAverage, BOOL autoRate, AutoRateSetting autoRateSetting, int fixedRate);

#endif
