/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKUSB_HOST_GENERIC_H
#define _MOCKUSB_HOST_GENERIC_H

#include "usb_host_generic.h"

void Mockusb_host_generic_Init(void);
void Mockusb_host_generic_Destroy(void);
void Mockusb_host_generic_Verify(void);




#define USBHostGenericInit_ExpectAndReturn(address, flags, clientDriverID, cmock_retval) USBHostGenericInit_CMockExpectAndReturn(__LINE__, address, flags, clientDriverID, cmock_retval)
void USBHostGenericInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE address, DWORD flags, BYTE clientDriverID, BOOL cmock_to_return);
#define USBHostGenericEventHandler_ExpectAndReturn(address, event, data, size, cmock_retval) USBHostGenericEventHandler_CMockExpectAndReturn(__LINE__, address, event, data, size, cmock_retval)
void USBHostGenericEventHandler_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE address, USB_EVENT event, void* data, DWORD size, BOOL cmock_to_return);
#define USBHostGenericGetDeviceAddress_ExpectAndReturn(pDevID, cmock_retval) USBHostGenericGetDeviceAddress_CMockExpectAndReturn(__LINE__, pDevID, cmock_retval)
void USBHostGenericGetDeviceAddress_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GENERIC_DEVICE_ID* pDevID, BOOL cmock_to_return);
#define USBHostGenericRead_ExpectAndReturn(deviceAddress, buffer, length, cmock_retval) USBHostGenericRead_CMockExpectAndReturn(__LINE__, deviceAddress, buffer, length, cmock_retval)
void USBHostGenericRead_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, void* buffer, DWORD length, BYTE cmock_to_return);
#define USBHostGenericRxIsComplete_ExpectAndReturn(deviceAddress, errorCode, byteCount, cmock_retval) USBHostGenericRxIsComplete_CMockExpectAndReturn(__LINE__, deviceAddress, errorCode, byteCount, cmock_retval)
void USBHostGenericRxIsComplete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE* errorCode, DWORD* byteCount, BOOL cmock_to_return);
#define USBHostGenericTasks_Expect() USBHostGenericTasks_CMockExpect(__LINE__)
void USBHostGenericTasks_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define USBHostGenericTxIsComplete_ExpectAndReturn(deviceAddress, errorCode, cmock_retval) USBHostGenericTxIsComplete_CMockExpectAndReturn(__LINE__, deviceAddress, errorCode, cmock_retval)
void USBHostGenericTxIsComplete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE* errorCode, BOOL cmock_to_return);
#define USBHostGenericWrite_ExpectAndReturn(deviceAddress, buffer, length, cmock_retval) USBHostGenericWrite_CMockExpectAndReturn(__LINE__, deviceAddress, buffer, length, cmock_retval)
void USBHostGenericWrite_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, void* buffer, DWORD length, BYTE cmock_to_return);

#endif
