/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKJPEGDEMO_H
#define _MOCKJPEGDEMO_H

#include "JPEGDemo.h"

void MockJPEGDemo_Init(void);
void MockJPEGDemo_Destroy(void);
void MockJPEGDemo_Verify(void);




#define CreateJPEGDemo_ExpectAndReturn(cmock_retval) CreateJPEGDemo_CMockExpectAndReturn(__LINE__, cmock_retval)
void CreateJPEGDemo_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD cmock_to_return);
#define JPEGMsgCallback_ExpectAndReturn(objMsg, pObj, pMsg, cmock_retval) JPEGMsgCallback_CMockExpectAndReturn(__LINE__, objMsg, pObj, pMsg, cmock_retval)
void JPEGMsgCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD objMsg, OBJ_HEADER* pObj, GOL_MSG* pMsg, WORD cmock_to_return);
#define JPEGDrawCallback_ExpectAndReturn(cmock_retval) JPEGDrawCallback_CMockExpectAndReturn(__LINE__, cmock_retval)
void JPEGDrawCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, WORD cmock_to_return);
#define MonitorThumbDriveMedia_Expect() MonitorThumbDriveMedia_CMockExpect(__LINE__)
void MonitorThumbDriveMedia_CMockExpect(UNITY_LINE_TYPE cmock_line);

#endif
