/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockusb_host_generic.h"

typedef struct _CMOCK_USBHostGenericInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_address;
  DWORD Expected_flags;
  BYTE Expected_clientDriverID;

} CMOCK_USBHostGenericInit_CALL_INSTANCE;

typedef struct _CMOCK_USBHostGenericEventHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_address;
  USB_EVENT Expected_event;
  void* Expected_data;
  DWORD Expected_size;

} CMOCK_USBHostGenericEventHandler_CALL_INSTANCE;

typedef struct _CMOCK_USBHostGenericGetDeviceAddress_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  GENERIC_DEVICE_ID* Expected_pDevID;

} CMOCK_USBHostGenericGetDeviceAddress_CALL_INSTANCE;

typedef struct _CMOCK_USBHostGenericRead_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;
  void* Expected_buffer;
  DWORD Expected_length;

} CMOCK_USBHostGenericRead_CALL_INSTANCE;

typedef struct _CMOCK_USBHostGenericRxIsComplete_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE* Expected_errorCode;
  DWORD* Expected_byteCount;

} CMOCK_USBHostGenericRxIsComplete_CALL_INSTANCE;

typedef struct _CMOCK_USBHostGenericTasks_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_USBHostGenericTasks_CALL_INSTANCE;

typedef struct _CMOCK_USBHostGenericTxIsComplete_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BOOL ReturnVal;
  BYTE Expected_deviceAddress;
  BYTE* Expected_errorCode;

} CMOCK_USBHostGenericTxIsComplete_CALL_INSTANCE;

typedef struct _CMOCK_USBHostGenericWrite_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BYTE ReturnVal;
  BYTE Expected_deviceAddress;
  void* Expected_buffer;
  DWORD Expected_length;

} CMOCK_USBHostGenericWrite_CALL_INSTANCE;

static struct Mockusb_host_genericInstance
{
  CMOCK_MEM_INDEX_TYPE USBHostGenericInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostGenericEventHandler_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostGenericGetDeviceAddress_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostGenericRead_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostGenericRxIsComplete_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostGenericTasks_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostGenericTxIsComplete_CallInstance;
  CMOCK_MEM_INDEX_TYPE USBHostGenericWrite_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockusb_host_generic_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostGenericInit_CallInstance, cmock_line, "Function 'USBHostGenericInit' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostGenericEventHandler_CallInstance, cmock_line, "Function 'USBHostGenericEventHandler' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostGenericGetDeviceAddress_CallInstance, cmock_line, "Function 'USBHostGenericGetDeviceAddress' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostGenericRead_CallInstance, cmock_line, "Function 'USBHostGenericRead' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostGenericRxIsComplete_CallInstance, cmock_line, "Function 'USBHostGenericRxIsComplete' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostGenericTasks_CallInstance, cmock_line, "Function 'USBHostGenericTasks' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostGenericTxIsComplete_CallInstance, cmock_line, "Function 'USBHostGenericTxIsComplete' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.USBHostGenericWrite_CallInstance, cmock_line, "Function 'USBHostGenericWrite' called less times than expected.");
}

void Mockusb_host_generic_Init(void)
{
  Mockusb_host_generic_Destroy();
}

void Mockusb_host_generic_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

BOOL USBHostGenericInit(BYTE address, DWORD flags, BYTE clientDriverID)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostGenericInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostGenericInit_CallInstance);
  Mock.USBHostGenericInit_CallInstance = CMock_Guts_MemNext(Mock.USBHostGenericInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostGenericInit' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_address), (void*)(&address), sizeof(BYTE), cmock_line, "Function 'USBHostGenericInit' called with unexpected value for argument 'address'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_flags), (void*)(&flags), sizeof(DWORD), cmock_line, "Function 'USBHostGenericInit' called with unexpected value for argument 'flags'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_clientDriverID), (void*)(&clientDriverID), sizeof(BYTE), cmock_line, "Function 'USBHostGenericInit' called with unexpected value for argument 'clientDriverID'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostGenericInit(CMOCK_USBHostGenericInit_CALL_INSTANCE* cmock_call_instance, BYTE address, DWORD flags, BYTE clientDriverID)
{
  memcpy(&cmock_call_instance->Expected_address, &address, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_flags, &flags, sizeof(DWORD));
  memcpy(&cmock_call_instance->Expected_clientDriverID, &clientDriverID, sizeof(BYTE));
}

void USBHostGenericInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE address, DWORD flags, BYTE clientDriverID, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostGenericInit_CALL_INSTANCE));
  CMOCK_USBHostGenericInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostGenericInit_CallInstance = CMock_Guts_MemChain(Mock.USBHostGenericInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostGenericInit(cmock_call_instance, address, flags, clientDriverID);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BOOL USBHostGenericEventHandler(BYTE address, USB_EVENT event, void* data, DWORD size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostGenericEventHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericEventHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostGenericEventHandler_CallInstance);
  Mock.USBHostGenericEventHandler_CallInstance = CMock_Guts_MemNext(Mock.USBHostGenericEventHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostGenericEventHandler' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_address), (void*)(&address), sizeof(BYTE), cmock_line, "Function 'USBHostGenericEventHandler' called with unexpected value for argument 'address'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_event), (void*)(&event), sizeof(USB_EVENT), cmock_line, "Function 'USBHostGenericEventHandler' called with unexpected value for argument 'event'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_data, data, cmock_line, "Function 'USBHostGenericEventHandler' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(DWORD), cmock_line, "Function 'USBHostGenericEventHandler' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostGenericEventHandler(CMOCK_USBHostGenericEventHandler_CALL_INSTANCE* cmock_call_instance, BYTE address, USB_EVENT event, void* data, DWORD size)
{
  memcpy(&cmock_call_instance->Expected_address, &address, sizeof(BYTE));
  memcpy(&cmock_call_instance->Expected_event, &event, sizeof(USB_EVENT));
  cmock_call_instance->Expected_data = data;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(DWORD));
}

void USBHostGenericEventHandler_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE address, USB_EVENT event, void* data, DWORD size, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostGenericEventHandler_CALL_INSTANCE));
  CMOCK_USBHostGenericEventHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericEventHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostGenericEventHandler_CallInstance = CMock_Guts_MemChain(Mock.USBHostGenericEventHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostGenericEventHandler(cmock_call_instance, address, event, data, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BOOL USBHostGenericGetDeviceAddress(GENERIC_DEVICE_ID* pDevID)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostGenericGetDeviceAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericGetDeviceAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostGenericGetDeviceAddress_CallInstance);
  Mock.USBHostGenericGetDeviceAddress_CallInstance = CMock_Guts_MemNext(Mock.USBHostGenericGetDeviceAddress_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostGenericGetDeviceAddress' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pDevID), (void*)(pDevID), sizeof(GENERIC_DEVICE_ID), cmock_line, "Function 'USBHostGenericGetDeviceAddress' called with unexpected value for argument 'pDevID'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostGenericGetDeviceAddress(CMOCK_USBHostGenericGetDeviceAddress_CALL_INSTANCE* cmock_call_instance, GENERIC_DEVICE_ID* pDevID)
{
  cmock_call_instance->Expected_pDevID = pDevID;
}

void USBHostGenericGetDeviceAddress_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GENERIC_DEVICE_ID* pDevID, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostGenericGetDeviceAddress_CALL_INSTANCE));
  CMOCK_USBHostGenericGetDeviceAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericGetDeviceAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostGenericGetDeviceAddress_CallInstance = CMock_Guts_MemChain(Mock.USBHostGenericGetDeviceAddress_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostGenericGetDeviceAddress(cmock_call_instance, pDevID);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BYTE USBHostGenericRead(BYTE deviceAddress, void* buffer, DWORD length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostGenericRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostGenericRead_CallInstance);
  Mock.USBHostGenericRead_CallInstance = CMock_Guts_MemNext(Mock.USBHostGenericRead_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostGenericRead' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostGenericRead' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_buffer, buffer, cmock_line, "Function 'USBHostGenericRead' called with unexpected value for argument 'buffer'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_length), (void*)(&length), sizeof(DWORD), cmock_line, "Function 'USBHostGenericRead' called with unexpected value for argument 'length'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostGenericRead(CMOCK_USBHostGenericRead_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, void* buffer, DWORD length)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  cmock_call_instance->Expected_buffer = buffer;
  memcpy(&cmock_call_instance->Expected_length, &length, sizeof(DWORD));
}

void USBHostGenericRead_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, void* buffer, DWORD length, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostGenericRead_CALL_INSTANCE));
  CMOCK_USBHostGenericRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostGenericRead_CallInstance = CMock_Guts_MemChain(Mock.USBHostGenericRead_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostGenericRead(cmock_call_instance, deviceAddress, buffer, length);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

BOOL USBHostGenericRxIsComplete(BYTE deviceAddress, BYTE* errorCode, DWORD* byteCount)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostGenericRxIsComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericRxIsComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostGenericRxIsComplete_CallInstance);
  Mock.USBHostGenericRxIsComplete_CallInstance = CMock_Guts_MemNext(Mock.USBHostGenericRxIsComplete_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostGenericRxIsComplete' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostGenericRxIsComplete' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_errorCode), (void*)(errorCode), sizeof(BYTE), cmock_line, "Function 'USBHostGenericRxIsComplete' called with unexpected value for argument 'errorCode'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_byteCount), (void*)(byteCount), sizeof(DWORD), cmock_line, "Function 'USBHostGenericRxIsComplete' called with unexpected value for argument 'byteCount'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostGenericRxIsComplete(CMOCK_USBHostGenericRxIsComplete_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE* errorCode, DWORD* byteCount)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  cmock_call_instance->Expected_errorCode = errorCode;
  cmock_call_instance->Expected_byteCount = byteCount;
}

void USBHostGenericRxIsComplete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE* errorCode, DWORD* byteCount, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostGenericRxIsComplete_CALL_INSTANCE));
  CMOCK_USBHostGenericRxIsComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericRxIsComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostGenericRxIsComplete_CallInstance = CMock_Guts_MemChain(Mock.USBHostGenericRxIsComplete_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostGenericRxIsComplete(cmock_call_instance, deviceAddress, errorCode, byteCount);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void USBHostGenericTasks(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostGenericTasks_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericTasks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostGenericTasks_CallInstance);
  Mock.USBHostGenericTasks_CallInstance = CMock_Guts_MemNext(Mock.USBHostGenericTasks_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostGenericTasks' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void USBHostGenericTasks_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostGenericTasks_CALL_INSTANCE));
  CMOCK_USBHostGenericTasks_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericTasks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostGenericTasks_CallInstance = CMock_Guts_MemChain(Mock.USBHostGenericTasks_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

BOOL USBHostGenericTxIsComplete(BYTE deviceAddress, BYTE* errorCode)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostGenericTxIsComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericTxIsComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostGenericTxIsComplete_CallInstance);
  Mock.USBHostGenericTxIsComplete_CallInstance = CMock_Guts_MemNext(Mock.USBHostGenericTxIsComplete_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostGenericTxIsComplete' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostGenericTxIsComplete' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_errorCode), (void*)(errorCode), sizeof(BYTE), cmock_line, "Function 'USBHostGenericTxIsComplete' called with unexpected value for argument 'errorCode'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostGenericTxIsComplete(CMOCK_USBHostGenericTxIsComplete_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, BYTE* errorCode)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  cmock_call_instance->Expected_errorCode = errorCode;
}

void USBHostGenericTxIsComplete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, BYTE* errorCode, BOOL cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostGenericTxIsComplete_CALL_INSTANCE));
  CMOCK_USBHostGenericTxIsComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericTxIsComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostGenericTxIsComplete_CallInstance = CMock_Guts_MemChain(Mock.USBHostGenericTxIsComplete_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostGenericTxIsComplete(cmock_call_instance, deviceAddress, errorCode);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

BYTE USBHostGenericWrite(BYTE deviceAddress, void* buffer, DWORD length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_USBHostGenericWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.USBHostGenericWrite_CallInstance);
  Mock.USBHostGenericWrite_CallInstance = CMock_Guts_MemNext(Mock.USBHostGenericWrite_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'USBHostGenericWrite' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_deviceAddress), (void*)(&deviceAddress), sizeof(BYTE), cmock_line, "Function 'USBHostGenericWrite' called with unexpected value for argument 'deviceAddress'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_buffer, buffer, cmock_line, "Function 'USBHostGenericWrite' called with unexpected value for argument 'buffer'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_length), (void*)(&length), sizeof(DWORD), cmock_line, "Function 'USBHostGenericWrite' called with unexpected value for argument 'length'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_USBHostGenericWrite(CMOCK_USBHostGenericWrite_CALL_INSTANCE* cmock_call_instance, BYTE deviceAddress, void* buffer, DWORD length)
{
  memcpy(&cmock_call_instance->Expected_deviceAddress, &deviceAddress, sizeof(BYTE));
  cmock_call_instance->Expected_buffer = buffer;
  memcpy(&cmock_call_instance->Expected_length, &length, sizeof(DWORD));
}

void USBHostGenericWrite_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE deviceAddress, void* buffer, DWORD length, BYTE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_USBHostGenericWrite_CALL_INSTANCE));
  CMOCK_USBHostGenericWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_USBHostGenericWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.USBHostGenericWrite_CallInstance = CMock_Guts_MemChain(Mock.USBHostGenericWrite_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_USBHostGenericWrite(cmock_call_instance, deviceAddress, buffer, length);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(BYTE));
}

